vllm-project/vllm-ascend

- vllm_ascend/model_runner.py
a fix follow up [MRotaryEmbedding change](https://github.com/vllm-project/vllm/commit/bf3b79efb82676219a3275764d8fcf4c70097ce5#diff-6bc44986c91bf0876240dec03d56c748403691c7fcd90f7a22e7affff7b033ecR839)
> bugfix for mrope

- vllm_ascend/utils.py
- vllm_ascend/worker.py
Add `try_register_lib` and import mindie-turbo when init.
> [Worker] Register mindie_turbo while initializing NPUWorker

- vllm_ascend/communicator.py
- vllm_ascend/patch/__init__.py
- vllm_ascend/patch/patch_commnicator.py
- vllm_ascend/platform.py
Some PR for plugin support is not merged by vllm yet. This PR add monkey patch to vllm-ascend to make vllm-ascend work with vllm directly.
This patch code should be removed once the related function is supported by vllm originally.
cherry pick to 0.7.1
> [Communicator] Add monkey patch (#30)

- setup.py
fix packages for finding submodule. 
see #42
> [Misc][Build] Fix packages for finding submodule

- setup.py
- vllm_ascend/patch/patch_commnicator.py
- vllm_ascend/platform.py
- vllm_ascend/worker.py
fix communicator patch so parallel could work.
see #52
> [dist] fix communicator patch

- .github/workflows/vllm_ascend_test.yaml
Switch to cann latest version
No
CI passed
> [CI] Switch to cann latest version

- docs/source/index.md
- docs/source/installation.md
- docs/source/tutorials.md
Add vllm-ascend tutorials for v0.7.1.
no.
no.
> [Doc] Add vllm-ascend tutorials for v0.7.1

- docs/source/tutorials.md
> [Doc] Update tutorials

- README.md
- README.zh.md
- docs/source/installation.md
Refeactor installation doc
No
CI, preview
> [Docs] Refeactor installation doc

- docs/source/tutorials.md
Update tutorials.
Backport https://github.com/vllm-project/vllm-ascend/pull/79
no.
ci.
> [v0.7.1][Doc] Update tutorials

- examples/offline_distributed_inference_npu.py
- examples/offline_inference_audio_language.py
- examples/offline_inference_npu.py
> [MISC] set default model to qwen in example

- docs/README.md
- docs/requirements-docs.txt
- docs/source/conf.py
- docs/source/installation.md
- docs/source/quick_start.md
Add dynamic version in docs
No
Preview: https://vllm-ascend--90.org.readthedocs.build/en/90/
> [Docs] Add dynamic version in docs

- docs/README.md
- docs/requirements-docs.txt
- docs/source/conf.py
- docs/source/installation.md
- docs/source/quick_start.md
cherry-pick from https://github.com/vllm-project/vllm-ascend/pull/90
> [Docs] Add dynamic version in docs (#90)

- .github/workflows/vllm_ascend_test.yaml
- Dockerfile
- docs/source/conf.py
- docs/source/developer_guide/contributing.md
- docs/source/developer_guide/versioning_policy.md
- docs/source/developer_guide/versioning_policy.zh.md
- docs/source/installation.md
- docs/source/quick_start.md
- docs/source/tutorials.md
- docs/source/user_guide/release_notes.md
- docs/source/user_guide/supported_models.md
1. Update CANN image name
2. Add pta install step
3. update vllm-ascend docker image name to ghcr
4. update quick_start to use vllm-ascend image directly.
5. fix `note` style
> [Doc] Update doc to work with release

- vllm_ascend/attention.py
fix an accuracy problem caused by missing of value contiguous
> [BugFix] Add value.contiguous in attention to avoid some accuracy problems.

- .github/workflows/image.yml
- Dockerfile
- docs/source/conf.py
- docs/source/installation.md
- pta_install.sh
- pyproject.toml
- requirements.txt
Final update for 0.7.1.rc1 release.
1. Update the version in doc
2. Update dockerfile
> [Release] doc and dockerfile update for 0.7.1.rc1

- docs/source/user_guide/supported_models.md
- docs/source/user_guide/suppoted_features.md
Update feature and model lists
> [doc] update feature and model lists

- .github/workflows/image.yml
- docs/source/quick_start.md
- docs/source/tutorials.md
change docker registry to quay
> [CI] change to quay.io

- docs/source/user_guide/suppoted_features.md
> [doc] update feature support plan

- .github/workflows/image.yml
- docs/source/conf.py
- docs/source/developer_guide/versioning_policy.md
- docs/source/tutorials.md
- docs/source/user_guide/release_notes.md
Don't login docker registry in pull request.
> [CI] Skip registry login if not push

- docs/source/user_guide/supported_models.md
> [doc] update model list

- docs/source/conf.py
- docs/source/installation.md
- docs/source/quick_start.md
- docs/source/tutorials.md
Fix vllm and vllm-ascend version 
| branch/tag | vllm_version | vllm_ascend_version|pip_vllm_ascend_version|pip_vllm_version|
|----|----|----|----|----|
| main | main | main | v0.7.1rc1 | v0.7.1 |
| v0.7.1-dev | v0.7.1 | v0.7.1rc1 | v0.7.1rc1 | v0.7.1 |
| v0.7.1rc1 | v0.7.1 | v0.7.1rc1 | v0.7.1rc1 | v0.7.1 |
No
CI passed
> [Docs] Fix vllm and vllm-ascend version 

- docs/source/tutorials.md
Add Tutorials for Online Serving on Multi Machine
> [Docs] Add Tutorials for Online Serving on Multi Machine

- .github/workflows/actionlint.yml
- .github/workflows/mypy.yaml
- .github/workflows/ruff.yml
- .github/workflows/shellcheck.yml
- .github/workflows/vllm_ascend_test.yaml
- .github/workflows/yapf.yml
- packages.txt
- pytest.ini
- requirements-dev.txt
- requirements.txt
Enable CI on all branch.
Installing with the torch-npu-2.5.1.dev20250218 so that we could enable CI on all branch and prepare for merging 0.7.1-dev to main
> [CI] enable CI on all branch

- .github/workflows/vllm_ascend_test.yaml
- vllm_ascend/attention.py
- vllm_ascend/model_runner.py
- vllm_ascend/ops/activation.py
- vllm_ascend/ops/fused_moe.py
- vllm_ascend/ops/rotary_embedding.py
- vllm_ascend/platform.py
- vllm_ascend/quantization/quant_config.py
- vllm_ascend/quantization/quantizer.py
Cherry pick from 0.7.1 to keep the main code newest
> [Core] Cherry pick from 0.7.1 to keep the main code newest

- .github/workflows/vllm_ascend_test.yaml
- docs/source/conf.py
- docs/source/installation.md
- pyproject.toml
- requirements.txt
> [Build] Make CI work on 0.7.3-dev

- vllm_ascend/attention.py
- vllm_ascend/model_runner.py
- vllm_ascend/ops/fused_moe.py
- vllm_ascend/ops/rotary_embedding.py
Eliminate redundant operations in the code to improve performance
No
> modify:Eliminate redundant operations in the code to improve performance

- docs/source/installation.md
- docs/source/tutorials.md
Fix doc issue
Close: https://github.com/vllm-project/vllm-ascend/issues/144
Related: https://github.com/vllm-project/vllm-ascend/issues/106
> [Doc] fix doc issue

- .github/workflows/vllm_ascend_test.yaml
enable test if pytest.ini changes
> [CI] enable test if pytest.ini changes

- vllm_ascend/model_runner.py
Remove padding for vlm inputs.
We don't need padding inputs now, this padding will break the input preparetion of VLMs.
N/A
> [ModelRunner] remove padding for vlm inputs

- .github/workflows/image.yml
- Dockerfile.CI
- docs/source/conf.py
- docs/source/installation.md
Image build CI do cross compile on x86 which doesn't work for vllm.
This PR make Dockerfile work with CI.
> [Build] Fix dockerfile for 0.7.3

- .github/workflows/vllm_ascend_test.yaml
Fix the bug introduced by #173
> [CI] fix hf_token

- vllm_ascend/worker.py
> [Bugfix] Fix AssertError in vllm_ascend/worker.py

- docs/source/tutorials.md
- vllm_ascend/model_runner.py
1. Fix cuda hard code in model runner.
2. Fix tutorials doc rendering error.
no.
no.
> [ModelRunner] Fix cuda hard code in model runner

- .github/workflows/vllm_ascend_test.yaml
- docs/source/installation.md
- vllm_ascend/attention.py
- vllm_ascend/ops/rotary_embedding.py
> [CI] upgrade to newest pta

- .github/workflows/vllm_ascend_test.yaml
- docs/source/installation.md
- vllm_ascend/attention.py
- vllm_ascend/ops/rotary_embedding.py
see: https://github.com/vllm-project/vllm-ascend/pull/187
> [CI] upgrade to newest pta (#187)

- vllm_ascend/attention.py
- vllm_ascend/ops/fused_moe.py
Upgrade to newest pta.(MLA and FusedMoE)
> [CI] Upgrade to newest pta.(MLA and FusedMoE)

- .github/dependabot.yml
- .github/labeler.yml
- .github/workflows/image.yml
- .github/workflows/labeler.yml
Add dependabot support and labeler workflow
> [CI] Add dependabot support and labeler workflow

- vllm_ascend/ops/rotary_embedding.py
This PR fix some unsolved bugs caused by pta api change.
> [CI] Fix unsolved bugs caused by pta api change.

- Dockerfile
- pta_install.sh
Install torch-npu in Dockerfile
> [Build] Fix dockerfile bug

- Dockerfile
Add ray to docker image to make `ray` work
No
CI passed
> Add ray to docker image

- vllm_ascend/attention.py
- vllm_ascend/ops/rotary_embedding.py
> Upgrade to newest pta

- docs/source/developer_guide/versioning_policy.md
- docs/source/developer_guide/versioning_policy.zh.md
Add Document Branch Policy
No
CI passed
Related: https://github.com/vllm-project/vllm-ascend/issues/214
> Add Document Branch Policy

- .github/workflows/vllm_ascend_test.yaml
- Dockerfile
- README.md
- README.zh.md
- docs/source/conf.py
- docs/source/installation.md
- pta_install.sh
Recover vllm-ascend dev image
No
CI passed
> Recover vllm-ascend dev image

- vllm_ascend/communicator.py
> [Dist] Set device as rank

- docs/source/user_guide/suppoted_features.md
Update Feature Support doc.
no.
no.
> [Doc] Update Feature Support doc

- docs/source/user_guide/suppoted_features.md
- vllm_ascend/attention.py
- vllm_ascend/platform.py
- vllm_ascend/worker/model_runner.py
- vllm_ascend/worker/pooling_model_runner.py
- vllm_ascend/worker/worker.py
Cherry pick pooling and guided decoding from main to 0.7.3-dev
> Cherry pick from main

- vllm_ascend/ops/fused_moe.py
Remove npu_group_topk before CANN version update.
> [Fix] Remove npu_group_topk before CANN version update

- vllm_ascend/ops/fused_moe.py
Remove npu_group_topk before CANN version update.
> [Fix] Remove npu_group_topk before CANN version update.

- docs/source/faqs.md
- docs/source/index.md
> [Doc] Add initial FAQs

- setup.py
- vllm_ascend/__init__.py
- vllm_ascend/attention.py
- vllm_ascend/models/__init__.py
- vllm_ascend/models/qwen2_vl.py
- vllm_ascend/quantization/quant_config.py
- vllm_ascend/quantization/quantizer.py
- vllm_ascend/worker/worker.py
cherry pick some change from main to 0.7.3-dev
> Cherry pick main to 0.7.3-dev

- .github/workflows/vllm_ascend_test.yaml
- docs/source/installation.md
- pta_install.sh
> [v0.7.3-dev][CI/Build] update pta

- README.md
- README.zh.md
- docs/source/installation.md
- docs/source/tutorials.md
> [v0.7.3][CI/Build] Bump torch_npu to dev20250307.3

- docs/source/tutorials.md
Update code block
No
CI passed, preview
> [Doc] Update code block

- .github/workflows/mypy.yaml
- README.md
- README.zh.md
- docs/source/developer_guide/contributing.md
- docs/source/developer_guide/contributing.zh.md
Adapt vLLM requirements changes: https://github.com/vllm-project/vllm/commit/206e2577fa9c73f0d8019210e36905ba970fe036#diff-01ec17406c969585ed075609a2bbf2f2f4fe3e3def36946694abe6d4eb60a6f2
No
CI passed
> Adapt vLLM requirements changes to fix main CI

- docs/source/tutorials/multi_npu.md
Fix `ValueError: Unrecognized distributed executor backend tp. Supported values are 'ray', 'mp' 'uni', 'external_launcher' or custom ExecutorBase subclass.`
No
Test on my local node
> [Doc] Change distributed_executor_backend to mp

- docs/source/tutorials/multi_npu.md
Fix `ValueError: Unrecognized distributed executor backend tp. Supported values are 'ray', 'mp' 'uni', 'external_launcher' or custom ExecutorBase subclass.`
No
Test on my local node
> [v0.7.3][Doc] Change distributed_executor_backend to mp

- vllm_ascend/attention.py
- vllm_ascend/platform.py
- vllm_ascend/worker/multi_step_runner.py
- vllm_ascend/worker/multi_step_worker.py
Add multi step scheduler support for vllm-ascend
> 0.7.3 multi step no tests

- vllm_ascend/attention.py
- vllm_ascend/models/qwen2_vl.py
> cherrypick from main to 0.7.3

- vllm_ascend/platform.py
Remove useless code which wrongly introduced by multi step PR .
> remove useless config

- docs/source/tutorials/index.md
- docs/source/tutorials/single_npu_multimodal.md
Add vllm-ascend tutorial doc for Qwen/Qwen2.5-VL-7B-Instruct model Inference/Serving doc
Backport: https://github.com/vllm-project/vllm-ascend/pull/311
no
preview
> [v0.7.3][Doc] Add Single NPU (Qwen2.5-VL-7B) tutorial (#311)

- vllm_ascend/worker/pooling_model_runner.py
Fix pooling model forward api to adapt to vllm 0.7.3
> [Worker] adapt pooling to vllm v0.7.3

- docs/source/tutorials/multi_npu.md
- docs/source/tutorials/single_npu.md
- docs/source/tutorials/single_npu_multimodal.md
Fixed some inappropriate expressions as shown in the title
> [Doc]Fix tutorial doc expression

- docs/source/developer_guide/versioning_policy.md
- docs/source/faqs.md
- docs/source/tutorials/multi_node.md
- docs/source/tutorials/single_npu.md
- docs/source/tutorials/single_npu_multimodal.md
- docs/source/user_guide/release_notes.md
- docs/source/user_guide/supported_models.md
- docs/source/user_guide/suppoted_features.md
Add the release note for 0.7.3rc1
> [Doc] Add the release note for 0.7.3rc1

- docs/source/conf.py
- docs/source/developer_guide/versioning_policy.md
- docs/source/faqs.md
- docs/source/tutorials/multi_node.md
- docs/source/tutorials/multi_npu.md
- docs/source/tutorials/single_npu.md
- docs/source/tutorials/single_npu_multimodal.md
- docs/source/user_guide/release_notes.md
- docs/source/user_guide/supported_models.md
- docs/source/user_guide/suppoted_features.md
Cherry pick doc change from main
> Cherry pick doc change from main

- Dockerfile
Install cpu version of pytorch in x86 to reduce image size
> [Build] Fix x86 image build

- Dockerfile
cherry-pick from main to fix x86 docker image size problem.
> fix x86 docker image build 

- docs/source/user_guide/suppoted_features.md
- vllm_ascend/worker/multi_step_runner.py
add multistep user_guide and  fix multistep bug when using chunked prefill, mulitstep now using 
ModelInputForNPUWithSamplingMetadata but not ModelInputForGPUWithSamplingMetadata
> add multistep user_guide and  fix multistep bug

- docs/source/installation.md
- format.sh
Fix bugs of installation doc and format tool.
no.
no.
> [Doc] Fix bugs of installation doc and format tool

- docs/source/installation.md
- format.sh
> Fix doc issue

- docs/source/user_guide/release_notes.md
> [Doc] Fix release note

- docs/source/user_guide/release_notes.md
- vllm_ascend/attention.py
fix https://github.com/vllm-project/vllm-ascend/issues/321
This pr is a temporary solution for long seq percision issue, will revert when the root cause is fixed
cc @rjg-lyh @wangxiyuan 
Co-authored-by: rjg-lyh <1318825571@qq.com>
> [Attn][bugfix] fix long seq percision issue

- vllm_ascend/worker/multi_step_runner.py
fix multistep worker get model error
> fix multistep get model error

- .github/workflows/actionlint.yml
- .github/workflows/mypy.yaml
- .github/workflows/ruff.yml
- .github/workflows/shellcheck.yml
- .github/workflows/vllm_ascend_test.yaml
- .github/workflows/yapf.yml
- tests/ops/test_fused_moe.py
> [CI] fix race condition problem

- .github/workflows/actionlint.yml
- .github/workflows/mypy.yaml
- .github/workflows/ruff.yml
- .github/workflows/shellcheck.yml
- .github/workflows/vllm_ascend_test.yaml
- .github/workflows/yapf.yml
> [CI] fix race condition problem (#353)

- vllm_ascend/attention.py
remove some useless tensor init to speedup performance
> remove uselesscodes 

- vllm_ascend/attention/attention.py
- vllm_ascend/platform.py
- vllm_ascend/worker/model_runner.py
- vllm_ascend/worker/model_runner_v1.py
- vllm_ascend/worker/worker.py
- vllm_ascend/worker/worker_v1.py
To resolve this [patch](https://github.com/vllm-project/vllm-ascend/pull/236/files#diff-43b96b39b5a52fe209d86449ad703a7ff5e1349ebaf1aa12ece8d82163ee5b61R24-R49) , we need to set `torch.compile()` backend to `eager` to disable compile, using default pytorch way.
...
...
> [Bugfix] Disable torch.compile()

- .github/workflows/vllm_ascend_test.yaml
- pytest.ini
> [CI] fix vllm test

- docs/source/user_guide/supported_models.md
Update model support doc (add QwQ-32B)
> [Doc] Update model support doc (add QwQ-32B)

- vllm_ascend/models/qwen2_vl.py
We proposed the FastPatch method, which optimized patch embedding (Conv3D) for Qwen2VL.
No.
We've tested it on benchmark, it meets our satisfaction and is better than original patch_embed layer.
> FastPatch: Optimized Patch Embedding for Qwen2VL

- README.md
- README.zh.md
Add vLLM Ascend Weekly meeting link
No
Preview
> Add vLLM Ascend Weekly meeting link

- .github/workflows/vllm_ascend_test.yaml
- README.md
- README.zh.md
- docs/source/developer_guide/versioning_policy.md
- docs/source/installation.md
- pta_install.sh
- vllm_ascend/attention/attention.py
> [Doc][Attn] upgrade torch-npu to 0320

- docs/source/user_guide/suppoted_features.md
- vllm_ascend/attention/attention.py
- vllm_ascend/worker/multi_step_runner.py
1. remove useluss code in attention.py
2. multistep now using StatefulModelInputForNPU and do not use StatefulModelInput
> fix multistep bug,remove uselesscodes

- vllm_ascend/platform.py
Fix bug in platform.py to avoid the None value of config parameters.
> [Bug Fix] Fix bug of platform for parameter checking

- vllm_ascend/worker/model_runner.py
Fix the bug in Prefix-Cache feature.
No.
The bug no longer reproduces after this fix.
> [Bugfix] Fix Prefix-Cache bug

- .github/workflows/vllm_ascend_test_main.yaml
- collect_env.py
- tests/ops/test_fused_moe.py
- tests/test_offline_inference.py
- vllm_ascend/platform.py
- vllm_ascend/worker/model_runner_v1.py
- vllm_ascend/worker/worker_v1.py
1. Make sure the version is string before parse in collect_env
2. Add basic V1 engine test
> [Core] Make V1 work and enable V1 engine test

- docs/source/developer_guide/versioning_policy.md
- docs/source/faqs.md
- docs/source/installation.md
- docs/source/user_guide/release_notes.md
Add 0.7.3rc2 release note. We'll release 0.7.3rc2 right now.
> [Doc] Add 0.7.3rc2 release note

- docs/source/developer_guide/versioning_policy.md
- docs/source/faqs.md
- docs/source/user_guide/release_notes.md
- docs/source/user_guide/suppoted_features.md
> [Doc] Add 0.7.3rc2 release note (#419)

- .github/workflows/vllm_ascend_test_main.yaml
Use CI pool instead of self-host for e2e test to speed up CI.
> [CI] Use CI pool

- docs/source/developer_guide/evaluation/index.md
- docs/source/developer_guide/evaluation/using_opencompass.md
- docs/source/index.md
Add developer guide for using OpenCompass
no
no
> [Doc]Add developer guide for using OpenCompass

- docs/source/developer_guide/evaluation/index.md
- docs/source/developer_guide/evaluation/using_opencompass.md
- docs/source/index.md
Backport #368
Add developer guide for using OpenCompass
no
test manually
> [v0.7.3][Doc]Add developer guide for using OpenCompass (#368)

- docs/source/conf.py
> [Doc] update version to 0.7.3rc2

- docs/source/user_guide/release_notes.md
- docs/source/user_guide/suppoted_features.md
Update feature support matrix， Auto Prefix Cache rely on CANN 8.1 NNAL package release， updated it
> [Doc]Update feature support matrix

- docs/source/developer_guide/evaluation/index.md
- docs/source/developer_guide/evaluation/using_lm_eval.md
Add developer guide for using lm-eval
no
test manually
> [Doc]Add developer guide for using lm-eval

- docs/source/developer_guide/evaluation/index.md
- docs/source/developer_guide/evaluation/using_lm_eval.md
Backport: https://github.com/vllm-project/vllm-ascend/pull/456
Add developer guide for using lm-eval
test manually
> [v0.7.3][Doc]Add developer guide for using lm-eval (#456)

- vllm_ascend/worker/model_runner_v1.py
Pre-construct a mask matrix to improve the efficiency of attention mask construction during inference.
Note that the length of the matrix needs to be carefully balanced: a matrix that is too large will consume excessive VRAM, while a matrix that is too small will require dynamic concatenation during inference, leading to performance degradation.
Therefore, an environment variable is added here to dynamically set the size of the pre-constructed mask matrix based on requirements.
> [ModelRunner][V1] Optimize V1 attention mask

- vllm_ascend/models/__init__.py
- vllm_ascend/models/deepseek_v2.py
- vllm_ascend/quantization/quant_config.py
- support deepseek quant
- add w8a8_dynamic quant
see #391
> [deepseek][bugfix] support deepseek quant

- vllm_ascend/platform.py
Add `supports_structured_output()` method to Platform, find more details at https://github.com/vllm-project/vllm/pull/16148.
> [V1][Platform] Add `supports_structured_output()` method to Platform

- vllm_ascend/models/deepseek_v2.py
- vllm_ascend/quantization/quant_config.py
> [quant][bugfix] fix deepseek quant bug

- requirements-dev.txt
- tests/spec_decode/e2e/conftest.py
- tests/spec_decode/e2e/test_compatibility.py
- tests/spec_decode/e2e/test_integration.py
- tests/spec_decode/e2e/test_integration_dist_tp2.py
- tests/spec_decode/e2e/test_integration_dist_tp4.py
- tests/spec_decode/e2e/test_logprobs.py
- tests/spec_decode/e2e/test_medusa_correctness.py
- tests/spec_decode/e2e/test_mlp_correctness.py
- tests/spec_decode/e2e/test_ngram_correctness.py
- tests/spec_decode/e2e/test_seed.py
- tests/test_offline_inference.py
- tests/utils.py
Added e2e test UT with spec_decode feature, Remaining issues: 
1. Case of graph mode; when vllm-ascend supports;
2. Case of preemption scenario; when bugfix;
3. Case related to quantization; when vllm-ascend supports;
5. test_multistep_correctness.py; when bugfix in Both chunked prefill and spec decode are enabled;
6. test_mtp_correctness.py; when bf16 weights ready;
7. test_eagle_correctness.py; when enable get Meta/llama weights by modelscope;
None
tested by CI
> [2/N][CI/UT] enable spec_decode UT

- vllm_ascend/worker/worker_v1.py
Fix wrong import in V1 worker.
> [Bugfix][V1] Fix wrong import in V1 worker

- docs/source/faqs.md
> [Doc] Update FAQ doc

- tests/conftest.py
- vllm_ascend/platform.py
- vllm_ascend/quantization/quant_config.py
- vllm_ascend/utils.py
- vllm_ascend/worker/model_runner.py
- vllm_ascend/worker/model_runner_v1.py
- vllm_ascend/worker/multi_step_runner.py
- vllm_ascend/worker/worker.py
- vllm_ascend/worker/worker_v1.py
logger in vllm-ascend doesn't work. This PR fix the issue.
Fix: https://github.com/vllm-project/vllm-ascend/issues/431
> [MISC] fix logger

- vllm_ascend/worker/model_runner_v1.py
- vllm_ascend/worker/worker_v1.py
Clean up V1 code:
1. remove useless code.
2. format code to be clear.
> [V1] clean up V1 code

- docs/source/developer_guide/versioning_policy.md
> [Doc] Update release date

- docs/source/index.md
- docs/source/user_guide/env_vars.md
- vllm_ascend/envs.py
Add environment variables doc.
> [Doc] Add environment variables doc

- .github/workflows/vllm_ascend_test.yaml
make linux-npu-4 runner run parallel for now
> [CI]Fix workflow

- tests/test_scheduler.py
- vllm_ascend/attention/attention.py
- vllm_ascend/attention/attention_v1.py
- vllm_ascend/core/schedule_config.py
- vllm_ascend/core/scheduler.py
- vllm_ascend/core/v1_engine_core_init.py
- vllm_ascend/platform.py
- vllm_ascend/worker/model_runner_v1.py
- vllm_ascend/worker/worker_v1.py
This PR adds ascend scheduler into v1 engine to support prefill-first schedule with v1 engine.
> [V1] Add v0 style schedule into v1 engine.

- .github/workflows/vllm_ascend_test.yaml
> [CI] update 0.8.3 to 0.8.4

- docs/source/faqs.md
- pyproject.toml
- requirements.txt
- vllm_ascend/patch/platform/__init__.py
- vllm_ascend/patch/platform/patch_0_8_4/__init__.py
- vllm_ascend/patch/platform/patch_common/__init__.py
- vllm_ascend/patch/platform/patch_main/__init__.py
- vllm_ascend/patch/worker/__init__.py
- vllm_ascend/patch/worker/patch_0_8_4/__init__.py
- vllm_ascend/patch/worker/patch_common/__init__.py
- vllm_ascend/patch/worker/patch_main/__init__.py
- vllm_ascend/utils.py
- vllm_ascend/worker/worker.py
- vllm_ascend/worker/worker_v1.py
This PR added patch module for vllm
1. platform patch: the patch will be registered when load the platform
2. worker patch: the patch will be registered when worker is started.
The detail is:
1. patch_common: patch for main and 0.8.4 version
4. patch_main: patch for main verison
5. patch_0_8_4: patch for 0.8.4 version
> [MISC] Add patch module

- docs/source/faqs.md
> [Doc] update faq about w8a8

- .github/workflows/vllm_ascend_test.yaml
- add `HF_TOKEN` as global var to the runner
- add `HF_ENDPOINT` as global var to the runner
- change concurrency group, rely on current pr num
> [CI]Add global env to runner

- vllm_ascend/models/deepseek_v2.py
Fix api in DeepSeekV2, aligning with the latest code of the main branch in vllm.
N/A
Test locally with deepseek-v2-lite, and will add CI by @Potabk.
Plz update the model UT after this pr is merged, thx! cc @Potabk
> [Bugfix][Model] Fix api in DeepSeek model

- docs/source/faqs.md
update performance and accuracy faq
> [Doc]Update faq

- docs/source/user_guide/supported_models.md
Update model support list
cc @Yikun plz help review, thanks!
> [Model][Doc] Update model support list

- tests/singlecard/test_scheduler.py
- vllm_ascend/core/schedule_config.py
- vllm_ascend/core/scheduler.py
This PR Fixes scheduler problems in last PR:
1. change position of DT test to validate it.
2. fix format of copyright.
> [BugFix] Fix scheduler problems in last PR.

- .github/workflows/mypy.yaml
- .github/workflows/vllm_ascend_test.yaml
- vllm_ascend/attention/attention.py
- vllm_ascend/patch/platform/__init__.py
- vllm_ascend/patch/worker/__init__.py
- vllm_ascend/utils.py
- vllm_ascend/worker/model_runner.py
- vllm_ascend/worker/worker.py
- vllm_ascend/worker/worker_v1.py
1. Add `vllm_version_is` function to check vllm version.
2. `ensure_kv_transfer_initialized` and `get_kv_transfer_group ` have been moved to other place in vllm main branch via https://github.com/vllm-project/vllm/commit/3408e471597e7a36ca79fab5fc849f4fb5576df8 , this patch fix the import error.
> [Misc] Fix import error and address nits to make CI happy

- README.md
- docs/source/conf.py
- docs/source/developer_guide/versioning_policy.md
- docs/source/faqs.md
- docs/source/user_guide/release_notes.md
Add release note for 0.8.4rc1, we'll release 0.8.4rc1 now.
> [Doc] Add release note for 0.8.4rc1

- docs/source/faqs.md
- docs/source/installation.md
Update build doc and faq about deepseek w8a8
> [Doc][Build] Update build doc and faq

- vllm_ascend/device_allocator/camem.py
Found a problem when ImportError raised but not ModuleNotFoundError.
No
With UT tested.
> catch ImportError when C code not compiled

- docs/source/installation.md
- tests/singlecard/test_offline_inference.py
- vllm_ascend/quantization/func_wrapper.py
- vllm_ascend/quantization/quant_config.py
- vllm_ascend/quantization/quantizer.py
- vllm_ascend/quantization/w8a8.py
- vllm_ascend/quantization/w8a8_dynamic.py
Add a `VLLMAscendQuantizer` to support w8a8 static (W8A8) and dynamic on linear and moe (W8A8_DYNAMIC), the quantizer will be enable if a model has [quantize filed](https://huggingface.co/vllm-ascend/Qwen2.5-0.5B-Instruct-w8a8/blob/main/config.json#L27). If MindIE Turbo is installed, the MindIE Turbo Quantizer will apply, otherwise will use VLLMAscendQuantizer directly.
- This patch fix installation docs to make installation work
- This patch enable norm quantization by patch `RMSNorm.__init__`, `RMSNorm.forward_oot`, `NPUModelRunnerBase.load_model`
- Add `AscendW8A8LinearMethod` for W8A8
- Add `AscendW8A8DynamicLinearMethod` and `AscendW8A8DynamicFusedMoEMethod` for W8A8_DYNAMIC
- Add a e2e test for `vllm-ascend/Qwen2.5-0.5B-Instruct-w8a8` 
Yes, support w8a8 quantization. After this …
> [quantization] Support w8a8 quantization

- vllm_ascend/attention/attention_v1.py
- vllm_ascend/platform.py
- vllm_ascend/worker/model_runner_v1.py
Support the feature of prefix cache in v1.
No.
Comprehensive unit tests for ops accuracy have been performed and will be included in another PR.
> [0.7.3][V1] Support the feature of prefix cache in v1

- vllm_ascend/patch/platform/patch_0_8_4/__init__.py
add doc for patch_config
No
No code changed.
> add doc for patch_config

- .github/workflows/vllm_ascend_test.yaml
Add new runner to  ref v0.7.3-dev
> [CI] switch to new CI runner

- vllm_ascend/models/deepseek_v2.py
- vllm_ascend/ops/fused_moe.py
- vllm_ascend/ops/rotary_embedding.py
- vllm_ascend/patch/platform/patch_0_8_4/patch_distributed.py
- vllm_ascend/patch/platform/patch_main/patch_distributed.py
- vllm_ascend/worker/model_runner_v1.py
Add notes for deepseek's patch and remove some of the unnecessary comments
> Add note for deepseek related docs and remove unnecessary comments

- docs/source/installation.md
fix doc to mention env setting for v0.7.3-dev
No
No code changed.
> fix doc to mention env setting for v0.7.3-dev

- requirements-dev.txt
- tests/singlecard/test_guided_decoding.py
After extensive testing, we are happy to say that guided_decoding is fully supported  by npu, in this pr, we add guided_decoding  integrated with our test, mainly does the following things:
1. test v0 supported backends including ` "outlines", "lm-format-enforcer","xgrammar"`
2. test v1 supported backends including ` "guidance", "xgrammar"`
> [CI]Add guided decoding test

- vllm_ascend/patch/__init__.py
- vllm_ascend/patch/worker/patch_0_8_4/__init__.py
- vllm_ascend/patch/worker/patch_0_8_4/patch_metrics.py
- vllm_ascend/patch/worker/patch_common/patch_metrics.py
Remove some parts of metrics patch, since the `cuda` hard code has been fixed by https://github.com/vllm-project/vllm/pull/14411.
> [Misc] Remove some parts of metrics patch

- vllm_ascend/worker/model_runner.py
Fix qwen2.5-vl positon input bug, fix #625  `TypeError: 'NoneType' object is not iterable`
> [Bugfix] Fix qwen2.5-vl positon input bug

- tests/conftest.py
- tests/model_utils.py
- tests/singlecard/test_offline_inference.py
Part of #499 
Add qwen2.5-vl test on single npu, v1 engine is excluded because qwen2.5-vl has some problems with v1 now,  at the same time,  this test can also make #639  more credible
> [CI] Add qwen2.5-vl test

- vllm_ascend/worker/draft_model_runner.py
- vllm_ascend/worker/model_runner.py
- vllm_ascend/worker/model_runner_v1.py
https://github.com/vllm-project/vllm/commit/b411418ff090a168c85eab243b14b7350bf73db4 this vllm commit change the sample usage. This PR adapt the change for main and make sure it works for 0.8.4 as well.
> [CI] Fix sample backward compatibility problem

- vllm_ascend/worker/model_runner_v1.py
vLLM Ascend side followup on:
[Core] Remove prompt string from engine core data structures
https://github.com/vllm-project/vllm/commit/df6f3ce883bbfb1884b040f178496a3da33209b9
No
CI passed
> Remove prompt string from engine core data structures

- setup.py
- vllm_ascend/envs.py
Sometimes SOC can not be correctly detected by npu-smi, it is better to use env, which can be set by users.
No
Tested by installing, compiling and UT.
> [0.7.3] Use env for soc during compilation

- vllm_ascend/patch/__init__.py
- vllm_ascend/patch/worker/patch_0_8_4/__init__.py
- vllm_ascend/patch/worker/patch_0_8_4/patch_tritonplaceholder.py
- vllm_ascend/patch/worker/patch_common/patch_minicpm.py
This pr support minicpm in branch main. see https://github.com/vllm-project/vllm-ascend/pull/164
test locally with minicpm
> [Model][MiniCPM] support MiniCPM

- vllm_ascend/attention/attention.py
Eliminated duplicate `block_table` tensor initialization and cleaned up unused code segments. This resolves an issue where the second creation was overwriting the first, potentially leading to unexpected behavior.
No
> [Bugfix] Remove redundant tensor creation and unused code

- docs/source/installation.md
Fix pip install cmd in installation.md
Followup on: https://github.com/vllm-project/vllm-ascend/pull/661
No, doc only
Preview
> [FOLLOWUP][DOC] Fix pip install cmd in installation.md

- vllm_ascend/attention/attention.py
`reshape_and_cache_siso` seems have some funcitonality issues, use torch op combination replace this custom op by default.
> [Fix] fix deepseek v0 attention eager mode

- .github/workflows/image_openeuler.yml
- Dockerfile.openEuler
Update openEuler dockerfile for COMPILE_CUSTOM_KERNELS=1
None
> Update openEuler dockerfile for COMPILE_CUSTOM_KERNELS=1

- docs/source/tutorials/index.md
- docs/source/tutorials/multi_npu_quantization.md
- docs/source/tutorials/w8a8_quantization.md
Add deepsee-v2-lite w8a8 quantization turorial
> [Doc] Add deepsee-v2-lite w8a8 quantization turorial

- docs/source/faqs.md
> [Doc] Update faqs

- benchmarks/README.md
- benchmarks/requirements-bench.txt
- benchmarks/scripts/run-performance-benchmarks.sh
- benchmarks/tests/latency-tests.json
- benchmarks/tests/serving-tests.json
- benchmarks/tests/throughput-tests.json
Cherry-pick benchmark script from main
> [Misc] Add v0.7.3 benchmark

- docs/source/faqs.md
Update v0.7.3 faqs, cherry-pick from main
> [Doc] Update v0.7.3 faqs

- docs/source/conf.py
- docs/source/developer_guide/versioning_policy.md
- docs/source/faqs.md
- docs/source/user_guide/release_notes.md
> [Doc] Add 0.8.4rc2 release note

- csrc/kernels/pos_encoding_kernels.cpp
- docs/source/faqs.md
- docs/source/installation.md
- examples/disaggregated_prefill_hccl.py
- examples/offline_inference_audio_language.py
- format.sh
- tests/singlecard/spec_decode/e2e/test_medusa_correctness.py
- tests/singlecard/spec_decode/e2e/test_mlp_correctness.py
- tests/singlecard/spec_decode/e2e/test_ngram_correctness.py
- tools/actionlint.sh
- tools/mypy.sh
- vllm_ascend/attention/attention.py
- vllm_ascend/core/schedule_config.py
- vllm_ascend/distributed/llmdatadist_connector.py
- vllm_ascend/distributed/parallel_state.py
- vllm_ascend/ops/fused_moe.py
- vllm_ascend/ops/rotary_embedding.py
This pr makes format.sh works as expect.
> [MISC] fix format check error

- tests/singlecard/test_offline_inference.py
Add Qwen3-0.6B-Base for integration test
> [CI] Add Qwen3-0.6B-Base test

- .github/workflows/vllm_ascend_test.yaml
Add nightly CI  for basic function and model usability
> [CI] Add nightly CI

- vllm_ascend/models/deepseek_v2.py
> [Bugfix] Fix early return in CustomDeepseekV2MoE.forward during profile_run

- vllm_ascend/quantization/quant_config.py
In order to support quantization model generated by new modelslim version, we need to add quant_description in `AscendQuantConfig`. cherry-pick this PR from https://github.com/vllm-project/vllm-ascend/pull/719
> new modelslim quantization model  support v0.7.3

- .github/workflows/vllm_ascend_test.yaml
- Dockerfile
- Dockerfile.openEuler
- README.md
- README.zh.md
- docs/source/conf.py
- docs/source/installation.md
- docs/source/quick_start.md
Backport: https://github.com/vllm-project/vllm-ascend/pull/747
Upgrade CANN version to 8.1.rc1
no
CI passed
Co-authored-by: MengqingCao <cmq0113@163.com>
> [v0.7.3] Upgrade CANN version to 8.1.rc1

- .github/workflows/vllm_ascend_test.yaml
- Dockerfile
- Dockerfile.openEuler
Bump vllm version to v0.8.5.post1
No
CI passed
> [Build] Bump vLLM version to v0.8.5.post1

- vllm_ascend/attention/attention.py
Fix function name typo, make `mask_fill_` to `masked_fill_`
No
> [Bugfix] Fix masked_fill_ function typo

- docs/source/faqs.md
add notes for OOM in faqs.
No
CI passed
> [v0.7.3][Doc] Add notes for OOM in FAQs (#786)

- vllm_ascend/attention/attention.py
- vllm_ascend/attention/attention_v1.py
- vllm_ascend/attention/mla_v1.py
- vllm_ascend/platform.py
- vllm_ascend/worker/model_runner.py
- vllm_ascend/worker/model_runner_v1.py
Support the features of prefix cache and chunked prefill in v0/v1.
> [Core] Support the features of prefix cache and chunked prefill in v0/v1

- benchmarks/README.md
- benchmarks/tests/latency-tests.json
- benchmarks/tests/serving-tests.json
- benchmarks/tests/throughput-tests.json
- Add qwen2.5-7b test
- Optimize the documentation to be more developer-friendly
> [Benchmarks] Add qwen2.5-7b test

- .github/workflows/accuracy_report.yaml
- .github/workflows/accuracy_test.yaml
1.  update cann version to 8.1.0 for multimodal
2.  fix huggingface-hub version to adapt to qwen3
3.  change Qwen3-8B to Qwen-8B-Base,
> [Bugfix] Update cann version and huggingface-hub version for Qwen3

- vllm_ascend/attention/mla_v1.py
- vllm_ascend/core/scheduler.py
- vllm_ascend/models/deepseek_v2.py
- vllm_ascend/platform.py
- vllm_ascend/worker/model_runner_v1.py
support torchair graph mode with v1 engine
> feat: support torchair graph mode in v1 engine

- vllm_ascend/attention/attention_v1.py
- vllm_ascend/platform.py
- vllm_ascend/utils.py
- vllm_ascend/worker/model_runner_v1.py
Add padding for ACL Graph and refactor graph batch size adjustments to utils.py
> [Enhancement] Add padding for ACL Graph

- vllm_ascend/models/qwen2_5_vl.py
The [vllm commit](https://github.com/vllm-project/vllm/commit/67da5720d4ed2aa1f615ec812031f4f3753b3f62) changed the input and rotary position embedding for qwen 2.5 vl which break CI. This PR fix the CI failure for qwen2.5 vl in quick
> [CI] Fix qwen2.5 vl CI failure

- docs/source/tutorials/multi_npu_quantization.md
1. replace deepseek-v2-lite model with more pratical model QwQ 32B
2. fix some incorrect commands
3. replase modelslim version with a more formal tag
> [Doc] update quantization docs with QwQ-32B-W8A8 example

- docs/source/tutorials/multi_npu_quantization.md
1. update modelslim version to fix deepseek related issues
2. add note for "--quantization ascend"
> [DOC] update modelslim version

- docs/source/user_guide/supported_models.md
Support XLM-RoBERTa-based and MiniCPM3 model for v0.7.3
> [Doc][v0.7.3] Support XLM-RoBERTa-based and MiniCPM3 model

- vllm_ascend/ops/attention.py
- vllm_ascend/quantization/w8a8.py
Set div_mode to False to use the ACLNN kernel, which is crucial when using ACL Graph.
> [Fix] Set div_mode to False and fix view_as position

- vllm_ascend/patch/patch_transformers_utils.py
Update transformer utils patch for `v0.7.3`.
This PR is a supplement to https://github.com/vllm-project/vllm-ascend/pull/858, adding more patch methods adapted from https://github.com/vllm-project/vllm/pull/17948 to solve `revision` problems in more scenarios besides https://github.com/vllm-project/vllm-ascend/issues/829.
no.
```bash
vllm serve Qwen/Qwen2.5-VL-7B-Instruct \
--dtype bfloat16 \
--max_model_len 32768 \
--max-num-batched-tokens 32768
```
> [Bugfix][0.7.3] Update transformer utils patch

- vllm_ascend/attention/attention_v1.py
- vllm_ascend/attention/mla_v1.py
- vllm_ascend/worker/model_runner_v1.py
Revert multiple kv cache groups related changes as this feature is reverted in vllm https://github.com/vllm-project/vllm/pull/18459
> [Bugfix][kvcache] revert multiple kv cache groups

- docs/source/user_guide/suppoted_features.md
Update feature support for lora
no
preview
> [DOC] mark v1 multi-lora functional

- docs/source/installation.md
Add `COMPILE_CUSTOM_KERNELS =1` note for sleep mode
> [Doc][0.7.3] Improve sleep documentation

- docs/source/tutorials/multi_npu_quantization.md
add example for offline inference with quantized model
> add doc for offline quantization inference

- README.md
- docs/source/_templates/sections/header.html
- docs/source/developer_guide/versioning_policy.md
- docs/source/faqs.md
- docs/source/user_guide/release_notes.md
Add release note for 0.7.3.post1
Add the missing release note back for 0.7.3
> [doc] add 0.7.3.post1 release note

- docs/source/conf.py
- docs/source/developer_guide/versioning_policy.md
- docs/source/faqs.md
- docs/source/user_guide/release_notes.md
cherry-pick 0.7.3.post1 release note from main
> [Doc][0.7.3] Add release note for 0.7.3.post1

- .github/workflows/nightly_benchmark.yaml
- .github/workflows/nightly_benchmarks.yaml
- benchmarks/scripts/run-performance-benchmarks.sh
- benchmarks/tests/latency-tests.json
- benchmarks/tests/serving-tests.json
- benchmarks/tests/throughput-tests.json
Add benchmark workflows
No
Run locally
> [CI] Add benchmark workflows

- .github/workflows/vllm_ascend_test.yaml
Skip benchmarks/** in vllm ascend test to reduce CI cost
No
CI passed
> Skip benchmarks/** in vllm ascend test

- docs/source/community/contributors.md
- docs/source/community/governance.md
- docs/source/index.md
Add vLLM Ascend project governance and first contributors docs
No
Preview
Closes: https://github.com/vllm-project/vllm-ascend/issues/828
Closes: https://github.com/vllm-project/vllm-ascend/issues/929
> Add vLLM Ascend project governance docs

- .github/workflows/nightly_benchmarks.yaml
Fix benchmark results path
No
CI passed
> [CI] Hotfix on benchmark results path

- docs/source/index.md
- docs/source/user_guide/graph_mode.md
Add graph mode user guide doc.
> [Doc] Add graph mode user doc

- tests/multicard/test_offline_inference_distributed.py
- tests/singlecard/test_offline_inference.py
- vllm_ascend/envs.py
- vllm_ascend/patch/worker/patch_common/patch_sampler.py
typo of VLLM_ASCEND_ENABLE_TOPK_OPTIMIZE
No
CI passed
> Fix typo of VLLM_ASCEND_ENABLE_TOPK_OPTIMIZE

- tests/e2e/common.sh
- tests/e2e/pd_disaggreate/setup_pd.sh
- tests/e2e/run_disagg_pd.sh
> [CI] Fix PD job

- docs/source/conf.py
- docs/source/developer_guide/versioning_policy.md
- docs/source/faqs.md
- docs/source/user_guide/release_notes.md
Add the release note for v0.9.0rc1
> [Doc] Add 0.9.0rc1 release note

- docs/source/community/contributors.md
Update 0.9.0rc1 contributors info
No
CI passed
> Update 0.9.0rc1 contributors info

- tests/singlecard/test_offline_inference.py
1. rename vllm-ascend/Qwen2.5-0.5B-Instruct-W8A8-new to vllm-ascend/Qwen2.5-0.5B-Instruct-W8A8
> [CI] rename Qwen2.5-0.5B-Instruct-W8A8 model

- docs/source/user_guide/graph_mode.md
Fix the doc typo in graph_mode.md
> [Doc] Fix the config parameter name "enable" in graph_mode.md.

- docs/source/installation.md
fix the CANN download url
no, do not have any user-facing change
run the **wget** command and cann package is rightly downloaded.
> [Doc] Add Referer header for CANN package download url.

- .github/workflows/nightly_benchmarks.yaml
- vllm_ascend/device_allocator/camem.py
- For npu environment, we should use  `PYTORCH_NPU_ALLOC_CONF ` rather than  `PYTORCH_CUDA_ALLOC_CONF`
- Add `PIP_EXTRA_INDEX_URL` to make nightly_benchmarks happy
> [Bugfix] Remove cuda related lines and add additional pip mirror

- vllm_ascend/ops/rotary_embedding.py
> [Bugfix] fix rope sin/cos cache bug

- vllm_ascend/ops/fused_moe.py
> [v0.9.1][bugfix] fix deepseek with mc2

- vllm_ascend/ops/fused_moe.py
> [bugfix] fix deepseek with mc2

- vllm_ascend/attention/attention_v1.py
- vllm_ascend/attention/mla_v1.py
- vllm_ascend/models/deepseek_dbo.py
- vllm_ascend/multistream/ms_split.py
- vllm_ascend/worker/model_runner_v1.py
- vllm_ascend/worker/worker_v1.py
Fix running error in dbo when dp_size>1. Add conditional logic in `_get_forward_metadata_across_dp` to enable dbo. 
None
add test case  `test/e2e/multicard/test_data_parallel.py` at main branch after pr1277 merged
test dp2 inference in dbo model
> [0.9.1][Bugfix] fix dp error in dbo

- vllm_ascend/worker/model_runner_v1.py
Fix the token-wise padding mechanism.
> [Fix] Fix the token-wise padding mechanism

- .github/doc_codespell.yaml
- docs/source/user_guide/quantization.md
Add codespell check test for doc only PR
> [CI] Add codespell check for doc

- README.md
- README.zh.md
- docs/source/installation.md
- requirements.txt
This PR update the torch-npu to dev20250619 on the 0.9.1-dev branch.
No
> update torch_npu in vllm-ascend to dev20250619

- .github/workflows/nightly_benchmarks.yaml
- docs/source/conf.py
- docs/source/developer_guide/versioning_policy.md
- docs/source/faqs.md
- docs/source/tutorials/index.md
- docs/source/tutorials/multi_npu_moge.md
- docs/source/tutorials/single_node_300i.md
- docs/source/user_guide/graph_mode.md
- docs/source/user_guide/release_notes.md
Bump v0.9.1rc1 release
Closes: https://github.com/vllm-project/vllm-ascend/pull/1341
Closes: https://github.com/vllm-project/vllm-ascend/pull/1334
No
CI passed
Co-authored-by: wangxiyuan <wangxiyuan1007@gmail.com>
Co-authored-by: leo-pony <nengjunma@outlook.com>
Co-authored-by: shen-shanshan <467638484@qq.com>
> Bump v0.9.1rc1 release

- docs/source/faqs.md
Change not to no in faqs.md.
No.
Local Test
> [Doc] Change not to no in faqs.md

- README.md
- README.zh.md
- docs/source/installation.md
- requirements.txt
This PR update the torch_npu to newest release version 2.5.1.post1.dev20250619 .
No
CI tested will guarantee the update
> update torch-npu to 2.5.1.post1.dev20250619

- .github/workflows/vllm_ascend_test_pd.yaml
- tests/e2e/pd_disaggreate/setup_pd.sh
Use eager mode to run disaggregated prefill ci
N/A
CI passed with new existing test.
> [CI/UT] Fix disaggregated prefill ci

- vllm_ascend/worker/model_runner_v1.py
Remove the duplicated code introduced by my inadvertent rebase. I apologize for this oversight.
> [Refactor] Remove duplicate multimodal codes in ModelRunner

- .github/workflows/accuracy_test.yaml
- benchmarks/scripts/run_accuracy.py
fix accuracy test:
1. fix accuracy report like:https://vllm-ascend--1429.org.readthedocs.build/en/1429/developer_guide/evaluation/accuracy_report/Qwen2.5-7B-Instruct-V0.html
2. fix create pr for report
> [FOLLOWUP] fix name and format in accuracy test (#1288)

- vllm_ascend/attention/mla_v1.py
This PR fixes a bug of running chunked-prefill with torchair.
> [BugFix] Fix a bug of running chunked-prefill with torchair.

- docs/source/tutorials/index.md
- docs/source/tutorials/single_npu_audio.md
- docs/source/tutorials/single_npu_audio_eager_mode.md
- examples/offline_inference_audio_language.py
Add qwen2-audio eager mode tutorial.
> [Doc] Add qwen2-audio eager mode tutorial

- docs/source/developer_guide/feature_guide/patch.md
Fix some terms in the user guide.
No
Following instructions in [here](https://github.com/vllm-project/vllm-ascend/blob/main/docs/README.md), build and test locally.
> Optimize Patch developer guide

- .github/ISSUE_TEMPLATE/900-release-checklist.yml
Add the release checklist issue template.
Every release manager should create and follow the checklist to do the release step by step.
> [Misc] Add release checklist issue template

- docs/source/developer_guide/modeling/adding_a_new_model.md
- docs/source/developer_guide/modeling/adding_a_new_multimodal_model.md
- docs/source/developer_guide/modeling/index.md
- docs/source/developer_guide/modeling/using_quantized_model_weights.md
- docs/source/index.md
Add guidance on how to implement and register new models.
Modified based on PR https://github.com/vllm-project/vllm-ascend/pull/1126, thanks for the contribution of @linfeng-yuan.
> [Doc] Add guidance on how to implement and register new models

- vllm_ascend/worker/model_runner_v1.py
Support prompt logprobs in V1. This also enable lm_eval to test accuracy on V1
support prompt logprobs output
CI passed with accuracy test.
Using lm_eval, which use prompt logprobs as output to test accuracy, to test:
```python
VLLM_USE_V1=1 lm_eval \
--model vllm \
--model_args pretrained=Qwen/Qwen2.5-7B-Instruct,max_model_len=4096,block_size=4 \
--tasks ceval-valid_computer_network \
--batch_size 8
```
After this pr, the accuracy test results of `Qwen/Qwen2.5-7B-Instruct` on V1 is:
```bash
|           Tasks            |Version|Filter|n-shot| Metric |   |Value |   |Stderr|
|----------------------------|------:|------|-----:|--------|---|-----:|---|-----:|
|ceval-valid_computer_network|      2|none  |     0|acc     |↑  |0.7368|±  |0.1038|
|                            |       |none  | …
```
> [PromptLogprobs][V1] Support prompt logprobs to fix ceval accuracy in V1

- vllm_ascend/patch/platform/patch_common/patch_distributed.py
This PR fixes a bug that use broadcast with cpu_group when running dp. The `broadcast310p` patch will take effects for both cpu_group and device group, but we only need it for device group. Hence a wrapper is added to allow cpu_group use native torch broadcast and it solves the bug. 
No.
With this PR, DP on 310p runs normally and generates reasonable answers.
> [BugFix]Fix bugs when initializing communication groups with dp on 300I Duo

- docs/source/tutorials/single_node_300i.md
Add Pangu MoE Pro for 300I series docs
No
CI passed
> Add Pangu MoE Pro for 300I series docs

- .github/workflows/vllm_ascend_test.yaml
- tests/e2e/multicard/test_fused_moe_allgather_ep.py
- tests/e2e/multicard/test_offline_inference_distributed.py
- tests/e2e/multicard/test_torchair_graph_mode.py
Previous, the DeepSeek V3 Pruning weight is not correct, the moe layer is not tested. We update a new Pruning model to enable moe layer compute. 
This PR fix the CI to address the new weight.
> [CI] change to new ds model

- tests/multicard/test_offline_inference_distributed.py
- tests/multicard/test_torchair_graph_mode.py
Cherry-pick #1513: change to new ds model 
> [CI/UT] Cherry-pick change to new ds model #1513

- vllm_ascend/worker/model_runner_v1.py
Disaggregate prefill force producer dummy run with prefill
> [BugFix] disaggregate prefill force producer dummy run with prefill

- .github/workflows/nightly_benchmarks.yaml
Make sure that None parameters are not passed in for `--error`
No
CI passed locally
> [Benchmark] Fix error msg upload in performance benchmark

- tests/ut/attention/test_attention_v1.py
- tests/ut/quantization/test_quant_config.py
- tests/ut/quantization/test_quantizer.py
- tests/ut/quantization/test_w8a8.py
- vllm_ascend/attention/attention_v1.py
- vllm_ascend/quantization/quantizer.py
- vllm_ascend/quantization/w8a8.py
- vllm_ascend/worker/model_runner_v1.py
1. drop some useless code for w8a8 fusedmoe
2. Add in8 kv cache check
3. Add more ut.
No
> Fix W8A8 fused moe bug

- vllm_ascend/ops/fused_moe.py
- vllm_ascend/quantization/w8a8_dynamic.py
- vllm_ascend/worker/draft_model_runner.py
- vllm_ascend/worker/model_runner.py
- vllm_ascend/worker/pooling_model_runner.py
1. fix v0_model_runner, pooling_model_runner, draft_model_runner are not adapted to `ascend_forward_context`
2. fix moe_distributed_combine's param `global_bs` bug.
> [0.9.1][bugfix] fix ascend_forward_context

- docs/source/user_guide/lora.md
Fix word spelling in DOC.
No.
No.
> [DOC] Fix word spelling

- .github/workflows/accuracy_test.yaml
- .github/workflows/nightly_benchmarks.yaml
- .github/workflows/vllm_ascend_test.yaml
- .github/workflows/vllm_ascend_test_long_term.yaml
- .github/workflows/vllm_ascend_test_pd.yaml
- benchmarks/scripts/run-performance-benchmarks.sh
- examples/offline_embed.py
- tests/conftest.py
- tests/e2e/multicard/test_ilama_lora_tp2.py
- tests/e2e/singlecard/test_ilama_lora.py
Unify Model Usage via ModelScope
No
CI passed
> [CI/UT] Unify model usage via ModelScope in CI

- tests/ut/test_ascend_config.py
- vllm_ascend/ascend_config.py
- vllm_ascend/attention/attention_v1_torchair.py
- vllm_ascend/ops/fused_moe.py
This commit https://github.com/vllm-project/vllm/commit/78fe77534bd87f5356881f12d2a4ecbd8db29c41 from vllm reverted the change for FusedMoEParallelConfig
This PR do the same to fix the CI error
> [CI] Follow vLLM FusedMoEParallelConfig interface change and clean up unused config

- .github/workflows/accuracy_test.yaml
- benchmarks/scripts/run_accuracy.py
- examples/offline_embed.py
Update accuracy test
1. remove accuarcy report on V0
2. add parallel and execution mode
3. add Qwen/Qwen3-30B-A3B and remove Qwen/Qwen2.5-7B-Instruct
> [Test] Remove V0 accuracy test and enable MoE and VL test on V1

- .github/workflows/vllm_ascend_test.yaml
- tests/e2e/singlecard/core/ascend_scheduler/test_ascend_scheduler_e2e.py
- tests/e2e/singlecard/core/ascend_scheduler/test_chunk_prefill.py
Add the resource clear logic to fix oom issue when testing `tests/e2e/singlecard/core/ascend_scheduler`.
N/A
> [CI] Fix oom in chunk prefill

- examples/eplb/eplb_deepseek.py
- examples/eplb/eplb_strategy.py
- requirements.txt
This PR implements the DeepSeek Expert Parallel Load Balancing (EPLB) strategy to optimize expert distribution in vllm-ascend. The implementation:
- Adapts the expert-map format to work with vllm-ascend's architecture
- Provides DeepSeek-provided mechanism to balance expert workload across devices
This PR adds a new script that allows users to:
- Generate expert map configurations based on workload analysis
- Optimize expert distribution for their specific use case
To use this feature:
1. First collect expert heat information during model execution
2. Run the provided script to generate the expert map configuration
3. Apply the generated configuration to your vllm-ascend deployment
User example:
```bash
python3 examples/eplb/eplb_strategy.py --exp_name 'deepseek_demo' \
--input_path …
```
> [EPLB] support deepseek eplb strategy

- vllm_ascend/worker/eagle_proposer_v1.py
- vllm_ascend/worker/model_runner_v1.py
Make model_runner_v1 more readable
- vLLM main: https://github.com/vllm-project/vllm/commit/baed180aa00314897b37b4b0af65adeba06f3d77
> [Misc] Code clean up

- docs/source/tutorials/index.md
- docs/source/tutorials/multi_npu_qwen3_moe.md
Signed-off-by: leo-pony <nengjunma@outlook.com>
Add multi-npu qwen3-MoE-32B Tutorials
Relate RFC: https://github.com/vllm-project/vllm-ascend/issues/1248
- vLLM main: https://github.com/vllm-project/vllm/commit/5358cce5ffbd4011f8fea2188995a249b43b8bfe
> [Doc] Add multi-npu qwen3-MoE-32B Tutorials

- vllm_ascend/attention/mla_v1.py
- vllm_ascend/worker/model_runner_v1.py
- vllm_ascend/worker/mtp_proposer_v1.py
[BUGFIX] [v0.9.1] Fix mtp with disaggregated-prefill
> [BUGFIX] [v0.9.1] Fix mtp with disaggregated-prefill

- tests/e2e/multicard/test_offline_inference_distributed.py
- tests/e2e/singlecard/test_offline_inference.py
- tests/e2e/singlecard/test_sampler.py
- tests/ut/patch/worker/patch_common/test_patch_sampler.py
- vllm_ascend/envs.py
- vllm_ascend/patch/__init__.py
- vllm_ascend/patch/worker/patch_common/__init__.py
- vllm_ascend/patch/worker/patch_common/patch_sampler.py
Performance optimization for apply_top_k_top_p
Use VLLM_ASCEND_ENABLE_TOPK_TOPP_OPTIMIZATION to enable this feature
e2e & ut
- vLLM main: https://github.com/vllm-project/vllm/commit/6a9e6b2abf88181f93a1959fe16291c3f1696329
> [Perf] add patch to optimize apply_topk_topp

- README.zh.md
Update README.zh.md to fix typo
No
CI passed
> Update README.zh.md to fix typo

- docs/source/tutorials/multi_node.md
- docs/source/user_guide/feature_guide/lora.md
- docs/source/user_guide/release_notes.md
Fix url 404 error in doc
- vLLM main: https://github.com/vllm-project/vllm/commit/9ad0a4588ba4e9c979cda0d178dec4fcdb89fd0c
> [Doc] Fix 404 error

- docs/source/tutorials/multi_npu_moge.md
Revise pangu docs
yes
CI passed with new existing test.
- vLLM main: https://github.com/vllm-project/vllm/commit/5a7fb3ab9ee4bd8174a5100595326f6f40024cdc
> Add graph mode and improve on multi_npu_moge.md

- vllm_ascend/__init__.py
- vllm_ascend/patch/platform/patch_0_9_1/__init__.py
Fix bug in decorator patch.
No.
> [BugFix] Fix decorator patch

- docs/source/faqs.md
Signed-off-by: wuzhongjian <wuzhongjian_yewu@cmss.chinamobile.com>
Fixes https://github.com/vllm-project/vllm-ascend/issues/1760 issue1
- vLLM main: https://github.com/vllm-project/vllm/commit/b9a21e9173508e38ac693a8781c48ee24c8873ec
> [Doc] Add a doc for qwen omni

- vllm_ascend/__init__.py
- vllm_ascend/patch/platform/patch_0_9_1/__init__.py
- vllm_ascend/patch/platform/patch_0_9_1/patch_decorator.py
Fix the bug in patch_decorator.py when engine v0. Now just enable this patch in engine v1.
No.
> [0.9.1][BugFix] Fix bug in path_decorator when engine v0

- tests/multicard/test_multimodal_context_parallel.py
- vllm_ascend/distributed/context_parallel_utils.py
- vllm_ascend/models/qwen2_5_vl.py
- vllm_ascend/ops/rotary_embedding.py
Enable Qwen2.5-VL vit sp parallel and mrope npu fusion op
No
Test Qwen2.5-VL 7B model accuracy on textVQA with aisbench
The difference in accuracy achieved by Single Card and Mutilcard(4 cards) is within 1%.
> qwen2.5-vl Vit module enable sp and mrope fusion op

- tests/ut/distributed/device_communicators/test_pyhccl.py
- tests/ut/distributed/device_communicators/test_pyhccl_wrapper.py
Add some ut for files in folder /distributed
No
- vLLM main: https://github.com/vllm-project/vllm/commit/107111a85991cbe9c8d16b697e048d91aa4135f6
> [Test] Add ut for files in /distributed

- .github/workflows/image_310p_openeuler.yml
- .github/workflows/image_310p_ubuntu.yml
- .github/workflows/image_a3_openeuler.yml
- .github/workflows/image_a3_ubuntu.yml
- .github/workflows/image_openeuler.yml
- .github/workflows/image_ubuntu.yml
- Fixes image CI
No
- vLLM main: https://github.com/vllm-project/vllm/commit/f3137cdd81cae3a48282c22130fbcadcfc64ea95
> Enable image push CI for build file and csrc has changes

- vllm_ascend/distributed/llmdatadist_c_mgr_connector.py
When you run multiple Ps and Ds on a single machine by using different `ASCEND_RT_VISIBLE_DEVICES`, only 1 P and 1 D work, and other instances fail to link with remote instances.
It should not change existing functions if the `gen_ranktable.sh` provided in the projects is used.
Pass benchmark_serving.py 3000 prompts with Qwen3-8B tp_size=2 3P3D(`ASCEND_RT_VISIBLE_DEVICES` = `0,1`, `2,3`, `4,5`, `8,9`, `10,11`, `12,13`) on A3. 
Pass benchmark_serving.py 3000 prompts with Qwen3-8B tp_size=1/tp_size=2 3P3D(`ASCEND_RT_VISIBLE_DEVICES` = `0`, `2`, `4`, `8,9`, `10,11`, `12,13`) on A3. 
Pass benchmark_serving.py 3000 prompts with Qwen3-8B tp_size=1 3P3D(`ASCEND_RT_VISIBLE_DEVICES` = `0`, `2`, `4`, `8`, `10`, `12`) on A3. 
vllm version: https://github.com/vllm-project/vllm/commit/b6553be1bc75f046b …
> [v0.9.1][Bugfix][PD] Make multiple Ps and Ds work on a single machine

- vllm_ascend/attention/attention_v1.py
- vllm_ascend/attention/attention_v1_torchair.py
- vllm_ascend/device_allocator/camem.py
- vllm_ascend/worker/model_runner_v1.py
Clean up useless  import from vllm to make code more clear.
- vLLM main: https://github.com/vllm-project/vllm/commit/18cc33dd603cce058867f5730919041fa3617eb7
> [Misc]Clean up useless import from vllm

- tests/e2e/doctests/002-pip-binary-installation-test.sh
Pin transformers to fix v0.9.1 doctest
No
doctest passed
- vLLM main: https://github.com/vllm-project/vllm/commit/c6573698414c88990c3ddcd5386d26fb5911c59d
> Pin transformers to fix v0.9.1 doctest

- tests/ut/models/test_qwen2_vl.py
add ut for qwen2_vl.py
no
not involved
- vLLM main: https://github.com/vllm-project/vllm/commit/555e7225bcb9cdf9b037ce064e48987dbc3e13a0
> ut:add ut for qwen2_vl.py

- tests/ut/models/test_qwen2_5_vl.py
add ut for qwen2_5_vl
No
not involved
- vLLM main: https://github.com/vllm-project/vllm/commit/2836dd73f13015ee386c544760ca0d16888203f3
> ut:add ut for qwen2_5_vl

- vllm_ascend/multistream/ms_split.py
- vllm_ascend/worker/model_runner_v1.py
1 . fix rope error because new feature add but doesn't match DBO
2. add interception code on other model which not support DBO
this pr will cherry-pick to main in pr:2111
> [0.9.1dev] Fix rope error when DBO and add interception code

- .github/workflows/accuracy_test.yaml
- .github/workflows/nightly_benchmarks.yaml
- .github/workflows/vllm_ascend_test.yaml
- .github/workflows/vllm_ascend_test_long_term.yaml
- .github/workflows/vllm_ascend_test_pd.yaml
- Dockerfile
- Dockerfile.openEuler
- README.md
- README.zh.md
- docs/source/installation.md
- pyproject.toml
- requirements.txt
Upgrade torch-npu to 2.5.1.post1
This is a v0.9.1 only PR.
No
CI passed
> [v0.9.1] Upgrade torch-npu to 2.5.1.post1

- tests/e2e/singlecard/test_offline_inference_310p.py
Add qwen-vl model and sampling feature UT for  310I series
- vLLM main: https://github.com/vllm-project/vllm/commit/e0f63e4a3509a9323339eee67c96ac3c93d15923
> Add qwen-vl model and sampling feature UT for  310I series

- tests/ut/kv_connector/test_llmdatadist_connector.py
- vllm_ascend/distributed/llmdatadist_c_mgr_connector.py
(cherry picked from commit 816375e0c1071d0696dfab1a1ce35674f9f37aa0)
Suppose that you want to start a prefiller instance with npus `2,3` only. So you start the instance with `ASCEND_RT_VISIBLE_DEVICES=2,3`. The current programming will start two workers, whose ranks are `0` and `1` respectedly. And they will pick the first and second ip addresses of npus in the ranktable instead of the thirdth and forth ones. But actually they are using card `2,3` and therefore they can not link with remote instances when they attempt to transfer the KVCache.
Hence, at most 1 prefiller instance and at most 1 decoder instance can work  on a single machine since they always pick the first npu ip address in the ranktable currently.
This pull request is proposed to fix the problem. This fix pick ips of only …
> [Bugfix][PD] Make multiple Ps and Ds work on a single machine

- tests/ut/sample/test_rejection_sampler.py
add rejection sampler ut.
No
UT passed
- vLLM main: https://github.com/vllm-project/vllm/commit/586f286789a09f5616be74ee8bedde0a9f698a72
> [Test] add rejection sampler ut

- examples/offline_external_launcher.py
- tests/e2e/multicard/test_external_launcher.py
This pr add e2e testcase to make sure sleep mode in external_launcher is ok.
not involved
not involved
- vLLM main: https://github.com/vllm-project/vllm/commit/74333ae2f6c3c4aa4b55301e5ed7aba03a5b09f8
> ut: add example and e2e test for sleepmode in external_launcher

- docs/source/tutorials/index.md
- docs/source/tutorials/single_npu_qwen3_quantization.md
Add a new single npu quantization tutorial, and using the latest qwen3 model.
No
- vLLM main: https://github.com/vllm-project/vllm/commit/8e8e0b6af189d262bcfdaef6c0cfb94772e86b0b
> [Tutorial] Add qwen3 8b w4a8 tutorial

- docs/source/user_guide/support_matrix/supported_models.md
Update user guide for suported models 
- vLLM main: https://github.com/vllm-project/vllm/commit/4be02a37767f05a3fd27d66435d5cebea7a9bfe8
> [Doc] Update user guide for suported models

- .github/workflows/vllm_ascend_test.yaml
- pyproject.toml
- requirements.txt
- tests/e2e/singlecard/spec_decode_v1/test_v1_spec_decode.py
- vllm_ascend/worker/model_runner_v1.py
1. disable test_eagle_ccorrectness test, we'll reopen it once oom error fixed.
2. drop transformers version limit for main, since vLLM rely on >=4.55.0, see: https://github.com/vllm-project/vllm/commit/65552b476b1c475ef433995d2699bb27428693b3
3. fix kv_connector_output bug,  see: https://github.com/vllm-project/vllm/commit/796bae07c59716b7b61d57343826bfbeabdd01bb
- vLLM main: https://github.com/vllm-project/vllm/commit/d1af8b7be9c5ad9d2926ce215771e9cd7279147b
> [CI] Fix broken CI

- docs/source/community/contributors.md
I would like to nominate Mengqing Cao (@MengqingCao https://github.com/MengqingCao) as a maintainer, starting with my +1.
Review Quality‌: She has completed [120+ reviews](https://github.com/vllm-project/vllm-ascend/pulls?q=is%3Apr+is%3Aclosed+commenter%3Amengqingcao+-author%3Amengqingcao) since Feb. 2025, include [#review-3077842852](https://github.com/vllm-project/vllm-ascend/pull/2088#pullrequestreview-3077842852), [comment-2990074116](https://github.com/vllm-project/vllm-ascend/pull/1032#issuecomment-2990074116), [comment-2921063723](https://github.com/vllm-project/vllm-ascend/pull/1013#issuecomment-2921063723) high quality review.
Sustained and Quality Contributions: She has Deep understanding of ‌vLLM‌ and ‌vLLM Ascend‌ codebases and solid contributions include The vLLM …
> Nominate Mengqing Cao as vllm-ascend maintainer

- vllm_ascend/envs.py
Remove the env used for v0 pd feature.
> [misc] remove uesless envs

- vllm_ascend/torchair/torchair_model_runner.py
- vllm_ascend/worker/model_runner_v1.py
- vllm_ascend/worker/mtp_proposer_v1.py
refact model runner v1
1. Separate the execute model logic from the prepare input logic
2. Disassemble the torchchair in model runner v1
- vLLM main: https://github.com/vllm-project/vllm/commit/68fcd3fa7313d00240f766f42affe931f1f379a7
> refact runner model v1

- docs/source/user_guide/release_notes.md
Add release note for `v0.9.1rc3`.
- vLLM main: https://github.com/vllm-project/vllm/commit/53415653ff24be03e7c90f5b42ef9cb3f72aad71
> [Doc] Add release note for `v0.9.1rc3`

- .github/workflows/vllm_ascend_test.yaml
- tests/ut/ops/test_rotary_embedding.py
- tests/ut/test_utils.py
- vllm_ascend/ops/__init__.py
- vllm_ascend/ops/rotary_embedding.py
- vllm_ascend/utils.py
Register RotaryEmbedding instead of overwrite forward
N/A
- vLLM main: https://github.com/vllm-project/vllm/commit/808d2e9aa0f302bf9667b09b9dcf297f86927dac
> [CustomOp] Register RotaryEmbedding instead of overwrite forward

- examples/eplb_generate_map.py
- tests/singlecard/ops/test_fused_moe.py
- vllm_ascend/eplb/adaptor/vllm_adaptor.py
- vllm_ascend/eplb/utils.py
- vllm_ascend/models/deepseek_v2.py
- vllm_ascend/ops/fused_moe.py
- vllm_ascend/worker/model_runner_v1.py
this pr is eplb add support for qwen3-moe
test in qwen3-moe-235b w8a8 tp1dp16ep16 has 3% optimization
> [0.9.1]eplb support qwen3-moe

- .github/workflows/accuracy_test.yaml
- .github/workflows/nightly_benchmarks.yaml
Upgrade vllm in accuracy and performance CI
- vLLM main: https://github.com/vllm-project/vllm/commit/5c4b6e66fec0a59f702e32ec5c476cdd8a800566
> [CI] Upgrade vllm in accuracy and performance CI

- tests/e2e/singlecard/test_embedding.py
- vllm_ascend/worker/model_runner_v1.py
- vllm_ascend/worker/npu_input_batch.py
Fix broken embedding function. It's broken by http://github.com/vllm-project/vllm/pull/23162
- vLLM main: https://github.com/vllm-project/vllm/commit/efc88cf64a399f5459cd6256223e99672c13614d
> [Embedding] Recover embedding function

- vllm_ascend/torchair/torchair_model_runner.py
Fix the bug of cos invalid shape when dp
- vLLM main: https://github.com/vllm-project/vllm/commit/1fdc732419d9b9eb00e003f38d6e02c480131ac8
> [Bugfix] Fix the bug of cos invalid shape when dp

- vllm_ascend/quantization/w8a8_dynamic.py
VRAM usage increased abnormally during mixed-precision inference with quantized models and floating-point MTP. This was caused by `dist.all_to_all_single` creating extra HCCL communicators, which produced unnecessary buffers that consumed more memory.
This commit adds a communicator parameter to `dist.all_to_all_single`. By passing the existing communicator from the `vllm-ascend` framework, we ensure all communication operations use a unified domain, preventing the creation of extra buffers and solving the VRAM issue.
@kunpengW-code 
cc @farawayboat @MengqingCao
> [0.9.1][bugfix] Address abnormal VRAM increase in quantized models with floating-point MTP

- docs/source/tutorials/multi_node.md
Upgrade to multi-node tutorial model to deepseek-v3.1-w8a8
- vLLM main: https://github.com/vllm-project/vllm/commit/de02b07db4741cc9ed40b8262d7a67e6bce30211
> [Doc] Upgrade to multi-node tutorial model to deepseek-v3.1-w8a8

- docs/source/developer_guide/performance/optimization_and_tuning.md
- docs/source/faqs.md
- docs/source/installation.md
- docs/source/quick_start.md
- docs/source/tutorials/multi_node.md
- docs/source/tutorials/multi_npu.md
- docs/source/tutorials/multi_npu_quantization.md
- docs/source/tutorials/multi_npu_qwen3_moe.md
- docs/source/tutorials/single_npu.md
- docs/source/tutorials/single_npu_multimodal.md
- docs/source/user_guide/feature_guide/graph_mode.md
- docs/source/user_guide/feature_guide/lora.md
- docs/source/user_guide/feature_guide/quantization.md
- docs/source/user_guide/feature_guide/sleep_mode.md
- docs/source/user_guide/feature_guide/structured_output.md
- docs/source/user_guide/support_matrix/supported_features.md
- docs/source/user_guide/support_matrix/supported_models.md
> [0.9.1][doc]Update doc for 0.9.1

- docs/source/developer_guide/performance/distributed_dp_server_with_large_ep.md
- docs/source/developer_guide/performance/index.md
- docs/source/tutorials/index.md
- docs/source/tutorials/large_scale_ep.md
- docs/source/user_guide/configuration/additional_config.md
Add more details and Optimize the directory structure in the large scale ep document
No
No
> [v0.9.1][Doc]Large Scale Ep doc update

- tests/ut/attention/test_mla_v1.py
Update UT for MLA case
- vLLM main: https://github.com/vllm-project/vllm/commit/14b4326b9470c098d537cce3834033a7f3b2c386
> Add ut for mla

- docs/source/user_guide/configuration/additional_config.md
- tests/ut/test_ascend_config.py
- vllm_ascend/ascend_config.py
- vllm_ascend/torchair/torchair_model_runner.py
support torchair mode
No
- vLLM main: https://github.com/vllm-project/vllm/commit/5438967fbc7a10ae6eee7a98182f4de94101e858
> support torchair mode

- tests/ut/ops/test_rotary_embedding.py
- vllm_ascend/ops/rotary_embedding.py
Clean up useless code which is only used for torchair in rotary_embedding
- vLLM main: https://github.com/vllm-project/vllm/commit/a344a5aa0a58cc1758d9721e848ce1f5ca4b6c7f
> [Misc] Clean up uesless code in rotary_embedding

- docs/source/faqs.md
This PR add 'How to get better performance in Non-MLA LLMs' in FAQs.
No.
> [v0.9.1][doc] add 'How to get better performance in Non-MLA LLMs' in FAQs

- docs/source/locale/zh_CN/LC_MESSAGES/community/versioning_policy.po
- docs/source/locale/zh_CN/LC_MESSAGES/developer_guide/performance/optimization_and_tuning.po
- docs/source/locale/zh_CN/LC_MESSAGES/faqs.po
- docs/source/locale/zh_CN/LC_MESSAGES/installation.po
- docs/source/locale/zh_CN/LC_MESSAGES/quick_start.po
- docs/source/locale/zh_CN/LC_MESSAGES/tutorials/large_scale_ep.po
- docs/source/locale/zh_CN/LC_MESSAGES/tutorials/multi_npu_quantization.po
- docs/source/locale/zh_CN/LC_MESSAGES/user_guide/configuration/additional_config.po
- docs/source/locale/zh_CN/LC_MESSAGES/user_guide/feature_guide/lora.po
- docs/source/locale/zh_CN/LC_MESSAGES/user_guide/feature_guide/sleep_mode.po
- docs/source/locale/zh_CN/LC_MESSAGES/user_guide/release_notes.po
- docs/source/locale/zh_CN/LC_MESSAGES/user_guide/support_matrix/supported_features.po
- docs/source/locale/zh_CN/LC_MESSAGES/user_guide/support_matrix/supported_models.po
> [0.9.1][Doc] Update doc for zh-cn

- README.md
- README.zh.md
Refresh the news. Add meetup and official release info
- vLLM main: https://github.com/vllm-project/vllm/commit/b5ee1e3261d9edf94d76ba8b437ebdef7ac599ea
> [Doc] Update news

- README.md
- README.zh.md
- docs/source/community/contributors.md
- docs/source/community/versioning_policy.md
- docs/source/conf.py
- docs/source/faqs.md
- docs/source/user_guide/release_notes.md
Add Release Note for v0.10.1rc1
- vLLM main: https://github.com/vllm-project/vllm/commit/b5ee1e3261d9edf94d76ba8b437ebdef7ac599ea
> [ReleaseNote] Add Release Note for v0.10.1rc1

- docs/source/locale/zh_CN/LC_MESSAGES/user_guide/support_matrix/supported_models.po
- docs/source/user_guide/support_matrix/supported_models.md
> [0.9.1][Doc] Update supported models

- README.md
- README.zh.md
- docs/source/installation.md
Add note for Ascend HDK version
No
CI passed
> Add note for Ascend HDK version

- tests/e2e/multicard/test_offline_inference_distributed.py
- tests/ut/ops/test_layernorm.py
- tests/ut/test_utils.py
- vllm_ascend/ascend_forward_context.py
- vllm_ascend/envs.py
- vllm_ascend/ops/__init__.py
- vllm_ascend/ops/layernorm.py
- vllm_ascend/ops/linear.py
- vllm_ascend/ops/register_custom_ops.py
- vllm_ascend/utils.py
- vllm_ascend/worker/model_runner_v1.py
Flashcomm_v1 optim in Qwen Dense Models.
No.
- vLLM main: https://github.com/vllm-project/vllm/commit/5e537f45b453096c489d06f0c47776f9436ef99b
> [main] flashcomm_v1 optim in Qwen Dense Models

- tests/ut/test_utils.py
- vllm_ascend/models/deepseek_v2.py
- vllm_ascend/models/layers/mla.py
- vllm_ascend/utils.py
Register AscendMultiHeadLatentAttention
N/A
- vLLM main: https://github.com/vllm-project/vllm/commit/b23fb78623f0019854af7a820d398cba9a316677
> Refactor AscendMultiHeadLatentAttention

- .github/actionlint.yaml
- .github/workflows/pre-commit.yml
Update pre_commit runner
- vLLM main: https://github.com/vllm-project/vllm/commit/0ae43dbf8cb28a299ae724fc742b0c5bcddea868
> [CI] Update pre_commit runner

- tests/ut/models/test_deepseek_v2.py
- tests/ut/test_ascend_config.py
- vllm_ascend/ascend_config.py
- vllm_ascend/models/deepseek_v2.py
- vllm_ascend/models/layers/mla.py
- vllm_ascend/ops/common_fused_moe.py
- vllm_ascend/platform.py
- vllm_ascend/worker/model_runner_v1.py
In memory of #677 , a long overdue milestone. Now DeepSeek V3/R1 should be OK with ACL Graph.
None.
Working on it.
- vLLM main: https://github.com/vllm-project/vllm/commit/68dbde5dbb11b9250454d0c9f21a8b3da960b341
> [Feat][Graph] Support DeepSeek with ACL Graph

- vllm_ascend/attention/mla_v1.py
- vllm_ascend/torchair/torchair_mla.py
- vllm_ascend/torchair/torchair_model_runner.py
1. In memory of #2509, Fix mtp torchair in pd Disaggregation scenario
2. fix mla bug in  SpecDecoding Scenario， since num_decodes != num_decode_tokens
- vLLM main: https://github.com/vllm-project/vllm/commit/5206ab20ba7477e5457c2e64469590d548fa15e6
> [Bugfix] Fix mtp torchair in pd Disaggregation scenario

- docs/source/user_guide/configuration/additional_config.md
- tests/ut/test_ascend_config.py
- vllm_ascend/ascend_config.py
- vllm_ascend/torchair/torchair_model_runner.py
Add an option of enable  frozen parameter
- vLLM main: https://github.com/vllm-project/vllm/commit/68dbde5dbb11b9250454d0c9f21a8b3da960b341
> Add an option of enable frozen parameter

- tests/e2e/singlecard/spec_decode_v1/test_v1_mtp_correctness.py
- tests/ut/attention/test_mla_v1.py
- tests/ut/torchair/test_torchair_mla.py
- vllm_ascend/attention/mla_v1.py
- vllm_ascend/spec_decode/mtp_proposer.py
- vllm_ascend/torchair/torchair_model_runner.py
- vllm_ascend/worker/model_runner_v1.py
This PR depends on the merge of #2707 and has adapted the aclgraph functionality to support MTP. 
- vLLM main: https://github.com/vllm-project/vllm/commit/2b856970313e80a649a573879d94e9d3430ba018
> [Feat][Graph] Support MTP for ACL Graph

- docs/source/tutorials/index.md
- docs/source/tutorials/multi_node_ray.md
Add multi-node ray backend tutorial for Qwen235B-A3B
- vLLM main: https://github.com/vllm-project/vllm/commit/f4cd80f94404787859ba72dcddb5e818d8f0c9e7
> [Doc] Add multi-node ray backend tutorial

- docs/source/locale/zh_CN/LC_MESSAGES/user_guide/configuration/additional_config.po
- docs/source/user_guide/configuration/additional_config.md
- examples/disaggregated_prefill_v1/README.md
- vllm_ascend/attention/mla_v1.py
- vllm_ascend/torchair/torchair_mla.py
Remove chunked prefill for mla branch in mla , and change dtype of prefill_mask to avoid accuracy problem
NO
- vLLM main: https://github.com/vllm-project/vllm/commit/ef7eefe17a7dc212ddb8a8aabd7760218a10e25e
> Remove chunked_prefill_for_mla and fix ring_mla bug

- vllm_ascend/torchair/models/torchair_deepseek_v2.py
Remove useless PD check in deepseek
> Remove useless PD check in deepseek

- .github/workflows/format_pr_body.yaml
- .github/workflows/vllm_ascend_test.yaml
- .github/workflows/vllm_ascend_test_full.yaml
- tests/ut/models/test_qwen2_5_vl.py
- tests/ut/ops/test_linear.py
- vllm_ascend/patch/worker/patch_common/__init__.py
- vllm_ascend/patch/worker/patch_common/patch_weight_loader.py
- vllm_ascend/torchair/torchair_worker.py
- vllm_ascend/worker/model_runner_v1.py
Upgrade vLLM version to the newest commit.
- Fix the break change introduced by  https://github.com/vllm-project/vllm/commit/969b4da3a6ab737f72cb33db502b4c0bb70d4139
- Add a patch to quick fix torhcair https://github.com/vllm-project/vllm/commit/de94289a98d7ec52a5ef02719e01a1db8b505170 
- fix the ut error introduced by https://github.com/vllm-project/vllm/commit/de94289a98d7ec52a5ef02719e01a1db8b505170
Close: https://github.com/vllm-project/vllm-ascend/issues/3138
> [CI] Upgrade vLLM version

- vllm_ascend/ascend_forward_context.py
- vllm_ascend/utils.py
Cleanup wrong warning log error: model config is None
> [bugfix] Fix warning bug: model config is None.

- docs/source/faqs.md
add faqs:install vllm-ascend will overwrite existing torch-npu
> [Doc] add faqs:install vllm-ascend will overwrite existing torch-npu

- docs/source/developer_guide/performance/distributed_dp_server_with_large_ep.md
- docs/source/developer_guide/performance/index.md
- examples/deepseek.md
- examples/omni_infer_inventory_used_for_1P32_1D32.yml
- examples/omni_infer_server_template_a3_ds.yml
Add deepseek.md
Add deepseek.md
Preview
> V0.9.1 dev

- docs/source/tutorials/hybrid_node.md
- docs/source/tutorials/index.md
- docs/source/tutorials/multi-node_dsv3.2.md
- docs/source/tutorials/multi_node_qwen3vl.md
Add deepseek v3.2 tutorial
- vLLM version: v0.11.0rc3
> [Doc] Add deepseek v3.2 tutorial

- tests/ut/ops/test_token_dispatcher.py
- vllm_ascend/ops/moe/token_dispatcher.py
It will crash when deepseek model executed in A2.
- vLLM version: v0.11.0rc3
> [bugfix] Fix moe bug: allgather error.

- examples/omniinfer/omni/adaptors/vllm/patches/pangu_patch.py
- examples/omniinfer/omni/models/__init__.py
- examples/omniinfer/omni/models/deepseek/deepseek_v32.py
Add model_type deepseek_v32 support with proper model registration and AutoConfig support
No.
Image was built and fully tested with various seq length.
> add model_type deepseek_v32 support

- docs/source/tutorials/multi-node_dsv3.2.md
Fix doc for A2 series and cleanup note
No
CI passed
- vLLM version: v0.11.0rc3
> Fix doc for A2 series and cleanup note
