vllm-project/vllm-ascend

.gitignore, vllm_ascend/attention.py, vllm_ascend/model_runner.py, vllm_ascend/worker.py
This PR is a refactoring of model runner, to decouple it from the classes specifically designed for GPU.
The changes of model runner are generally showed below:
**Other changes:** I have removed the code of `cuda`, `lora` and `prompt adapter`, because NPU doesn`t support them now.
no.
I have used `AI-ModelScope/gpt2` for testing `examples/offline_inference_npu.py`, and the results showed that it worked well.
The test logs are showed below:
```bash
INFO 02-05 09:08:46 __init__.py:30] Available plugins for group vllm.platform_plugins:
INFO 02-05 09:08:46 __init__.py:32] name=ascend, value=vllm_ascend:register
INFO 02-05 09:08:46 __init__.py:34] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-05 09:08:46 __init__.py:36] set environment variable VLLM_PLUGINS to …
```
=> [ModelRunner] Refactor model_runner for NPU

CONTRIBUTING.zh.md, README.md, README.zh.md, docs/environment.zh.md
This PR adds Chinese documents for vllm-ascend  for  Chinese-speaking developers
Change as follows
- add README.zh.md
- add environment.zh.md
- add CONTRIBUTING.zh.md
By CI
=> [Doc]Add chinese doc

README.md, README.zh.md
Replace logo official link and update contrib doc
No
Preview:
- https://github.com/Yikun/vllm-ascend/blob/336055be1a271b5c349d19b0c5dc29e77caadf4f/README.zh.md
- https://github.com/Yikun/vllm-ascend/blob/336055be1a271b5c349d19b0c5dc29e77caadf4f/README.md
=> [Doc] Replace logo official link and update contrib doc

vllm_ascend/attention.py, vllm_ascend/model_runner.py, vllm_ascend/ops/activation.py, vllm_ascend/ops/rotary_embedding.py
Add silu_and_mul and rope ops;
Replace the original ops in attention impl with three mixed ops: reshape_and_cache, pagedattention and selfattention for better performance.
=> [Hardware][Ascend] Add silu_and_mul/rope; Add mix ops into attention layer

examples/offline_distributed_inference_npu.py, vllm_ascend/attention.py
Fix device of tensors created in `AscendAttentionBackendImpl`.
While specifying device to cards except card-0, there'll cause an **device conflict** because the tensors (such as `attn_mask`) will be put on card-0 by default.
This pr creates these tensors on the correct card corresponding to the input.
User could specify device with local rank by this pr, and a modify on vLLM is also needed, will related to this pr when created.
This is tested by the following code locally. Will add a test case when the modify in vLLM is also completed.
```python
from vllm import LLM, SamplingParams
prompts = [
"Hello, my name is",
"The president of the United States is",
"The capital of France is",
"The future of AI is",
]
sampling_params = SamplingParams(max_tokens=100, temperature=0.0)
llm = …
```
=> [attn] fix device of tensors in attention

README.md, README.zh.md, docs/installation.md
- Fix typos: vllm-ascned --> vllm-ascend
- For version info
No
preview
=> Followup fix on official doc update

vllm_ascend/communicator.py, vllm_ascend/patch/__init__.py, vllm_ascend/patch/patch_commnicator.py, vllm_ascend/platform.py
Some PR for plugin support is not merged by vllm yet. This PR add monkey patch to vllm-ascend to make vllm-ascend work with vllm directly.
This patch code should be removed once the related function is supported by vllm originally.
=> [Communicator] Add monkey patch

setup.py
fix packages for finding submodule. 
Before this pr, the wheel built by pip not contain submodule `ops` , thus will raise an `ImportError` when importing vllm
1. build vllm-ascend wheel by pip
```bash
cd ./vllm-ascend
pip wheel ./ --no-deps
pip install vllm_ascend-0.1.dev11+g07f2a16.d20250211-py3-none-any.whl  #change file name according to yours wheel.
```
2. check vllm
```python
import vllm
```
=> [Misc][Build] Fix packages for finding submodule

.github/workflows/mypy.yaml, mypy.ini
- Remove on communicator mypy to address: https://github.com/vllm-project/vllm-ascend/pull/24#issuecomment-2647696781
- Add mypy.ini to trigger list
No
CI passed
=> [FOLLOWUP][Misc] Remove unused mypy config for base_communicator

pyproject.toml, requirements.txt
This PR updates the dependency version of vllm-ascend on torch-npu, so that the vllm-ascend can be installed in a later version environment (like to torch-npu 2.6.0rc1),
No
CI Test
=> [Misc] update the dependency version of torch-npu

setup.py, vllm_ascend/patch/patch_commnicator.py, vllm_ascend/platform.py, vllm_ascend/worker.py
Fix communicator patch for distributed inferencing.
We should patch `GroupCoordinator` with its module, and just before initializing distributed env. So that the patch won't be shadowed by the import of `init_distributed_environment` in `worker.py`
=> [dist] fix communicator patch

docs/quick_start.md
This PR add the quickstart doc 
No
Preview
=> [Doc] Add Quickstart doc

vllm_ascend/ops/rotary_embedding.py, vllm_ascend/platform.py
This PR makes two changes for better performance:
1. Optimize the 'to' conversion in rope forward. New code only performs 'to' when device or dtype has changed
2. Change the default block_size from 16 to 128 in platform.py, because Ascend Devices have better affinity with block size 128.
=> [Rope][Platform] optimize the to conversion in rope forward and reset default block_size in platform.py

README.md, README.zh.md, docs/source/installation.md
=> [Doc] Add install doc

.github/workflows/image.yml, Dockerfile
Add container image build ci:
- Enable branch, tag docker image publish
- branch image: `vllm-ascend:main`, `vllm-ascend:v0.7.1-dev`
- tag image: `vllm-ascend:v0.7.1rc1`
- Enable PR docker image build check
- other changes:
- Prepare the `REPO_OWNER` because the ghcr lowerercase required
- Add `Free up disk space` step to avoid `No space left on device` like https://github.com/vllm-project/vllm-ascend/issues/27
- Setup qemu with image to resolve https://github.com/docker/setup-qemu-action/issues/198
NO
build: CI passed [push false](https://github.com/vllm-project/vllm-ascend/actions/runs/13347017608/job/37278724158?pr=64)
Note for test case:
1. merge commits ot `main`, `v0.7.1-dev` branch 
✅ main: https://github.com/Yikun/vllm-ascend/actions/runs/13347238961 --> …
=> [CI] Add container image build ci

README.md, README.zh.md, docs/source/conf.py, docs/source/developer_guide/versioning_policy.md, docs/source/developer_guide/versioning_policy.zh.md, docs/source/index.md
This patch add the versioning policy doc for vllm-ascend
Reference:
- https://spark.apache.org/versioning-policy.html
- https://docs.openstack.org/project-team-guide/stable-branches.html
- https://github.com/pytorch/pytorch/blob/main/RELEASE.md
No
preview: https://vllm-ascend--62.org.readthedocs.build/en/62/
=> [Doc] Add versioning_policy doc

.github/workflows/image.yml, Dockerfile
Backport https://github.com/vllm-project/vllm-ascend/pull/64 to v0.7.1-dev branch
Add container image build ci:
- Enable branch, tag docker image publish
- branch image: `vllm-ascend:main`, `vllm-ascend:v0.7.1-dev`
- tag image: `vllm-ascend:v0.7.1rc1`
- Enable PR docker image build check
- other changes:
- Prepare the `REPO_OWNER` because the ghcr lowerercase required
- Add `Free up disk space` step to avoid `No space left on device` like https://github.com/vllm-project/vllm-ascend/issues/27
- Setup qemu with image to resolve https://github.com/docker/setup-qemu-action/issues/198
NO
build: CI passed
=> [v0.7.1][CI] Add container image build ci

README.md, README.zh.md, docs/source/installation.md
Refeactor installation doc
backport https://github.com/vllm-project/vllm-ascend/pull/80
No
CI, preview
=> [v0.7.1][Docs] Refeactor installation doc

vllm_ascend/platform.py
Changed default block_size in platform.py from 16 to 128, as Ascend Devices have a better affinity for block size 128.
=> reset default block_size from 16 to 128

examples/offline_distributed_inference_npu.py, examples/offline_inference_audio_language.py, examples/offline_inference_npu.py
- Set default model to Qwen2.5-0.5B-Instruct in example
- Remove Ultravox 0.3 because it is not tested currently
=> [MISC] set default model to qwen in example

vllm_ascend/attention.py, vllm_ascend/platform.py
To adapt to the MLA structure of vLLM DeepSeek on Ascend hardware, write the AscendMLAAttentionBackendImpl class. 
Users can choose to set VLLM_MLA_DISABLE to 1 or 0 to disable or enable MLA.
=> [Hardware][Ascend]MLA for deepseek

.github/workflows/vllm_ascend_test.yaml, Dockerfile, docs/source/conf.py, docs/source/developer_guide/contributing.md, docs/source/developer_guide/versioning_policy.md, docs/source/developer_guide/versioning_policy.zh.md, docs/source/installation.md, docs/source/quick_start.md, docs/source/tutorials.md, docs/source/user_guide/release_notes.md, docs/source/user_guide/supported_models.md
1. Update CANN image name
2. Add pta install step
3. update vllm-ascend docker image name to ghcr
4. update quick_start to use vllm-ascend image directly.
5. fix `note` style
cherry-pick from https://github.com/vllm-project/vllm-ascend/pull/85
=> [Doc] Update doc to work with release (#85)

vllm_ascend/ops/fused_moe.py
Fix a bug caused by omitting to change the parameter name.
=> [BugFix] Delete redundant variables

vllm_ascend/platform.py
Add dispatch key for NPU, so that the log could be print correctly.
Now
```
executor_base.py:110] # CPU blocks: 220478, # CPU blocks: 21845
```
After this pr
```
executor_base.py:110] # NPU blocks: 220478, # CPU blocks: 21845
```
N/A
CI passed and log printed as above
=> [Platform] add dispatch key

.github/ISSUE_TEMPLATE/100-documentation.yml, .github/ISSUE_TEMPLATE/200-installation.yml, .github/ISSUE_TEMPLATE/300-usage.yml, .github/ISSUE_TEMPLATE/400-bug-report.yml, .github/ISSUE_TEMPLATE/500-feature-request.yml, .github/ISSUE_TEMPLATE/600-new-model.yml, .github/ISSUE_TEMPLATE/700-performance-discussion.yml, .github/ISSUE_TEMPLATE/750-RFC.yml, .github/ISSUE_TEMPLATE/800-others.yml, .github/ISSUE_TEMPLATE/config.yml
Add issue templates.
Most of templates in this PR are from vllm-project/vllm: https://github.com/vllm-project/vllm/tree/main/.github/ISSUE_TEMPLATE
No
Test on my local repo by setting default branch to ISSUE_TEMPLATE: https://github.com/Yikun/vllm-ascend/issues
https://github.com/Yikun/vllm-ascend/issues/new/choose
Closes: https://github.com/vllm-project/vllm-ascend/issues/48
=> [Docs] Add issue template

vllm_ascend/model_runner.py
In Model Runner, is_encoder_decoder is exacted from model_config to determin whether vllm is running for enc-dec models. Obtaining this status requires a long call stack, and the CPU overhead is high. So this PR cache this status in __init__ of ModelInputForNPUBuilder.
=> [Model Runner][Performance] Cache the jugement result of is_encoder_decoder to decrease framework overhead

vllm_ascend/platform.py, vllm_ascend/worker.py
In the case where `backend = ray`, only the main process completes the `forward_oot` call, while the other worker processes call `forward_native`. (This bug should also exist when `backend = mp`.)
no.
**Environment:**
CANN: 8.0.0
PyTorch: 2.5.1
Torch: 2.5.1rc1
python: 3.10
python: 3.10
vllm: branch main 
vllm-ascend: branch main 
The current implementation avoids the Ray Worker initialization issue, as addressed in the [PR](https://github.com/vllm-project/vllm-ascend/pull/92). Then, during the `forward_oot` call, logging will be performed.
**Script:**
```bash
python examples/offline_distributed_inference_npu.py
```
**Result:**
```bash
NPURayWorkerWrapper pid=3984223) forward_oot run. #############################################
(NPURayWorkerWrapper pid=3984223) forward_oot run. …
```
=> Ray Worker Ops Optimization

vllm_ascend/model_runner.py
The arg list of `Attention.forward()` is changed by https://github.com/vllm-project/vllm/pull/13555.
The unused args `kv_caches` and `attn_metadata` are removed.
N/A
=> [ModelRunner] remove unused args (follow vllm changes)

vllm_ascend/patch/__init__.py, vllm_ascend/patch/patch_minicpm.py, vllm_ascend/patch_module.py, vllm_ascend/worker.py
In order to adapt the MiniCPM-2B model of the vLLM framework to Ascend hardware, the following two modifications are required: 1. The qkv type conversion in the forward function is deleted to support the rope operator. 2. The fused_moe.fused_moe module is replaced to prevent errors caused by triton not supported，this modification can be deleted if triton is supported
=> [Model] Adapt the MiniCPM-2B model

.github/workflows/vllm_ascend_test.yaml
Add `HF_TOKEN` for downloading models that requires access rights from huggingface hub. This will fix the CI error in #123 and #76
=> [CI/Build] add HF_TOKEN for model downloading

vllm_ascend/worker.py
Remove unused assertion in `NPUWorker`, as this has been moved to `Executor` in vLLM:
https://github.com/vllm-project/vllm/blob/aabeb2688fba861a39547a2a33649e6330caaafd/vllm/executor/uniproc_executor.py#L43
N/A
=> [worker] remove unused assertion

pytest.ini, vllm_ascend/model_runner.py
=> [CI][UT]enable multimodal ut

vllm_ascend/ops/fused_moe.py
Fix #176
We need to set `topk_group` and `num_expert_group` to `0` if they are `None`
=> [MOE] fix #176

docs/source/tutorials.md
Update multinode doc
fix #167 #168
=> [Doc] update multinode doc

docs/source/conf.py
remove v prefix in pip_vllm_version, followup on #203
NO
```
$ grep "|pip_vllm_version|" -r ./docs/source
./docs/source/installation.md:pip install vllm==|pip_vllm_version|
```
preview
=> [Followup] remove v prefix in pip_vllm_version

vllm_ascend/communicator.py
The rank returned by `torch.distributed.get_rank(device_group)` is the local rank, but rank (or rank in process group (PG)) is expected.
Thus we change to use `torch.npu.current_device()` to set device
```python
```
Tested by @wwfu109 with `vllm/tests/distributed/test_customops::test_multi_process_tensor_parallel_pipeline_parallel`
=> [Dist] Set device as rank

vllm_ascend/patch/__init__.py, vllm_ascend/patch/patch_cache_dtype.py, vllm_ascend/platform.py
1. Ascend attention requires int8 kvcache dtype. It is used in initialization of CacheConfig:
```
if cache_config.cache_dtype == "auto":
self.dtype = model_config.dtype
else:
self.dtype = STR_DTYPE_TO_TORCH_DTYPE[cache_config.cache_dtype]
```
STR_DTYPE_TO_TORCH_DTYPE is defined in vllm.utils:
```
STR_DTYPE_TO_TORCH_DTYPE = {
"half": torch.half,
"bfloat16": torch.bfloat16,
"float": torch.float,
"fp8": torch.uint8,
"fp8_e4m3": torch.uint8,
"fp8_e5m2": torch.uint8,
}
```
Hence we need to update both cache_dtype and STR_DTYPE_TO_TORCH_DTYPE.
=> [Core]Add "int8" kv cache dtype patch for attention quantization

Dockerfile, pta_install.sh
Install `wget` to fix image build
Backport https://github.com/vllm-project/vllm-ascend/pull/231
No
CI passed
=> [v0.7.3] Install wget to fix image build

Dockerfile, pta_install.sh
Install `wget` to fix image build
No
CI passed
=> Install wget to fix image build

vllm_ascend/worker.py
Add transfer_to_npu in worker.py to replace hard-code 'cuda' in vllm. (This change can be remove after v0.7.4)
=> [BugFix] Add transfer_to_npu in worker.py to replace hard-code 'cuda' in vllm.

.github/ISSUE_TEMPLATE/400-bug-report.yml, collect_env.py
Add `collect_env.py` scripts from vLLM and remove `nvidia`, `gpu`, `cuda` related codes, thus users of vllm-ascend can collect their env info when reporting bugs.
no.
Run `python collect_env.py` and a example of results are shown below:
```bash
PyTorch version: 2.5.1
Is debug build: False
ROCM used to build PyTorch: N/A
OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.31.4
Libc version: glibc-2.35
Python version: 3.10.16 (main, Dec 11 2024, 16:18:56) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.19.90-vhulk2211.3.0.h1804.eulerosv2r10.aarch64-aarch64-with-glibc2.35
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
CPU:
Architecture: …
```
=> [Misc] Add collect_env.py scripts for bug reporting

docs/source/user_guide/suppoted_features.md, vllm_ascend/attention.py, vllm_ascend/platform.py, vllm_ascend/worker/model_runner.py, vllm_ascend/worker/pooling_model_runner.py, vllm_ascend/worker/worker.py
This PR added pooling support for vllm-ascend
Tested with `bge-base-en-v1.5` by encode:
```
from vllm import LLM
prompts = [
"Hello, my name is",
"The president of the United States is",
"The capital of France is",
"The future of AI is",
]
model = LLM(model="./bge-base-en-v1.5", enforce_eager=True)
outputs = model.encode(prompts)
for output in outputs:
print(output.outputs.embedding)  # list of 4096 floats
```
Tested by embedding:
```
from vllm import LLM, SamplingParams
llm = LLM(model="./bge-base-en-v1.5", task="embed")
(output,) = llm.embed("Hello, my name is")
embeds = output.outputs.embedding
print(f"Embeddings: {embeds!r} (size={len(embeds)})")
```
Related: https://github.com/vllm-project/vllm-ascend/issues/200
The accuracy is not correct since this feature rely on `enc-dec` …
=> [Core] Support pooling

format.sh
Exclude `collect_env.py` from `CODESPELL` check in `format.sh`, otherwise it will get the error shown below:
```bash
vLLM yapf: Done
vLLM mypy:
Running mypy on vllm_ascend
Success: no issues found in 18 source files
Running mypy on examples
Success: no issues found in 3 source files
Running mypy on tests
Success: no issues found in 3 source files
vLLM mypy: Done
collect_env.py:410: CANN ==> CAN
```
no.
no.
=> [Bugfix] Exclude collect_env.py from CODESPELL check in format.sh

vllm_ascend/attention.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/worker/worker.py
This PR changes the shape of kv cache to avoid the view of k_cache and v_cache.
What's more, cache the metadata of k_cache and v_cache to avoid duplicative slice operations to improve performance.
=> [Performance] Change the shape of kv_cache to avoid view of k_cache and v_cache.

vllm_ascend/quantization/quant_config.py, vllm_ascend/quantization/quantizer.py
1. It adds more description for classes in quant_config.py
2. It renames AscendQKVQuantAttentionMethod to AscendKVCacheMethod to align with vLLM naming style.
3. It modifies the process when AscendLinearMethod or AscendKVCacheMethod calls create_weights.
-->
Yes. When creating weights, now AscendLinearMethod uses get_weight, get_pertensor_param and get_perchannel_param api from linear quant implementation, while AscendKVCacheMethod passes layer into linear quant implementation.
By performing offline inference:
=> [Feature] Modify description and api for ascend quantization

.github/workflows/vllm_ascend_test.yaml, tests/test_offline_inference.py
Add dispatch job to leverage jobs to dynamic devices include 2 stage as below:
The dispatch job will spend extra about `10s * parallel number + 30s` time to wait other job launch container and release lock.
- **Stage 1: Acquire lock**
add a dispatch job, this job use lockfile to acquire locks and then get device number dynamically
- **Stage 2.1: Launch container with dynamic device**
pass the device number via output and start the container job with dynamic device
- **Stage 2.2: Release lock**
once the job started, release the lock.
In the backend, we use multiple path to setup multiple self host runners as load balancer:
```
$ pwd
/home/action
$ ll | grep actions
drwx------   6 action action 4096 Mar  7 08:55 actions-runner-01
drwx------   6 action action 4096 Mar  7 08:55 …
```
=> [CI] Add dispatch job to leverage dynamic devices

.github/workflows/vllm_ascend_test.yaml, tests/test_offline_inference.py
Backport: https://github.com/vllm-project/vllm-ascend/pull/251
Add dispatch job to leverage jobs to dynamic devices include 2 stage as below:
The dispatch job will spend extra about `10s * parallel number + 30s` time to wait other job launch container and release lock.
- **Stage 1: Acquire lock** add a dispatch job, this job use lockfile to acquire locks and then get device number dynamically
- **Stage 2.1: Launch container with dynamic device** pass the device number via output and start the container job with dynamic device
- **Stage 2.2: Release lock** once the job started, release the lock.
In the backend, we use multiple path to setup multiple self host runners as load balancer:
```
$ pwd
/home/action
$ ll | grep actions
drwx------   6 action action 4096 Mar  7 08:55 …
```
=> [v0.7.3][CI] Add dispatch job to leverage dynamic devices (#251)

.github/workflows/vllm_ascend_test.yaml, README.md, README.zh.md, docs/source/installation.md, pta_install.sh
Bump torch_npu version to dev20250308.3 to fix performance regression on multi-stream case: https://github.com/Ascend/pytorch/commit/e04c580d07c0a49a46217656fd84465ca1114d24 .
NO
CI passed
=> Bump torch_npu version to dev20250308.3

.github/workflows/vllm_ascend_test.yaml, README.md, README.zh.md, docs/source/installation.md, pta_install.sh
Backport: https://github.com/vllm-project/vllm-ascend/pull/276
Bump torch_npu version to dev20250308.3 to fix performance regression on multi-stream case: https://github.com/Ascend/pytorch/commit/e04c580d07c0a49a46217656fd84465ca1114d24 .
NO
CI passed
=> [v0.7.3] Bump torch_npu version to dev20250308.3

Dockerfile
Pin modelscope<1.23.0 on vLLM v0.7.3 to resolve: https://github.com/vllm-project/vllm/pull/13807
No
CI passed
=> Pin modelscope<1.23.0 on vLLM v0.7.3

Dockerfile
Pin modelscope<1.23.0 on vLLM v0.7.3 to resolve: https://github.com/vllm-project/vllm/pull/13807
Backport: https://github.com/vllm-project/vllm-ascend/pull/272
No
CI passed
=> [v0.7.3] Pin modelscope<1.23.0 match vLLM 0.7.3

vllm_ascend/patch/__init__.py, vllm_ascend/patch/patch_spec_decode_worker.py, vllm_ascend/worker/draft_model_runner.py
support speculative decoding in Ascend, including speculating with a draft model、by matching n-grams in the prompt、using MLP speculators and using EAGLE based draft models.
u can refer to https://docs.vllm.ai/en/latest/features/spec_decode.html#
Four modes of speculative decoding have been tested, consistent with GPU devices
=> v0.7.3 support speculative decoding

requirements-dev.txt
Pin modelscope<1.23.0 match vLLM 0.7.3
https://github.com/vllm-project/vllm/pull/13807 is not included in v0.7.3, thus we just pin it to branch v0.7.3-dev
N/A
=> [CI][v0.7.3] Pin modelscope<1.23.0 match vLLM 0.7.3

vllm_ascend/platform.py, vllm_ascend/worker/model_runner.py
This PR changes the initial value of blocksize back to 128 and adds hash value of request id list in model runner for implementing sampling param cache in sampler.
=> [Platform][Model Runner] Add hash of request_ids; Change blocksize back to 128.

tests/ops/test_fused_moe.py, vllm_ascend/ops/fused_moe.py
Enable Expert-Parallel for ascend devices.
Enable EP
add `enable_expert_parallel=True` in your offline inference scripts, like this:
```python
llm = LLM(
model="/path/to/model",
trust_remote_code=True,
tensor_parallel_size=4,
max_model_len=4096,
enforce_eager=True,
distributed_executor_backend="mp",
enable_expert_parallel=True,
)
```
Please use the `main` branch of vLLM.
=> [Feature] Implement EP-compatible fused_moe

Dockerfile
triton doesn't work with ascend. We should make sure it's uninstalled in dockerfile
Related: https://github.com/vllm-project/vllm-ascend/issues/291
=> [CI] Uninstall triton in dockerfile

vllm_ascend/attention.py
Support encoder-only attention with torch sdpa
fix https://github.com/vllm-project/vllm-ascend/pull/229#issuecomment-2695942741
N/A
Test locally with `pytest vllm-project/vllm/tests/entrypoints/openai/test_score.py`
**Note**: Since torch compile on npu are still work in process, we need to comment the following code to make UT run:
https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/vocab_parallel_embedding.py#L138
result:
```bash
/home/xxx/miniconda3/envs/atb/lib/python3.10/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for …
```
=> [Attn] Support encoder-only attention with torch sdpa

Dockerfile
The triton doesn't work with ascend. We should make sure it's uninstalled in dockerfile
Backport: https://github.com/vllm-project/vllm-ascend/pull/298
Closes: https://github.com/vllm-project/vllm-ascend/issues/291
NO
CI passed
=> [CI] Uninstall triton in dockerfile (#298)

vllm_ascend/attention.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/quantization/quantizer.py
It fixes following bugs:
1. When searching a specific linear quantization implementation from a tool (such as MindIE-Turbo), the mapping of packed linear is required to identify correponding quant type.
2. The exception is narrowed down to ImportError when importing MindIETurboQuantizer to better throw other errors.
3. The api of AscendKVCacheMethod.apply is aligned with that in AscendAttentionBackendImpl.
No
By performing offline inference:
=> [BugFix] Fix bugs when using ascend quantization

vllm_ascend/platform.py, vllm_ascend/quantization/quant_config.py
Fix a bug that w8a8 without attention quantization is misidentified as using attention quantization.
no
=> [BugFix]fix w8a8 bug

.github/workflows/vllm_ascend_test.yaml, README.md, README.zh.md, docs/source/developer_guide/versioning_policy.md, docs/source/installation.md, pta_install.sh, pytest.ini
This pr upgrades torch-npu to 0320, so that #321, https://github.com/vllm-project/vllm-ascend/issues/267#issuecomment-2745045743 could be fixed, and #372 should be reverted after this pr
upgrade torch-npu to 0320
tested locally with long seq inferencing.
=> [CI/Build][Doc] upgrade torch-npu to 0320

CMakeLists.txt, cmake/utils.cmake, csrc/kernels/pos_encoding_kernels.cpp, csrc/kernels/types.h, csrc/kernels/utils.h, csrc/ops.h, csrc/torch_binding.cpp, csrc/utils.h, pyproject.toml, requirements-dev.txt, requirements.txt, setup.py, tests/ops/test_rotary_embedding.py, vllm_ascend/envs.py, vllm_ascend/platform.py
Add custom ascendc kernel support in vllm-ascend, this PR mainly include 3 parts:
-  AscendC implementation of rotary_embedding, and its unitest.
-  CMakeLists.txt to compile AscendC kernel and related torch library binding to this kernel.
-  Build and pack all the compiled so into the vllm_ascend's package.
For now, this rotary embedding kernel dose not support the scenario with `neoxStyle=False`, So its not used in the actual modeling parts. We will soon add this implements into the vllm-ascend and integrate it into the modeling parts.
No change at all
=> Custom AscendC op support in vllm_ascend

vllm_ascend/models/__init__.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/quantization/quant_config.py
add w8a8_dynamic quant & support deepseek quant
=> feat: add w8a8_dynamic quant & support deepseek quant

docs/source/installation.md
Add install system dependencies in install doc
Resolve:
```
$ pip install vllm==v0.7.3
CMake Error at CMakeLists.txt:14 (project):
No CMAKE_CXX_COMPILER could be found.
Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.
// ... ...
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for vllm
Failed to build vllm
ERROR: Failed to build installable wheels for some pyproject.toml based projects (vllm)
```
Closes: https://github.com/vllm-project/vllm-ascend/issues/439 
No
CI passed
=> [Docs] Add install system dependencies in install doc

.github/workflows/vllm_ascend_test_main.yaml, requirements-lint.txt, requirements.txt, vllm_ascend/worker/model_runner_v1.py
Fix CI by updating mypy and pining numpy version
_the modification of model_runner_v1 is just to make CI happy_
N/A
CI passed
=> [CI] Fix mypy CI

vllm_ascend/patch/__init__.py, vllm_ascend/patch/patch_multi_step_worker.py, vllm_ascend/worker/draft_model_runner.py
spec decode MultiStepWorker support TP1DraftModelRunner fully, support run the draft_model_runner with multi-step prepare on the NPU directly and support draft_model_runner use MLA.
1. before this pr, `MultiStepWorker` would not step into the branch using NPU prepare, but only into the branch using CPU prepare (`line 52` of `vllm_ascend/patch/patch_multi_step_worker.py`).  Although this has `no effect` on the `correct operation` of speculative decoding and the performance of the two branches is basically the same as of the current version, I support entering this branch in this PR. In general, there are two main changes in `patch_multi_step_worker.py`: first, the `is_cuda_like()` check is removed and the `TP1DraftModelRunner` rewritten in vllm_ascend is used; second, the …
=> [v0.7.3]spec decode MultiStepWorker support TP1DraftModelRunner fully

.github/workflows/vllm_ascend_test.yaml, requirements.txt, tests/spec_decode/conftest.py, tests/spec_decode/test_batch_expansion.py, tests/spec_decode/test_dynamic_spec_decode.py, tests/spec_decode/test_metrics.py, tests/spec_decode/test_multi_step_worker.py, tests/spec_decode/test_ngram_worker.py, tests/spec_decode/test_spec_decode_worker.py, tests/spec_decode/test_utils.py, tests/spec_decode/utils.py, vllm_ascend/attention/attention.py, vllm_ascend/platform.py
This PR enable the initial UT for speculative decoding.
And this is the first ut adaption pr, which mainly contains functional testing of funcs in spec decode related implementations.
Other things done in this pr:
1. install vllm from source in CI to contain the test scripts
2. run ut of spec decoding only when the related code is changed
3. fix attention and platform
TODO:
N/A
=> [1/N][CI/UT] enable spec decode related UT

.github/workflows/vllm_ascend_test_main.yaml, CMakeLists.txt, cmake/utils.cmake, csrc/kernels/pos_encoding_kernels.cpp, csrc/kernels/types.h, csrc/kernels/utils.h, csrc/ops.h, csrc/torch_binding.cpp, csrc/utils.h, pyproject.toml, requirements.txt, setup.py, tests/ops/test_rotary_embedding.py, vllm_ascend/envs.py, vllm_ascend/platform.py
This PR add custom ascendc kernel rotary_embedding support in vllm-ascend, related CMakeLists and setuptools is also added in this PR.
Related: https://github.com/vllm-project/vllm-ascend/issues/156
=> [core] Support custom ascendc kernels in vllm-ascend

vllm_ascend/worker/model_runner_v1.py
Cherry-pick from main https://github.com/vllm-project/vllm-ascend/pull/442.
Pre-construct a mask matrix to improve the efficiency of attention mask construction during inference.
Note that the length of the matrix needs to be carefully balanced: a matrix that is too large will consume excessive VRAM, while a matrix that is too small will require dynamic concatenation during inference, leading to performance degradation.
Therefore, an environment variable is added here to dynamically set the size of the pre-constructed mask matrix based on requirements.
=> [ModelRunner][V1] Optimize V1 attention mask

docs/source/installation.md
Backport https://github.com/vllm-project/vllm-ascend/pull/438
Add install system dependencies in install doc
Resolve:
```
$ pip install vllm==v0.7.3
CMake Error at CMakeLists.txt:14 (project):
No CMAKE_CXX_COMPILER could be found.
Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.
// ... ...
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for vllm
Failed to build vllm
ERROR: Failed to build installable wheels for some pyproject.toml based projects (vllm)
```
Closes: https://github.com/vllm-project/vllm-ascend/issues/439 
No
CI passed
=> [v0.7.3][Docs] Add install system dependencies in install doc (#438)

vllm_ascend/models/deepseek_v2.py, vllm_ascend/quantization/quant_config.py
we found that all quant weight from modelslim need flatten `scale` and `offset` to one-dimensional tensor before `load_weight`, so we move this code to `process_weights_after_loading`.
=> fix: fix deepseek quant bug

csrc/camem_allocator.cpp, vllm_ascend/__init__.py, vllm_ascend/device_allocator/camem.py, vllm_ascend/patch_config.py, vllm_ascend/worker/worker.py, vllm_ascend/worker/worker_v1.py
This PR adds sleep mode feature for vllm-ascend, when sleeps, we do mainly two things:
- offload model weights
- discard kv cache
RLHF tools(such as https://github.com/volcengine/verl and https://github.com/OpenRLHF/OpenRLHF) have a strong need of sleep mode to accelerate the training process. 
This PR may solve #375 and #320 .
No existing user interfaces changed.
Users will have two new methods(`sleep()` and `wake_up()`) to use.
This PR is tested with Qwen/Qwen2.5-0.5B-Instruct.
At first, we have free NPU memory M1.
After `llm = LLM("Qwen/Qwen2.5-0.5B-Instruct", enable_sleep_mode=True)` executed, we have free NPU memory M2. M2 < M1.
Then we call `llm.sleep(level=1)`, we have free NPU memory M3.
We have M3 > M2, M3 is very close to M1.
Plus, we have the same output tokens before sleep and …
=> Add sleep mode feature for Ascend NPU

.github/workflows/vllm_ascend_test_main.yaml, pyproject.toml, requirements.txt
vLLM bumps numpy version to 2.x: https://github.com/vllm-project/vllm/commit/8427f70493ed67bf26cb9e7fa98ac202b991c37d , this will cause a `pip._vendor.pkg_resources.ContextualVersionConflict: (numpy 2.2.4 (/usr/local/python3.10/lib/python3.10/site-packages), Requirement.parse('numpy==1.26.4'), {'vllm-ascend'})` failure when vllm ascend install. This PR resolved the issue by:
- Set numpy < 2.0.0 to resolve numpy VersionConflict
- Sync requirements and toml 
- Reorder
No
CI passed
Closes: https://github.com/vllm-project/vllm-ascend/issues/473
=> Set numpy < 2.0.0 to resolve numpy VersionConflict

pyproject.toml, requirements.txt
Set torchvision<0.21.0 to match torch/torch_npu version to resolve `RuntimeError: operator torchvision::nms does not exist`.
Closes: https://github.com/vllm-project/vllm-ascend/issues/477
No
CI passed
=> Set torchvision<0.21.0 to match torch/torch_npu version

.github/workflows/image_openeuler.yml, Dockerfile.openEuler, docs/source/quick_start.md
Provide users with openEuler-based vllm images, so modify the quick start readme
None
There is no need for performing any test.
=> Add openEuler based container image for vLLM Ascend

vllm_ascend/models/__init__.py, vllm_ascend/models/deepseek_mtp.py
Add support MTP in deepseek w8a8 quant model.
1. The quantized MTP layer of deepseek on the current NPU msmodelslim is not quantized, So the MTP layer in deepseek w8a8 quantization weight is still in bflaot16 format;
2. The description file generated by the current msmodelslim tool does not have MTP layer information. Please manually add it to `quantization_config` in `config.json` and set the value to `FLOAT`.
local tested
=> [v0.7.3]support MTP in deepseek w8a8 quant model

docs/source/developer_guide/contributing.md, docs/source/installation.md
1. install torch-npu before vllm-ascend to ensure custom ops build success.
2. set `COMPILE_CUSTOM_KERNELS=0` if users want to disable custom ops build.
=> [Build] Update doc

vllm_ascend/platform.py
Remove `supports_structured_output()` in platform. This method is no need, because upstream has deleted this.
=> [V1][Platform] Remove `supports_structured_output()` in platform

docs/source/faqs.md
update faq about progress bar display issue
=> [Doc] update faq about progress bar display issue

.github/workflows/vllm_ascend_test.yaml, tests/conftest.py, tests/spec_decode/e2e/test_eagle_correctness.py, tests/spec_decode/e2e/test_mtp_correctness.py, vllm_ascend/device_allocator/camem.py, vllm_ascend/patch/patch_spec_decode_worker.py, vllm_ascend/platform.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/utils.py, vllm_ascend/worker/draft_model_runner.py, vllm_ascend/worker/model_runner.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/multi_step_runner.py, vllm_ascend/worker/worker.py, vllm_ascend/worker/worker_v1.py
add spec decode e2e UT:
1. add `test_eagle_correctness.py`; 
2. add `test_mtp_correctness.py`; use bf16 model weights;
fix init_logger bug:
1. slove OOM probelm in `camem.py`;
2. replace `from vllm.logger import init_logger` to `from vllm.logger import logger` overall situation
None
Local verification passed
=> [3/N][CI/UT] add spec decode e2e UT && [BUGFIX] fix init_logger bug

CMakeLists.txt, docs/source/installation.md
- update doc about custom ops compile
=> [Doc] Update doc for custom ops build

vllm_ascend/worker/model_runner_v1.py
Add `apply_grammar_bitmask()` method to model runner.
This method is necessary for `xgrammar` structured output.
=> [V1][Structured Output] Add `apply_grammar_bitmask()` method to model runner

docs/source/user_guide/release_notes.md
Update v0.8.4 release note:
- Add contents for structured output feature.
- Remove redundant `(` in spec decoding.
=> [Doc] Update v0.8.4 release note, add contents for structured output feature

Dockerfile
Bump Dockerfile version to v0.8.4
docker image are using v0.8.4 version vLLM
CI passed
Closes: https://github.com/vllm-project/vllm-ascend/pull/571
=> [Docker] Bump Dockerfile version to v0.8.4

.github/workflows/image_openeuler.yml, .github/workflows/image_ubuntu.yml
There was a bug when we release v0.8.4rc1 (openEuler image tag was wrong set to 0.8.4rc1), according doc of docker-meta-action, it should be append suffix:
```
tags: |
type=pep440,enable=true,priority=900,prefix=,suffix=,pattern=,value=
```
This patch just fix openEuler image suffix to make pep440 tag rule work.
This patch also remove the cache step because the cache step bring more than 10mins export, but reduce less time in next trigger.
Yes, docker image tag set to right
I test with in my fork repo by setting default branch:
- release a tag: v0.7.88rc1 (pep440 tag)
- The log show `--label org.opencontainers.image.version=v0.7.88rc1-openeuler` is right rule
https://github.com/Yikun/vllm-ascend/actions/runs/14560411481/job/40842950165#step:9:205
Related: …
=> [Docker] Fix openEuler image suffix

CMakeLists.txt, setup.py, vllm_ascend/__init__.py, vllm_ascend/device_allocator/camem.py, vllm_ascend/envs.py, vllm_ascend/platform.py
To make compile adjust to more user envs.
To make patch timing better to adjust to more conditions.
No
Tested the same as #416
=> [0.7.3] Update patch timing and CMake to adjust to more user envs

.github/workflows/vllm_ascend_test.yaml, tests/spec_decode/e2e/test_eagle_correctness.py, tests/spec_decode/e2e/test_multistep_correctness.py, vllm_ascend/attention/attention.py
add spec decode e2e UT
1. add `test_multistep_correctness.py`;
2. open `tests/spec_decode/e2e/test_eagle_correctness.py` 2 cases by using modelscope weights;
fix chunked prefill bug
1. add support for `atten_mask`  only has 1 element
None
tested by CI and local test passed.
=> [0.7.3][5/N][CI/UT]add spec decode e2e UT && [BUGFIX]fix chunk prefill bug

docs/source/installation.md
Many users facing a failed installation when using `pip install -e .`, this is mainly introduced by the released `torch-npu` version conflict with `torch>=2.5.1`. This conflict mainly exist in the temp env of pyproject build. 
This pr updates installation tutorial by using `python setup.py develop` to quick fix this.
cc @wangxiyuan
=> [Doc] Update installation

docs/source/developer_guide/evaluation/index.md, docs/source/developer_guide/evaluation/using_evalscope.md
Using EvalScope to hava a evaluation (include eval and test):
- https://evalscope.readthedocs.io/en/latest/user_guides/stress_test/quick_start.html#basic-usage
- https://evalscope.readthedocs.io/en/latest/get_started/basic_usage.html#model-api-service-evaluation
No
Test locally
=> Using EvalScope evaluation 

vllm_ascend/patch/__init__.py, vllm_ascend/patch/platform/patch_common/patch_distributed.py
Add dp stateless process group initialization path with hccl backend as vllm-ascend patch.
=> Add dp initialize patch with hccl backend

vllm_ascend/models/__init__.py, vllm_ascend/models/qwen2_5_vl.py, vllm_ascend/ops/activation.py, vllm_ascend/ops/rotary_embedding.py
optimize Qwen2 5 vl vit with pta
no
we've tested on benchmark and it proves to be equal.
=> [0.7.3] optimize Qwen2.5 vl vit

.github/workflows/vllm_ascend_test.yaml, csrc/ops.h, csrc/torch_binding.cpp, pyproject.toml, requirements-dev.txt, requirements.txt, tests/compile/test_simple.py, tests/multicard/test_offline_inference_distributed.py, tests/singlecard/test_offline_inference.py, vllm_ascend/__init__.py, vllm_ascend/attention/attention_v1.py, vllm_ascend/ops/__init__.py, vllm_ascend/platform.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
This PR supports the access of vllm-acend to the piecewise_graph feature provided by the v1 engine.
1. register unifiled_ascend_attention_with_output for piecewise_graph to split graph.
2. support NPUGraph to accelerate kernel launch.
support npugraph to default， Users can disenable the npugraph feature by configuring enforce_eager.
This has corresponding requirements for the versions of torch_npu and CANN, and they need to support graph capture.
it turn to default
=> support aclgraph

tests/multicard/test_offline_inference_distributed.py, tests/ops/test_fused_moe.py, tests/singlecard/test_offline_inference.py, vllm_ascend/platform.py
Enforce eager mode in the V1 engine ahead of the upcoming CANN and torch_npu releases.
After this change, users will no longer need to manually set enforce_eager=True.
Test it with regular offline inference examples.
=> Quick Fix: Enforce eager mode in the V1 engine ahead of the upcoming CANN and torch_npu releases

.github/workflows/image_openeuler.yml, Dockerfile.openEuler
Provide users with openEuler-based vllm images for vllm v0.7.3
None
=> [v0.7.3] Add openEuler based container image

docs/source/developer_guide/versioning_policy.md, docs/source/faqs.md, vllm_ascend/envs.py, vllm_ascend/utils.py
Sometimes, user install a dev/editable version of vllm. In this case, we should make sure vllm-ascend works as well.
This PR add a new env `VLLM_VERSION`. It's used for developers who edit vllm. In this case, developers should set thie env to make sure which vllm version is installed and used.
=> [MISC] Make vllm version configurable

vllm_ascend/patch_outputs.py, vllm_ascend/platform.py
Fix CPU memory leak issue as is stated in https://github.com/vllm-project/vllm/pull/16472
No
With CI
=> [0.7.3] patch from_seq_group to clear finished seq in seq_id_to_seq_group

vllm_ascend/sample/ops/ascend_topk_topp_sampler.py, vllm_ascend/sample/ops/penalties.py, vllm_ascend/sample/sampler.py, vllm_ascend/sample/sampler_v1.py, vllm_ascend/worker/model_runner.py, vllm_ascend/worker/model_runner_v1.py
This PR optimizes apply_penalties & topKtopP implementation in both V0/V1 Engine by avoiding using torch.scatter and matrix indexing operations.
We verified the functionality of this PR using Qwen2.5-72B-Instruct. At a concurrency of 40 and with post-processing parameters set to "temperature": 0.3, "top_k": 100, "top_p": 0.9, "repetition_penalty": 1.01, the average decoding time was reduced from 300ms to 50ms.
=> [0.7.3] Optimize apply_penalties & topKtopP for both V0/V1 Engine

vllm_ascend/worker/model_runner_v1.py
set self.kv_cache_dtype to kv_cache_spec in model_runner_v1 in order to support kv_cache quant in v1
=> [ModelRunnerV1] Adapt kv_cache quant in v1.

vllm_ascend/__init__.py, vllm_ascend/patch/worker/patch_0_8_4/patch_tritonplaceholder.py
Fix triton placeholder patch period
=> [Bugfix] Fix triton placeholder patch period

vllm_ascend/lora/punica_wrapper/punica_npu.py, vllm_ascend/platform.py, vllm_ascend/worker/model_runner.py, vllm_ascend/worker/worker.py
According to this [RFC]( https://github.com/vllm-project/vllm-ascend/issues/396 ) and [this](https://github.com/vllm-project/vllm-ascend/issues/448), we pull request relavant code to support (1) Multi-LoRA and (2) Multi-LoRA Dynamic Serving.
LoRA reference is here: [LoRA reference](https://docs.vllm.ai/en/latest/features/lora.html)
Following openai HTTP apis will be supported:
/v1/load_lora_adapter
/v1/unload_lora_adapter
git clone [https://github.com/vllm-project/vllm.git](https://github.com/vllm-project/vllm.git)
cd vllm/examples/offline_inference/ && python3 multilora_inference.py
> [[Release]: vLLM Ascend v0.7.3 release checklist ](https://github.com/vllm-project/vllm-ascend/issues/644#issuecomment-2832225904)
=> Add LoRA & Multi-LoRA support for V0.7.3 dev by Cherry Pick

vllm_ascend/models/__init__.py, vllm_ascend/models/qwen2_5_vl.py, vllm_ascend/models/qwen2_vl.py
Optimize qwen2_vl and qwen2_5_vl.
no
Testing this PR on 1080p picture with tp=1, bs=1 on Qwen2-VL and Qwen2.5-VL, every fa op's during time lasting from 11ms to 9ms, got roughly 22% perf boost.
=> [0.7.3] optimize qwen2_vl and qwen2_5_vl

.github/workflows/vllm_ascend_test.yaml, tests/singlecard/spec_decode/e2e/conftest.py, tests/singlecard/spec_decode/e2e/test_mtp_correctness.py, tests/singlecard/spec_decode/test_dynamic_spec_decode.py, tests/singlecard/spec_decode/test_multi_step_worker.py, tests/singlecard/spec_decode/test_ngram_worker.py, tests/singlecard/spec_decode/test_spec_decode_worker.py, vllm_ascend/models/deepseek_mtp.py, vllm_ascend/patch/__init__.py, vllm_ascend/patch/worker/patch_0_8_4/patch_spec_decode_worker.py, vllm_ascend/patch/worker/patch_common/patch_multi_step_worker.py, vllm_ascend/patch/worker/patch_common/patch_spec_decode_worker.py, vllm_ascend/worker/draft_model_runner.py, vllm_ascend/worker/multi_step_runner.py
As custom deepseek modeling do some changes to support graph mode in https://github.com/vllm-project/vllm-ascend/pull/585, so i follow it to change custom deepseek_mtp modeling.
And some modifications for k>1 were not carried over by the https://github.com/vllm-project/vllm-ascend/pull/429, now i add it.
In order to better take care of the MTP feature in the vllm-ascend repository, I added cases related to graph mode(torchair), but i skip it since torchair can not correctly clean up memory in vllmrunner.
Also i add some case for MTP quantization weights, but test weight is not ready, so i skip it and i will open it when test quant weights is ready.
https://github.com/vllm-project/vllm-ascend/pull/648 did not completely fix the sample …
=> [MTP] follow custom deepseek modeling changes to support graph mode

docs/source/installation.md, docs/source/tutorials/single_npu.md, docs/source/user_guide/supported_models.md
Update installation and tutorial doc
NO
preview
=> Update installation and tutorial doc

vllm_ascend/attention/mla_v1.py
Replace torch function with reshape_and_cache fused op for better performance. The `reshape_and_cache` function wasn't working because it expected torch.int32 tensor, but a torch.int64 tensor was provided.
=> [Feature] Use reshape_and_cache fused op

vllm_ascend/ops/__init__.py, vllm_ascend/ops/common_fused_moe.py
vllm-ascend now only support moe for deepseek. We should add common moe support back
=> [Model] Support common fused moe ops for moe model, such as Qwen3Moe

examples/dp_offline/data_parallel.py, tests/multicard/test_pyhccl_distributed.py, tests/ops/test_rotary_embedding.py, tests/singlecard/test_camem.py, tests/singlecard/test_pyhccl.py, vllm_ascend/attention/attention.py, vllm_ascend/device_allocator/camem.py, vllm_ascend/distributed/device_communicators/pyhccl.py, vllm_ascend/ops/__init__.py, vllm_ascend/patch/worker/patch_0_8_4/patch_metrics.py, vllm_ascend/platform.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner.py, vllm_ascend/worker/pooling_model_runner.py
torch_npu 2.5.1 support autoload now. This patch does:
1. remove useless torch_npu import
2. replace `torch_npu.npu` to `torch.npu`.
=> [MISC] Clean up torch_npu

vllm_ascend/patch/__init__.py, vllm_ascend/patch/platform/patch_common/patch_distributed.py, vllm_ascend/platform.py
Platform should only contain the function that based from vllm. This PR move the unrelated function to the right place to make platform more clear.
=> [Platform] format platform to make it more clear

.github/actionlint.yaml, .github/workflows/accuracy_report.yaml, .github/workflows/accuracy_test.yaml, benchmarks/scripts/run_accuracy.py, docs/source/developer_guide/evaluation/index.md, docs/source/index.md
1. Provide accuracy test report for development branch release.
2. Models and datasets for accuracy test：
|                 Model              |              datasets              |
|---------------------------- | --------------------------- | 
| Qwen2.5-7B-Instruct        |  ceval-val, gsm8k, mmlu  |
| Qwen3-8B                        |  ceval-val, gsm8k, mmlu  |
| Llama-3.1-8B-Instruct      |  ceval-val, gsm8k, mmlu  |
| Qwen2.5-VL-7B-Instruct  |           mmmu_val             |
This PR will display the accuracy test report of the release versionin docs/source/developer_guide/accuracy_report。
Qwen2.5-7B-Instruct.md
Qwen3-8B.md
Llama-3.1-8B-Instruct.md
Qwen2.5-VL-7B-Instruct .md
=> [Test] Add accuracy test report workflow

vllm_ascend/quantization/quant_config.py
After discussed with MindStudio about the quantization model format, we decide to support another quant format which may used in new modelslim tool, in which case, `quantization_config` may be removed from the `config.json` file and `quant_model_description.json` will be used for quantization configuration.
=> [Feature] Add quant description file for new quant model generated by modelslim

.github/workflows/image_openeuler.yml, .github/workflows/image_ubuntu.yml, Dockerfile, Dockerfile.openEuler
Fix source code path to avoid reference error in docker image
fix https://github.com/vllm-project/vllm-ascend/issues/725
=> [Build][Bugfix] Fix source code path to avoid reference error

.github/workflows/image_openeuler.yml, .github/workflows/image_ubuntu.yml, Dockerfile, Dockerfile.openEuler
Backport and sync dockerfile change #726
This patch follow vLLM, move all source code into /vllm-workspace/, and keep /workspace as workdir.
[1] https://github.com/vllm-project/vllm/blob/main/docker/Dockerfile#L264C7-L264C23
[2] https://github.com/vllm-project/vllm/blob/main/docker/Dockerfile#L52
Closes: #725
=> [v0.7.3][Build][Bugfix] Fix source code path to avoid reference error

vllm_ascend/attention/attention.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/ops/rotary_embedding.py, vllm_ascend/platform.py, vllm_ascend/quantization/w8a8_dynamic.py, vllm_ascend/worker/model_runner.py
-->
1. Improve inference speed and usability for deepsek models with NPU graph mode.
2. Modify some codes to adapt to CANN 8.1.RC1.beta1.
3. Add a switch for NPU graph mode and its cache.
This PR provides an experimental configuration to enable NPU graph mode for Deepseek models. User can set additional_config={'enable_graph_mode': True} to try this feature. Note that this feature currently only supports for V0 engine.
This patch was tested with the newest torch_npu 2.5.1 (https://pypi.org/project/torch-npu/#files) and CANN 8.1.RC1.beta1 toolkit&nnal&kernels (https://www.hiascend.com/developer/download/community/result?module=cann) released in  25/30 April.
=> performance optimization, usability optimization and API compatibility adjustments for deepseek with npu graph mode

.github/workflows/vllm_ascend_test.yaml
Re-enable Speculative Decode test for vLLM v0.8.5
No
CI passed
=> Re-enable Speculative Decode test for vLLM v0.8.5

vllm_ascend/__init__.py, vllm_ascend/patch/__init__.py, vllm_ascend/patch/platform/__init__.py, vllm_ascend/patch/worker/__init__.py, vllm_ascend/patch/worker/patch_main/__init__.py, vllm_ascend/patch/worker/patch_main/patch_tritonplaceholder.py
Re-patch TritonPlaceholder on main to make CI happy
- Add triton patch back until https://github.com/vllm-project/vllm/pull/17446 resolved
- Move patch_main before patch_common to resolve minicpm triton import issue
- Add `0.8.5` and `0.8.5.post1` to make patch work on 0.8.5 all versions
Related:
- https://github.com/vllm-project/vllm-ascend/pull/704
- https://github.com/vllm-project/vllm-ascend/pull/690
No
All CI passed include main
=> Re-patch TritonPlaceholder on main to make CI happy

.github/workflows/vllm_ascend_test.yaml, Dockerfile, Dockerfile.openEuler, README.md, README.zh.md, docs/source/conf.py, docs/source/installation.md, docs/source/quick_start.md
Make CANN version bump separately from https://github.com/vllm-project/vllm-ascend/pull/708
- Upgrade CANN version to 8.1.rc1
- Add prefix to speed up download `m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10`
- Address tail sapce for Dockerfile.openEuler
- Add note for `/workspace` and `/vllm-workspace` as followup of https://github.com/vllm-project/vllm-ascend/pull/741
no
CI passed
Co-authored-by: MengqingCao <cmq0113@163.com>
=> Upgrade CANN version to 8.1.rc1

vllm_ascend/quantization/w8a8_dynamic.py
Optimize NPU memory usage. https://github.com/vllm-project/vllm-ascend/issues/723
vllm v0.8.4.rc2 and DeepSeek R1 can only support a model length of 16K. When attempting to run with a model length of 32K, an "Out of Memory" (OOM) error will occur.
No
CI passed
=> support 32K model len on deepseek r1 W8A8

vllm_ascend/quantization/w8a8_dynamic.py
The root cause of the bug is that numerical computations involving NaNs cannot eliminate them. We addressed it by using `masked_fill_` to eliminate NaNs while avoiding memory-wasting `torch.where` approach.
Not invovled.
This patch was tested with vllm v0.8.5 and vllm-ascend master. I run deepseek_v3 model with offline inference scripts (examples/dp_offline/run_dp.sh & data_parallel.py).
=> [Bugfix] fix accuracy problem for quantized deepseek models

tests/utils.py, vllm_ascend/ops/attention.py, vllm_ascend/worker/model_runner.py
Fix output tensor shape in vanilla_chunked_prefill function.
None.
Run offline inference on DeepSeek models.
=> [Bugfix] Fix output tensor shape in vanilla_chunked_prefill and update import paths for model_loader

tests/multicard/test_dynamic_npugraph_batchsize.py, vllm_ascend/worker/model_runner_v1.py
This PR add new function of : aclgraph_batch_size can dynamic adjust to different model; before this PR, the aclgraph_batch_sizes given from vllm to vllm-ascend always too large, and that may result in ERROR while running on different, with the information: "The resources are insufficient".
Now, with this PR, the code can dynamic adjust aclgraph_batch_sizes depend on the model hidden_layer_nums and parallel config, for example:
a. for Qwen2.5-7B, the aclgraph_batch_size length is 33 total;
b. for Qwen2.5-72B, the aclgraph_batch_size length is 11 total;
=> [WIP]Add Func: aclgraph_batch_size auto-adjust to different model

docs/requirements-docs.txt, docs/source/conf.py, docs/source/installation.md, docs/source/quick_start.md, docs/source/tutorials/multi_node.md, docs/source/tutorials/multi_npu.md, docs/source/tutorials/single_npu.md, docs/source/tutorials/single_npu_multimodal.md, docs/source/user_guide/suppoted_features.md, setup.py, vllm_ascend/utils.py, vllm_ascend/worker/worker.py, vllm_ascend/worker/worker_v1.py
Integrate MindIE Turbo into vLLM Ascend:
- Added support for MindIE Turbo in `setup.py` via an optional dependency under `extras_require`.
- Enhanced `try_register_lib` utility to log specific exceptions when MindIE Turbo is not found.
- Updated documentation to include instructions for installing MindIE Turbo:
- Improved documentation with links to Bisheng compiler optimization tutorials and MindIE Turbo documentation.
NO
CI passed
=> [Build][0.7.3] Integrate MindIE Turbo into vLLM Ascend

docs/requirements-docs.txt, docs/source/developer_guide/evaluation/accuracy_report/Llama-3.1-8B-Instruct.md, docs/source/developer_guide/evaluation/accuracy_report/Qwen2.5-7B-Instruct.md, docs/source/developer_guide/evaluation/accuracy_report/Qwen2.5-VL-7B-Instruct.md, docs/source/developer_guide/evaluation/accuracy_report/index.md, docs/source/developer_guide/evaluation/index.md
Add accuracy report for v0.7.3 release
Models and datasets for accuracy test：
|                 Model              |              datasets              |
|---------------------------- | --------------------------- | 
| Qwen2.5-7B-Instruct        |  ceval-val, gsm8k, mmlu  |
| Llama-3.1-8B-Instruct      |  ceval-val, gsm8k, mmlu  |
| Qwen2.5-VL-7B-Instruct  |           mmmu_val             |
This PR will display the accuracy test report of the v0.7.3 version in docs/source/developer_guide/accuracy_report。
Qwen2.5-7B-Instruct.md
Llama-3.1-8B-Instruct.md
Qwen2.5-VL-7B-Instruct .md
=> [v0.7.3][Doc] Add accuracy report

vllm_ascend/ops/rotary_embedding.py
This change ensures proper functionality for longer sequences by correctly invoking the _set_cos_sin_cache method with self as the first argument.
For example, with DeepSeek R1, if this change isn't made, the program will crash when the input sequence exceeds 4096.
=> [Bugfix] Correct method call for _set_cos_sin_cache

vllm_ascend/models/deepseek_v2.py, vllm_ascend/quantization/w8a8_dynamic.py
In the w8a8 quantization code of `fused_experts`, the output of almost every operator is assigned a new variable name. If we want to save NPU memory, we manually `del` these variables to end their lifecycle, which fills the code with `del` statements and looks inelegant. 
Therefore, I plan to names the output of most operators as `hidden_states`, thereby ending the lifecycle of the previous `hidden_states`.
No
=> [Perf] Optimize fused_experts quantization code to save npu memory

docs/source/developer_guide/versioning_policy.md
- Move Release Compatibility Matrix to top 
- Remove v0.7.x rc info because v0.7.3 final release alread published
- Rename vllm-ascend to vLLM Ascend
No
Preview
=> [Doc] Move Release Compatibility Matrix to top and remove v0.7.x rc info

.github/workflows/vllm_ascend_test.yaml
This PR aims to fix nightly ci [broken](https://github.com/vllm-project/vllm-ascend/actions/runs/14848150987)
We have a workflow containing multiple triggers:
- push events (to the default branch)
- pull requests (against the default branch)
- scheduled events
Our paths-filter action works great for the first two use-cases, detecting the context and base to compare against. However, it fails for scheduled events giving the error `This action requires 'base' input to be configured or 'repository.default_branch' to be set in the event payload.`
Any suggestions on how to handle this? There is two  alternative solutions:
1. For a scheduled build there is obviously no "base" to compare against as it's just a specific commit that is used, so we can specific it :
```
- name: Check for changes in …
```
=> [CI] Fix schedule trigger bug

.github/workflows/vllm_ascend_test.yaml, tests/singlecard/spec_decode/e2e/test_medusa_correctness.py, tests/singlecard/spec_decode/e2e/test_mlp_correctness.py, tests/singlecard/spec_decode/e2e/test_mtp_correctness.py, tests/singlecard/spec_decode/e2e/test_ngram_correctness.py
As https://github.com/vllm-project/vllm-ascend/pull/694 and https://github.com/vllm-project/vllm-ascend/pull/749 verify, Now, vllm-ascend main and vllm 0.8.5, spec UT is happy, but vllm-ascend main and vllm main, CI is fail.
I found the reason is a triton bug https://github.com/triton-lang/triton/issues/2266, but i I didn't figure it out that why the bug did not effect vllm-ascend main and vllm 0.8.5, maybe the usage of triton have changed when vllm 0.8.5 to latest main
As the bug describe, I changed the minimum block_size in UT from 8 to 16, and the modification is verified locally to be effective.
I modified some commented out cases to skipif form, which is more standardized.
None
CI
=> [CI/UT] fix spec ut in vllm-ascend main and vllm main

pytest.ini, vllm_ascend/worker/model_runner_v1.py
Fix V1 error found by [nightly_ci](https://github.com/vllm-project/vllm-ascend/actions/runs/14950004754/job/41998136610), broken by [[v1] Pass BlockTable and KVCacheSpec to AttentionMetadataBuilders #17483](https://github.com/vllm-project/vllm/pull/17483), make `InputBatch` parameter consistent with vllm.
CI passed
=> [Bugfix] Add max_num_batched_tokens to InputBatch to make main CI pass

.github/workflows/vllm_ascend_test.yaml, tests/multicard/test_offline_inference_distributed.py
Add deepseek-v2-lite test, part of #499
=> [CI] Add deepseek-v2-lite test

pytest.ini
For the [#17962](https://github.com/vllm-project/vllm/pull/17962?notification_referrer_id=NT_kwDOCexQHLUxNjM0MTM3OTEwNDoxNjY0ODE5NDg#event-17608938997) has merged, vllm openapi server can now launch normally on python==3.10, we re-enable the related tests
CI passed
=> [CI] Re-enable `vllm-empty/tests/benchmarks`

vllm_ascend/core/scheduler.py
This PR fixes two bugs in AscendScheduler:
1. When running with high concurrency, the length of running queue may exceed the limit of max_num_seqs
2. When some requests are prempted and recomputing is activated, the logic of computing new tokens is wrong.
=> [BugFix] Fix ascend scheduler bugs.

.github/workflows/codespell.yml, docs/source/developer_guide/versioning_policy.md, docs/source/faqs.md, docs/source/tutorials/multi_npu_quantization.md, docs/source/user_guide/release_notes.md, examples/disaggregated_prefill/dp_proxy.py, pyproject.toml, requirements-dev.txt, requirements.txt, vllm_ascend/distributed/kv_transfer/simple_buffer.py, vllm_ascend/utils.py
1. Fix format check error to make format.sh work
2. Add codespell check CI 
3. Add the missing required package for vllm-ascend.
=> [CI] add codespell CI and fix format.sh

docs/source/_templates/sections/header.html, docs/source/conf.py
Add the latest stable release url
=> [Misc][Doc] Add the latest stable release url

vllm_ascend/attention/attention.py, vllm_ascend/attention/attention_v1.py, vllm_ascend/ops/common_fused_moe.py, vllm_ascend/ops/fused_moe.py
moe support for llama4 and mllama4 in vllm-ascend
no
start sever:
python -m vllm.entrypoints.openai.api_server --model /data/nfs/benchmark/tokenizer/Llama-4-Scout-17B-16E-Instruct \
--max-num-seqs=256 \
--max-model-len=8192 \
--tensor-parallel-size=8 \
--block-size=128 \
--dtype bfloat16 \
--host=0.0.0.0 \
--port=8000 \
--gpu-memory-utilization=0.9 \
--trust-remote-code
client:
python online_server.py --model-path /data/nfs/benchmark/tokenizer/Llama-4-Scout-17B-16E-Instruct --image-path /data/nfs/w60040464/cherry_blossom.jpg --docker-ip 7.242.108.253 --served-port 8000 --text "what is the content of this image?"
result:
{'id': 'chatcmpl-2b709a5d2e1a4017991ec4ba8248686a', 'object': 'chat.completion', 'created': 1747056823, 'model': …
=> [Attention][Kernel]moe support for llama4 and mllama4

vllm_ascend/patch/worker/patch_common/__init__.py, vllm_ascend/patch/worker/patch_common/patch_utils.py
Patch torch.library.infer_schema for torch 2.5 backward compatibility
- Introduced a new module `patch_utils` under `vllm_ascend/patch/worker/patch_common/`.
- Added a function `ascend_direct_register_custom_op` to handle custom operator registration with backward compatibility for PyTorch < 2.7 (such as torch 2.5.1).
- Implemented type conversion logic for annotations to ensure compatibility across different PyTorch versions.
- Registered the function `ascend_direct_register_custom_op` to `utils.direct_register_custom_op`.
- Updated `__init__.py` to include `patch_utils` as the first import.
- Ensured `patch_utils` is available for use in other patch files and skipped isort checks for `patch_utils` import.
=> [CI] Patch torch.library.infer_schema for torch 2.5 backward compatibility

.github/workflows/vllm_ascend_doctest.yaml, docs/source/quick_start.md, tests/e2e/common.sh, tests/e2e/doctests/001-quickstart-test.sh, tests/e2e/run_doctests.sh
Add quickstart doctest
no
- CI passed
- Run `/vllm-ascend/tests/e2e/run_doctests.sh`
Related: https://github.com/vllm-project/vllm-ascend/issues/725
=> Add e2e test frame work and doctest

.github/actionlint.yaml, .github/workflows/vllm_ascend_test_pd.yaml
Add basic CI for PD disaggregation, and enable it when schedule and label with `module:pd`
- Updated `.github/actionlint.yaml` to add a new self-hosted runner configuration: `linux-arm64-npu-static-8`.
- Introduced a new GitHub Actions workflow `.github/workflows/vllm_ascend_test_pd.yaml` for PD disaggregation testing:
- Scheduled to run daily at 23:00 UTC and triggered by pull request label `module:pd`.
- Added steps for baisci installation and other steps will add in followup PR
Related: https://github.com/vllm-project/vllm-ascend/issues/841
No
- CI passed
- No trigger by default
- Trigger only if we tag with pd
=> [CI][1/N] Add basic ci for PD disaggregation

tests/ops/test_fused_moe.py, vllm_ascend/__init__.py, vllm_ascend/quantization/quant_config.py
make sure pytorch infer_schema check is patched before some case which using fused moe ops:
1. model register
2. quantization loading
3. fused moe ut
=> [CI] Patch torch.library.infer_schema for fused moe ops to fix CI

vllm_ascend/distributed/communicator.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/patch/platform/patch_common/patch_distributed.py, vllm_ascend/patch/worker/patch_common/__init__.py, vllm_ascend/patch/worker/patch_common/patch_distributed.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/quantization/w8a8_dynamic.py
1. This PR introduces native `all_to_all` communication operator to fix `allgather` bugs when dp_size > 1. Besides, it adds a naive implementation of force-load-balance when doing profile runs.
2. The operator `npu_dequant_swiglu_quant` only supports input hidden_states with dtype `torch.int32`. This tensor occupies space of  `global_bs * seq_len * topk * hidden_size`, which might be very large as `ep_size` grows. Therefore we need to disable this operator and use original `swiglu` && `quantize`.
No.
By performing offline inference:
=> [BugFix]add all2all when dp_size > 1 && downgrade npu_dequant_swiglu_quant

vllm_ascend/attention/attention_v1.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/worker/model_runner_v1.py
this PR fix CI failure broken by vllm.
1. add moe_config for fused_moe
2. adjust the change for kv cache group  from vllm. currently vllm-ascend doesn't support this feature.  this is just a quick fix for backward compatibility
fix: #872
=> [Bugfix][Model] Fix fusedmoe and make modelrunner_v1 compatible with latest vllm

pytest.ini
Ignore `vllm/tests/test_vllm_port.py` in ut as no related to vllm-ascend, and it is breaking CI
=> [CI/UT] Ignore vllm/tests/test_vllm_port.py

vllm_ascend/platform.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/utils.py
For online serving, "ascend" quantization method is not a choice natively, so we need to add "ascend" quantization method to quantization methods list and the user can enable quantization using "vllm serve --quantization ascend" command.
=> enable online serving quantization

vllm_ascend/patch/__init__.py, vllm_ascend/patch/patch_transformers_utils.py
Fix: https://github.com/vllm-project/vllm-ascend/issues/829
=> [Bugfix][0.7.3] Patch transformer utils

vllm_ascend/platform.py, vllm_ascend/worker/model_runner_v1.py
Fix the bugs when run deepseek model in engine v1.
No.
=> [BugFix] Fix chunked prefill bugs in engine v1

vllm_ascend/models/__init__.py, vllm_ascend/models/qwen3_moe.py, vllm_ascend/ops/fused_moe.py
Add support for Qwen3-MoE model.
no.
**TODO:**
=> [Model][0.7.3] Add support for Qwen3-MoE model

vllm_ascend/envs.py, vllm_ascend/models/__init__.py, vllm_ascend/models/qwen2_5_vl_without_padding.py
Add unpadded Qwen2.5-VL for verl scenario.
When using vllm-ascend for verl scenario, set `USE_OPTIMIZED_QWEN2_5_VL` (default `1`) to `0` to use unpadded Qwen2.5-VL to avoid errors.
=> [Bugfix][0.7.3] Add unpadded Qwen2.5-VL for verl scenario

vllm_ascend/device_allocator/camem.py, vllm_ascend/platform.py
Fix the bug of #703, where vllm wrong raised the ERROR : Failed to import vllm_ascend_C:No module named 'vllm_ascend.vllm_ascend_C'. The format for reporting import vllm_ascend_C failure is unified by warning ("Failed to import vllm_ascend_C:%s", e).
No
=> [bugfix] Improve log level and info for custom ops build

vllm_ascend/core/scheduler.py
Implement save kv cache logic for v1 disaggregated prefill in ascend scheduler
This PR adds support for saving kv cache in the ascend scheduler, which is part of the v1 disaggregated prefill design. The load functionality is not yet implemented.
=> [Feature] Impl v1 disaggregated prefill in ascend scheduler

vllm_ascend/attention/mla_v1.py, vllm_ascend/quantization/w8a8.py
Update attention nz and mla nz modules to improve TPOP 6ms performance
Convert W_UV and W_UK_T to NPU format in mla_v1.py
Convert layer.weight to NPU format in w8a8.py
=> update attention nz and mla nz(Improve TPOP 6ms performance)

vllm_ascend/attention/mla_v1.py
Currently, the implementation for MLA V1 pads q, k, v to `head_dim` 256 to conform to early MLA kernel. But the new MLA kernel supports `head_dim` that can't be devided by 128. Therefore we can remove those unnecessary paddings to boost the performance 
No.
=> [WIP][Perf]remove unnecessary padding before MLA V1 prefill

.github/workflows/vllm_ascend_test.yaml, requirements-dev.txt, tests/sample/test_rejection_sampler.py, tests/singlecard/spec_decode/e2e/test_v1_spec_decode.py, vllm_ascend/attention/attention_v1.py, vllm_ascend/patch/__init__.py, vllm_ascend/patch/worker/patch_common/__init__.py, vllm_ascend/patch/worker/patch_common/patch_eagle.py, vllm_ascend/sample/rejection_sampler.py, vllm_ascend/worker/model_runner_v1.py
Make spec decode support for V1 Engine
- Currently, Ascend does not support the triton kernel. PyTorch is used to rewrite the `rejection_sampler.py` triton kernel. However, PyTorch is not as good as Triton. Therefore, ascend c is used to implement the function in the future.
- Currently, spec decode supports only the ngram algorithm. The eagle algorithm needs to be further adapted.
Not change user facing.
test by `tests/singlecard/spec_decode/e2e/test_v1_spec_decode.py` and `tests/sample/test_rejection_sampler.py`, test base function of rejection sampler and e2e function of spec decode.
=> Spec decode support for V1 Engine

vllm_ascend/models/__init__.py, vllm_ascend/models/qwen3_moe.py
Tweak packed_modules_mapping to support W8A8 weights.
=> [Feature] Add CustomQwen3MoeForCausalLM model

vllm_ascend/ops/fused_moe.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/quantization/w8a8_dynamic.py
This PR fixes two accuracy bugs incurred by PR #819 when running deepseekv3 series models:
1. #819 adds `all_to_all` communication in quantized cases, but `all_gather` && `reduce_scatter` are removed in both of quantized and unquantized cases. When running unquantized deepseekv3 models with `ep_size == world_size`, the moe modules fail to communicate. Therefore, this PR adds `all_to_all` communication on unquantized situation to solve this accuracy issue.
2. Use `ep_size` rather than `dp_size` to decide whether to use `all_to_all` in moe.
No.
=> [BugFix] Fix accuracy bugs for unquantized deepseekv3 models

vllm_ascend/attention/attention_v1.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/worker/model_runner_v1.py
Adjust inputbatch to be compatible with latest vllm, as kvcache group feature has been redo in https://github.com/vllm-project/vllm/pull/18593
=> [Bugfix] Adjust inputbatch to be compatible with latest vllm

.github/Dockerfile.buildwheel, .github/actionlint.yaml, .github/workflows/actionlint.yml, .github/workflows/release_code.yml, .github/workflows/release_whl.yml, tools/actionlint.sh
This is a continuing work of #716.
This PR add workflow to build and release wheel, and also release source to PYPI.
We have 3 conditions to trigger the workflow:
1. PR to `main` and `*-dev`
2. push to `main` and `*-dev`
3. push tag with name of `v*`
Release to PYPI will only be done under condition 3. Under condition 1 and 2, it will generate .tar.gz and build .whl, upload to github artifacts but will not release.
update:
Will build .whl and upload to github artifacts with scheduled task.
No.
All triggered conditions are well tested with my fork repo.
=> add workflow to build and release wheel

vllm_ascend/ops/fused_moe.py
This PR fix accuracy issues incurred by codes that adapt to `FusedMoEParallelConfig` in vLLM 0.9.0 version. The `tp_size` used to split weights are wrongly passed. The root cause is that vLLM community and vLLM-Ascend are using different methods to decide whether to use Expert Parallel.
vLLM:
vLLM use a flag `enable_expert_parallel` to indicate whether to use EP and use the following codes to decide `ep_size`:
```
use_ep = (dp_size_ * tp_size_ > 1
and vllm_parallel_config.enable_expert_parallel)
dp_size = dp_size_
dp_rank = get_dp_group().rank_in_group if dp_size > 1 else 0
tp_size, tp_rank = flatten_tp_across_dp(dp_rank)
if not use_ep:
return FusedMoEParallelConfig(tp_size=tp_size,
tp_rank=tp_rank,
dp_size=dp_size,
dp_rank=dp_rank,
ep_size=1,
ep_rank=0,
use_ep=False)
assert use_ep …
```
=> [WIP][BugFix]Fix accuracy issues caused by wrong etp_size passed into FusedMoEParallelConfig when using vLLM 0.9.0

.github/workflows/vllm_ascend_test_pd.yaml, examples/disaggregated_prefill/disaggregated_prefill_offline.py, examples/disaggregated_prefill/p2p_disaggrefated_prefill_proxy.py, packages.txt, requirements-dev.txt, tests/e2e/pd_disaggreate/setup_pd.sh, tests/e2e/pd_disaggreate/test_pd_e2e.py, tests/e2e/run_disagg_pd.sh, vllm_ascend/distributed/kv_transfer/simple_pipe.py
=> [CI/UT][PD Disaggreate] Initialize PD Disaggreate UT

vllm_ascend/models/deepseek_v2.py, vllm_ascend/quantization/w8a8_dynamic.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner_v1.py
1. In previous PRs https://github.com/vllm-project/vllm-ascend/pull/580 https://github.com/vllm-project/vllm-ascend/pull/784, I saved GPU memory by promptly deleting unnecessary tensors. For tensors passed from upper-layer functions, I used a list container to transfer the parameter and then popped the tensor from the list within the inner function to achieve deletion. Recently, I discovered a better implementation in sglang—the `dispose_tensor` function and I recommend adopting this approach.
2. Dispose `hidden_states` and `residual` from the previous layer once they're no longer used.
3. Avoid to generate `self.inputs_embeds` in `ModelRunnerV1` in non-multimodal scenarios.
With the aforementioned optimizations, using the DeepSeek-R1-W8A8 model under the conditions of `TP=16` and …
=> [Perf] Refactor tensor disposal logic to reduce memory usage

tests/multicard/test_offline_inference_distributed.py, vllm_ascend/attention/mla_v1.py
Fix deepseek with v1, this error is introdeced by https://github.com/vllm-project/vllm-ascend/pull/945. and this pr fix the block table of mla
CI passed with new addedtest.
=> [Bugfix][V1] Fix deepseek with v1

vllm_ascend/models/qwen3.py
Because the EOL vLLM-v0.7.3 lacks this PR(https://github.com/vllm-project/vllm/pull/13166), while launching Qwen3+LoRA on vllm-ascend0.7.3, the error **"Qwen3ForCausalLM" object has no attribute "embedding modules**" will be raised.
We modify qwen3.py to support Qwen3+LoRA on vllm-ascend v0.7.3 instead.
No.
=> [V0.7.3][LoRA][Qwen3] Make v0.7.3 support Qwen3+LoRA

vllm_ascend/attention/mla_v1.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/platform.py, vllm_ascend/quantization/w8a8_dynamic.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker.py, vllm_ascend/worker/worker_v1.py
feat: support data parallel for deepseek
Yes, support dp for deepseek
```
export VLLM_ENABLE_MC2=0
export VLLM_USE_V1=1
export TASK_QUEUE_ENABLE=1
source /usr/local/Ascend/ascend-toolkit/set_env.sh
source /usr/local/Ascend/nnal/atb/set_env.sh
nohup python -m vllm.entrypoints.openai.api_server
--model=/path/to/DeepSeek-R1-W8A8 \
--quantization ascend \
--served-model-name auto \
--trust-remote-code \
--distributed-executor-backend=mp \
--port 8006 \
-tp=8 \
-dp=2 \
--max-num-seqs 24 \
--max-model-len 4096 \
--max-num-batched-tokens 4096 \
--block-size 128 \
-O 0 \
--no-enable-prefix-caching \
--additional-config
'{"torchair_graph_batch_sizes":[24],"expert_tensor_parallel_size":16,"ascend_scheduler_config":{},"enable_graph_mode":true}'
\
--gpu-memory-utilization 0.95 &> run.log &
disown
```
=> feat: support data parallel for deepseek

.github/workflows/accuracy_test.yaml, .github/workflows/nightly_benchmarks.yaml, .github/workflows/vllm_ascend_test_long_term.yaml, .github/workflows/vllm_ascend_test_pd.yaml
Adjust concurrency group for each npu workflow
- for pd and benchmarks share the static-08-01, so only one job can runs on
- other job one PR/schedule should have only 1 job runs
No
CI passed
=> Adjust concurrency group for each npu workflow

.github/workflows/nightly_benchmarks.yaml
This is for the benchmark iteration, which will change the benchmark scripts while checkouting each commit. So we need ensure the benchmark scripts always available.
=> [CI] Add workflow_dispatch and use main benchmarks directly

.github/workflows/vllm_ascend_test.yaml, docs/source/index.md, docs/source/user_guide/additional_config.md, examples/dp_offline/data_parallel.py, tests/long_term/spec_decode/e2e/conftest.py, tests/long_term/spec_decode/e2e/test_mtp_correctness.py, tests/multicard/test_dynamic_npugraph_batchsize.py, tests/multicard/test_offline_inference_distributed.py, tests/singlecard/test_aclgraph.py, tests/singlecard/test_ascend_config.py, vllm_ascend/ascend_config.py, vllm_ascend/attention/attention.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/core/schedule_config.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/platform.py, vllm_ascend/quantization/w8a8_dynamic.py, vllm_ascend/worker/cache_engine.py, vllm_ascend/worker/model_runner.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker.py, vllm_ascend/worker/worker_v1.py
More and more config options are added to additional_config. This PR provide a new AscendConfig to manage these config options by an easier way to make code cleaner and readable.
This PR also added the `additional_config` doc for users.
Added the test_ascend_config.py to make sure the new AscendConfig works as expect.
TODO: Add e2e test with torchair and deepseek once the CI resource is available.
=> [Misc] Refactor additional_config

tests/singlecard/test_scheduler.py, vllm_ascend/core/scheduler.py, vllm_ascend/worker/model_runner_v1.py
KV cache manger has been changed by https://github.com/vllm-project/vllm/commit/f8a1a2d108d290791ae1245b2ee309f38fdd7619
This PR adapt the change into vllm-ascend to make ci happy
=> [Misc] fix initialize_kv_cache

docs/source/user_guide/additional_config.md, tests/singlecard/test_ascend_config.py, vllm_ascend/ascend_config.py, vllm_ascend/platform.py, vllm_ascend/worker/model_runner_v1.py
Fix the ascend config check logic:
1. refactor check_ascend_config to make it clear:
1. torchair graph should not work with enforce_eager=True
2. aclgraph should not work with torchair graph
3. add refresh config for rlhf case
4. fix a typo in model runner
5. change expert_tensor_parallel_size default to 0 to keep the same as before
=> [BugFix] Fix ascend config check

vllm_ascend/ops/fused_moe.py
remove cumsum operator in MOE to improve performance
it should be tested on a case with mc2 operator and graph mode enabled
=> [Kernel] Remove cumsum in groupedmatmul

.github/workflows/vllm_ascend_test.yaml, examples/prompt_embedding_inference.py, tests/singlecard/test_prompt_embedding.py, tests/utils.py, vllm_ascend/worker/model_runner.py
- Adds support for passing prompt_embeds to LLM.generate as
```bash
llm.generate({"prompt_embeds": input_embeds}, sampling_params)
```
or
```bash
llm.generate(
[{"prompt_embeds": input_embeds} for input_embeds in inputs_embeds], sampling_params
)
```
- Add `prompt_embeds` to examples
and I have test with the example script in this pr, and the output seems looks good:
```bash
[Single Inference Output]
------------------------------
The capital of France is Paris. Paris is the largest city in France and is
------------------------------
Adding requests: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 3966.87it/s]
Processed prompts: …
```
=> [ModelRunner] Support embedding inputs

vllm_ascend/worker/worker.py, vllm_ascend/worker/worker_v1.py
When profiling, it is often necessary to disable the call stack to reduce profiling overhead, and adjust the profiler_level to level1 to obtain more detailed operator and communication information.
Therefore, it is recommended to modify the default profiling configuration.
No
No
=> [Misc] Adjust the default profiler configuration

docs/source/user_guide/additional_config.md, vllm_ascend/ascend_config.py, vllm_ascend/worker/model_runner.py, vllm_ascend/worker/model_runner_v1.py
View optimization in torchair (defaulted to on for Transpose with any of its axis being 1) prevents the weight Transpose to be fused with later GroupedMatmul, which decrease the performance of MoE layer when expert parallelism equals the total number of experts (e.g. EP256 for DSKv3). Add an option to solve this problem by disabling the optimization.
Controlled by `additional_config.torchair_graph_config.enable_view_optimize`, defaulted to `True`.
Tested on 1x16 910 node, with tailored 2 layer DSKv2.
=> Avoid unfused Transpose in DeepSeekV3 EP256 MoE layer

tests/singlecard/test_offline_inference.py, vllm_ascend/worker/model_runner_v1.py
The current vllm-ascend is not support the multimodal model in vllm-ascend v1 yet. So I change the `model_runner_v1.py` file with using MRoPE feature and so on to support this feature. It currently still not perfect since the Ascend operator is not support the `window/full attn` to reduce Memcpy operations, so it would out of memory if the input embedding is too large, so We can't use `self._profile_multimodal()` for profile since it use a big dummy input (i.e. images) as the multimodal input.
Fixes: https://github.com/vllm-project/vllm-ascend/issues/514
No, this feature not need change the user-facing
I test this offline using my machine 910B3 and my own fork, and it works well.
=> Add qwen2.5 vl multimodal feature for vllm-ascend v1

pyproject.toml, requirements-dev.txt, requirements.txt, tests/long_term/test_deepseek_v2_lite_tp2_accuracy.py, tests/singlecard/compile/test_simple.py, vllm_ascend/compilation/piecewise_backend.py
1. The dependency was introduced by https://github.com/vllm-project/vllm-ascend/pull/874
- Move numba/quart from requirements-dev to requirments
- Align pyproject.toml with requirements
2. This patch also fix deepseek accuracy baseline which https://github.com/vllm-project/vllm-ascend/pull/1118 was not addressed. According to https://huggingface.co/deepseek-ai/DeepSeek-V2-Lite the gsm8k is about `41.1`
3. This also sync the vLLM upstream changes: https://github.com/vllm-project/vllm/commit/eaa2e51088d4daf36d47e566ad90e812f80e91b8
No
CI passed
vllm ascend test (basic workflow)
vllm longterm test (spec decode)
Closes: https://github.com/vllm-project/vllm-ascend/issues/1120
=> [Build] Move numba/quart to requirments and update DS baseline and sync graph typo fix

vllm_ascend/envs.py
Set `ACL_OP_INIT_MODE` env var default to `0`, since vllm-ascend may have problems in some scenarios when setting it to `1`.
Plus, the guide https://github.com/vllm-project/vllm-ascend/issues/734 has also been updated.
=> [Bugfix] Set `ACL_OP_INIT_MODE` env var default to `0`

docs/source/community/contributors.md, docs/source/community/governance.md
As plus of https://github.com/vllm-project/vllm-ascend/pull/1070, this patch adds `Nominating and Removing Maintainers` section (reference some design from [PyTorch Governance](https://docs.pytorch.org/docs/stable/community/governance.html))
Below are key info about existing maintainers:
- Super active code and high quality reviewer [450+ PR reviewed](https://github.com/vllm-project/vllm-ascend/pulls?q=commenter%3Awangxiyuan).
- One of the top contributors, he also active contribute [50+ commits ](https://github.com/vllm-project/vllm-ascend/pulls?q=is%3Apr+is%3Aclosed+review%3Aapproved+author%3Awangxiyuan+) with good quality, he dares to [refactor the code](https://github.com/vllm-project/vllm-ascend/pulls?q=is%3Apr+author%3Awangxiyuan+is%3Aclosed+refactor), which also shows his deep …
=> Init vLLM Ascend maintainers info

.github/workflows/accuracy_report.yaml, .github/workflows/accuracy_test.yaml, benchmarks/scripts/run_accuracy.py, docs/source/developer_guide/evaluation/accuracy_report/index.md, docs/source/developer_guide/evaluation/index.md
Make accuarcy CI and report work
No
Manaully review
=> [CI] Make accuarcy CI and report work

docs/source/conf.py, docs/source/developer_guide/versioning_policy.md, docs/source/faqs.md, docs/source/user_guide/graph_mode.md, docs/source/user_guide/release_notes.md, vllm_ascend/worker/model_runner_v1.py
1. Add `__init__.py` for vllm_ascend/compilation to make sure it's a python module
2. Fix model runner bug to keep the same with vllm
3. Add release note for 0.9.0rc2
=> [Bugfix] add compilation/__init__.py to fix import error

vllm_ascend/attention/mla_v1.py, vllm_ascend/worker/model_runner_v1.py
The former PR https://github.com/vllm-project/vllm-ascend/pull/736 select the valid token inside the `input_ids` and `position_ids` breaks the necessary padding required by torchair. In this PR, we pending the pad logic after the multimodal part.
=> fix torchair execute issue on padding data, and mtp padding logic

.github/workflows/vllm_ascend_test_long_term.yaml
[CI] Skip test_v1_spec_decode.py::test_ngram_correctness to make longterm CI pass
Related: https://github.com/vllm-project/vllm-ascend/issues/1162
=> [CI] Skip test_v1_spec_decode.py::test_ngram_correctness to make longterm CI pass

.github/workflows/vllm_ascend_test.yaml, tests/singlecard/core/test_ascend_scheduler.py, tests/singlecard/core/test_ascend_scheduler_e2e.py, vllm_ascend/core/scheduler.py
This PR adds support for speculative decoding in AsecendScheduler.
Also inculde part of support for disaggregated prefill, full support will be merged in follow-up PR.
=> [Scheduler][MTP] Add support for speculative decoding in AsecendScheduler.

.github/workflows/nightly_benchmarks.yaml, benchmarks/tests/latency-tests.json, benchmarks/tests/serving-tests.json, benchmarks/tests/throughput-tests.json
- Add qwen2.5-7b-instruct test
- Add v1 test
=> [CI][Benchmark] Add new model and v1 test to perf benchmarks

docs/source/user_guide/additional_config.md, tests/singlecard/test_ascend_config.py, vllm_ascend/ascend_config.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/models/deepseek_v2.py
Move all vector operations to a secondary stream, with the expected overlaping being:
```
| q_rmsnorm |                  | kv_norm_rope_cache |       | q_rope |
| matmul W_DQ | matmul W_DKV | index | index |    matmul W_UQ     | split | matmul W_KV_T |
```
Currently, the `IndexByTensor` operators introduced by computation of `cos` and `sin` can't be offloaded to the secondary stream due to a known bug of graph fusion optimization pass. So we instead keep it in the main stream, only requires it be computed before `matmul W_UQ` to avoid hindering later overlapping. The problem may be solved by later optimization (#993), which hoists the computation of `cos` and `sin` up to the first layer.
Controlled by `torchair_graph_config.enable_multistream_mla`, defaulted to False.
Tested on 1x16 910 …
=> Support multistream of MLA vector operations

docs/source/community/contributors.md
Add @jianzs as vLLM Ascend maintainer
@jianzs
----
I would like to nominate Shoujian Zheng (@jianzs <https://github.com/jianzs>) as a maintainer, starting with my +1.
- He focuses on the code quality and good design with solid reviews in P/D disaggregation and DeepSeek improvement area about 30+ high quality review, such as [#issuecomment-2811764833](https://github.com/vllm-project/vllm-ascend/pull/429#issuecomment-2811764833), [#discussion_r2069927605](https://github.com/vllm-project/vllm-ascend/pull/694#discussion_r2069927605) and [#pullrequestreview-2820996674](https://github.com/vllm-project/vllm-ascend/pull/773#pullrequestreview-2820996674). This is the most important reason why I nominated him, because helping community developers complete PRs with high quality and continuously …
=> Add ShouJian Zheng (@jianzs) as vLLM Ascend maintainer

.github/workflows/vllm_ascend_test.yaml, docs/source/user_guide/additional_config.md, docs/source/user_guide/graph_mode.md, tests/conftest.py, tests/multicard/test_torchair_graph_mode.py
Add ut for torchair graph mode on DeepSeekV3
=> [CI/UT][Graph] Add ut for torchair graph mode

docs/source/user_guide/additional_config.md, tests/singlecard/test_chunked.py, vllm_ascend/ascend_config.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/worker/model_runner_v1.py
vllm-ascend support chunked prefill for MLA
=> vllm-ascend support chunked prefill

docs/source/user_guide/graph_mode.md
os.environ["VLLM_USE_V1"] must be assigned with str, not other type.
=> [Doc] fix VLLM_USE_V1 value in graph mode docs

vllm_ascend/attention/mla_v1.py, vllm_ascend/envs.py, vllm_ascend/models/deepseek_dbo.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/quantization/w8a8_dynamic.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
This PR is used for resolved [issue 1147](https://github.com/vllm-project/vllm-ascend/issues/1147)
1. Move fused_moe code into one file `fused_moe.py`.
2. Integrate branch conditions into function `get_fused_moe_state`.
1. This PR has removed the env `VLLM_ENABLE_MC2`, because I think this env is useless, we can make judgments based on the current scenario without this env, it will only increase complexity.
2. This PR has removed the env `USING_LCCL_COM`, because this env has already expired.
3. `additional_config.expert_tensor_parallel_size` has already expired, and now we also use parameter `enable_expert_parallel`, consistent with the vLLM.
=> [refactor] Refactoring AscendFusedMoE

vllm_ascend/attention/mla_v1.py, vllm_ascend/envs.py, vllm_ascend/models/deepseek_dbo.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/quantization/w8a8_dynamic.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
This PR is the cherry-pick of the PR https://github.com/vllm-project/vllm-ascend/pull/1229 which have already merged into the main branch. 
This PR is used for resolved [issue 1147](https://github.com/vllm-project/vllm-ascend/issues/1147)
1. Move fused_moe code into one file `fused_moe.py`.
2. Integrate branch conditions into function `get_fused_moe_state`.
1. This PR has removed the env `VLLM_ENABLE_MC2`, because I think this env is useless, we can make judgments based on the current scenario without this env, it will only increase complexity.
2. This PR has removed the env `USING_LCCL_COM`, because this env has already expired.
3. `additional_config.expert_tensor_parallel_size` has already expired, and now we also use parameter `enable_expert_parallel`, consistent with the vLLM.
CI …
=> [v0.9.1][refactor] Refactoring AscendFusedMoE (#1229)

vllm_ascend/envs.py, vllm_ascend/platform.py
Enable `ACL_OP_INIT_MODE=1` directly only when using V0 spec decode.
Cherry pick from https://github.com/vllm-project/vllm-ascend/pull/1258.
=> [Bugfix][Spec Decode][0.9.1] Enable `ACL_OP_INIT_MODE=1` directly only when using V0 spec decode

tests/e2e/singlecard/core/test_ascend_scheduler.py, tests/e2e/singlecard/test_scheduler.py, tests/ut/ops/test_expert_load_balancer.py, vllm_ascend/worker/model_runner_v1.py
refactor test_expert_load_balancer to keep the ut code style
This PR also fixed the break change from https://github.com/vllm-project/vllm/pull/16188/files#diff-e2942ece30a5c580437694ffb964bfc664b510c59244c08e5921b8f5cefb4280
This is just a quick fix. We'll support embedding on V1 later
Closes: https://github.com/vllm-project/vllm-ascend/issues/1299
=> [UT] refactor test_expert_load_balancer and fix broken CI

docs/source/index.md, docs/source/user_guide/quantization.md
Add user guide for quantization
No
Preview
=> Add user guide for quantization

examples/disaggregate_prefill_v1/README.md, examples/disaggregate_prefill_v1/gen_ranktable.sh, vllm_ascend/attention/mla_v1.py, vllm_ascend/envs.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/quantization/w8a8_dynamic.py
After the disaggregated PD merged, the kv cache on deepseek will become two piece of independent buffer for kv transfer or computation. However, the current kernel, namely `paged_attention_mla` can only accept k_cache as a single parameter, this make us have to concat these two piece of kv cache together before the attention thus incurs a memory peak inside the attention in eager mode. In this PR we introduce a `torch_npu.atb.npu_multi_head_latent_attention` for mla decode path, which will be used as default path for both eager mode and aclgraph after the related torch_npu is public available. Since its still a restrict package, we add `VLLM_ASCEND_MLA_PA` to control its usage. This flag will be removed in the future.
Yes, add a new flag named `VLLM_ASCEND_MLA_PA`, but it will be removed …
=> [0.9.1][Bugfix] fix oom issue in mla and enable mla_pa for deepseek mla decode

.github/workflows/vllm_ascend_test.yaml, tests/e2e/singlecard/test_guided_decoding.py
=> [CI] Update guided decoding ut

vllm_ascend/attention/mla_v1.py
Fix the issue of insufficient cached cosine and sine length in MLA's TorchAir graph mode, which causes accuracy deviation during long-sequence inference.
No.
We tested the accuracy of this patch with DeepSeek R1 e2e becnhmark serving, and get 83.33 sore for AIME2024 dataset with DP4TP4EP16 setting.
=> [bugfix] fix accuracy prolem for deepseek V3/R1 models with torchair graph in long sequence predictions

vllm_ascend/patch/__init__.py, vllm_ascend/patch/platform/patch_common/patch_distributed.py
`stateless_init_dp_group` in vllm works with non-cuda platform now. Remove this useless patch.
Which was introduced in vllm-ascend by https://github.com/vllm-project/vllm-ascend/commit/e74331a1ede31c69ec0b1b97bd407d38742caa9c (v0.8.4rc2)
vLLM upstream merged: https://github.com/vllm-project/vllm/commit/3e472d882a6071813bf6e683f5b9269e0d1d9678 (v0.8.0)
No
CI passed
=> [MISC] Remove useless patch

vllm_ascend/worker/model_runner_v1.py
Sync MRotaryEmbedding interface change to recover main CI (https://github.com/vllm-project/vllm/pull/19939)
No
CI passed
=> [Bugfix] Sync MRotaryEmbedding interface change to recover CI

.github/ISSUE_TEMPLATE/110-user-story.yml, README.md, README.zh.md, docs/source/developer_guide/feature_guide/patch.md, docs/source/user_guide/additional_config.md, docs/source/user_guide/graph_mode.md
1. Fix the typo
2. Fix 404 url
3. update graph mode and additional config user guide
=> [Doc] Fix doc typo

.github/workflows/vllm_ascend_test.yaml, tests/e2e/multicard/test_offline_inference_distributed.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/models/deepseek_dbo.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/ops/fused_moe.py
Communication performance optimization: replace allreduce with reduce_scatter+all_gather in MLA layer's TP group，to remove stridedsliced and all_gather in MOE layer. 
when tp > 1, It is enabled during the decode phase of the graph mode when enable_multistream_moe、MLA, use_v1, and MC2 are used.
According to the end-to-end RL inference test results, this PR can bring 3% gain in the decode stage.
**Before Improvement**
Profiling kernel_details
Evaluation
**After Improvement**
Profiling kernel_details
Evaluation
Users need to configure enable_multistream_moe=True
Add e2e test cases to cover code logic
=> adjusting the communication method in graph mode

vllm_ascend/worker/model_runner_v1.py
Reset all unused positions in `NPUModelRunner` to prevent out-of-bounds asserts in the `GatherV3` operator.
Currently, in [`get_splitfuse_attn_mask`](https://github.com/vllm-project/vllm-ascend/blob/main/vllm_ascend/attention/attention.py#L124), the `position` tensor may contain values that exceed the dimensions of the attention mask, triggering a `GatherV3` boundary check failure. These invalid indices originate from stale “dirty” entries left over in `position` due to padding logic in the ACL graph. Specifically, in [`_process_reqs`](https://github.com/vllm-project/vllm-ascend/blob/main/vllm_ascend/worker/model_runner_v1.py#L989), the variable `num_input_tokens` is always greater than or equal to `total_num_scheduled_tokens`, so any positions not explicitly cleared from a previous batch …
=> [Bugfix] Reset all unused positions to prevent out-of-bounds in GatherV3

tests/e2e/multicard/test_torchair_graph_mode.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/models/deepseek_v2.py
After #1094, decode might be executed with non-compiled mode, despite of `torchair_graph_config.enabled`, causing multistream mla to fail, which assumes torchair compiled mode for decode when `torchair_graph_config.enabled == True`.
Augment that assumption to fix this.
No.
Tested both offline, and by graph mode mla e2e testcase.
=> Handle with_prefill_across_dp for multistream mla

tests/multicard/test_model_qwen3_w4a8.py
Fixes qwen3 w4a8 test case failed due to `sampling_params` not fixed and `torch_npu` updated.
None.
=> [CI/UT][BugFix] Fix sampling params

vllm_ascend/ascend_config.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/quantization/w8a8.py, vllm_ascend/quantization/w8a8_dynamic.py, vllm_ascend/utils.py
1. add a switch for enabling NZ layout in weights
2. enable NZ for GMM
3. replace magic number of weights layout 
Users should set `enable_weight_nz_layout` to `true` in `--additional-config` when they wanna enable weights NZ layout.
1) CI passed. 
2) accuracy and performance comparison (only gsm8k-lite)
=> [v0.9.1][perf] add a switch for enabling NZ layout in weights and enable NZ for GMM.

vllm_ascend/worker/model_runner_v1.py
Reset all unused positions in `NPUModelRunner` to prevent out-of-bounds asserts in the `GatherV3` operator.
Currently, in [`get_splitfuse_attn_mask`](https://github.com/vllm-project/vllm-ascend/blob/main/vllm_ascend/attention/attention.py#L124), the `position` tensor may contain values that exceed the dimensions of the attention mask, triggering a `GatherV3` boundary check failure. These invalid indices originate from stale “dirty” entries left over in `position` due to padding logic in the ACL graph. Specifically, in [`_process_reqs`](https://github.com/vllm-project/vllm-ascend/blob/main/vllm_ascend/worker/model_runner_v1.py#L989), the variable `num_input_tokens` is always greater than or equal to `total_num_scheduled_tokens`, so any positions not explicitly cleared from a previous batch …
=> [v0.9.1][Bugfix] Reset all unused positions to prevent out-of-bounds in GatherV3

tests/ut/distributed/test_parallel_state.py
Add ut for parallel_state.py
N/A
python -m unittest  test_parallel_state.py
=> [CI/UT] Add ut for parallel_state.py

vllm_ascend/attention/attention_v1.py
This fix the shape of block_table which was introduced by hybrid kv groups several weeks ago.
Error will be raised when enable prefix-cache (eager or not) and Ascend Scheduler at the same time, just send two identical requests and it will reproduce.
=> [v0.9.1][Fix] Fix block table shape

vllm_ascend/attention/attention.py, vllm_ascend/attention/mla_v1.py
This PR removes the restriction that TP cannot be greater than 4 in torchair scenario, because current newest version of CANN has fixed this bug.
This PR is only for test now and will be merged until the next CANN version is released.
=> [BugFix] Fix the problem that torchair doesn't support tp > 4.

pyproject.toml, requirements.txt, vllm_ascend/models/deepseek_dbo.py, vllm_ascend/models/deepseek_v2.py
- Fix vLLM EPLB break https://github.com/vllm-project/vllm/commit/e9fd658a736a4d30f7a367c317506c87ad7f5359 by recovering load_weights back to [v0.9.1 version](https://github.com/vllm-project/vllm/commit/07b8fae219b1fff51ef115c38c44b51395be5bb5) temporarily.
- Fix transformers>=4.53.0 image processor break
Related: https://github.com/vllm-project/vllm-ascend/issues/1470
- Mirror torch_npu requirements to pyproject.toml
No
CI passed
=> [CI] Pin transformers<4.53.0 and fix EPLB load_weights to make CI passed

pyproject.toml, requirements.txt
Fix version conflict on transformers: `pip._vendor.pkg_resources.ContextualVersionConflict: (transformers 4.53.0 (/usr/local/python3.10.17/lib/python3.10/site-packages), Requirement.parse('transformers<4.53.0'), {'vllm-ascend'})`
Fix https://github.com/vllm-project/vllm-ascend/actions/runs/15933263325/job/44947231642
Fix broken build
CI passed with new existing test.
=> [CI/Build] Fix version conflict on transformers

vllm_ascend/models/pangu_moe.py, vllm_ascend/ops/common_fused_moe.py, vllm_ascend/ops/fused_moe.py
This PR introduces an expert rearrange algorithm for PanguProMoE model. Different from the original grouped topk, it filters out the top experts that are allocated more tokens. Therefore, we can load less experts when calculating gmm.
We have test this algorithm for PanguProMoE-72B on 300I Duo platform and 800I A2 platform. On 300I Duo platform, we find that `num_voted_experts` set to 5 achieves both good performance and accuracy. While on 800I A2, we still set it to 8 to use original pangu grouped topk.
No.
=> [PERF]support MERRouter

docs/source/user_guide/additional_config.md, vllm_ascend/attention/attention_v1.py, vllm_ascend/models/pangu_moe.py, vllm_ascend/platform.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/quantization/quantizer.py, vllm_ascend/quantization/w8a8.py, vllm_ascend/worker/model_runner_v1.py
=> support pangumoe w8a8c8 and docs

vllm_ascend/attention/attention_v1.py
This fix the shape of block_table which was introduced by hybrid kv groups several weeks ago.
Error will be raised when enable prefix-cache (eager or not) and Ascend Scheduler at the same time, just send two identical requests and it will reproduce.
v0.9.1: https://github.com/vllm-project/vllm-ascend/pull/1297
No
Test manually
=> [Core] Fix block table shape to make Prefix cache work with Ascend scheduler

vllm_ascend/models/deepseek_v2.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/quantization/w8a8_dynamic.py
This PR designs the shared expert multi-stream parallelism of w8a8-dynamic-quantized MoE stage in more detail to achieve better performance.
Current multi-stream parallel for shared experts are shown in following pic:
Performance change：
Before：
After：
=> [Perf][MoE] Improve shared experts multi-stream for w8a8 dynamic.

vllm_ascend/ascend_forward_context.py
fix bug `'AscendMetadata' object has no attribute 'num_actual_tokens'`.
=> [bugfix] fix ascend_forward_context with model_runner_v0

vllm_ascend/models/deepseek_mtp.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/quantization/quantizer.py
1. Support the inference of the Deepseekr1-w8a8-mtp model with statically-quantized shared_head in MTP layers.
Signed-off-by: curryliu <120010041@link.cuhk.edu.cn>
=> [Feature] Enable inference support for Deepseekr1-w8a8-MTP

examples/offline_embed.py
The `os.environ["VLLM_USE_MODELSCOPE"] = "True"` should be placed before module imports
if not 
```
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/xleoken/projects/vllm-ascend/examples/offline_embed.py", line 48, in <module>
model = LLM(model="Qwen/Qwen3-Embedding-0.6B", task="embed")
File "/usr/local/python3.10.17/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 243, in __init__
self.llm_engine = LLMEngine.from_engine_args(
File "/usr/local/python3.10.17/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 494, in from_engine_args
vllm_config = engine_args.create_engine_config(usage_context)
File "/usr/local/python3.10.17/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 1018, in …
```
=> [Bug] Fix wrong modescope env set order

tests/ut/quantization/test_w8a8.py, tests/ut/test_utils.py, vllm_ascend/quantization/w8a8.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner_v1.py
This pr supports w8a8 on 300I Duo platform. The main change is to use `npu_quant_grouped_matmul_dequant` to replace `npu_grouped_matmul`.
No.
offline inference on 310p runs normally.
=> [Quantization]300I Duo support w8a8 quantization

.github/workflows/doc_codespell.yaml, .github/workflows/vllm_ascend_test.yaml, docs/source/user_guide/additional_config.md, docs/source/user_guide/graph_mode.md, format.sh, tests/e2e/multicard/test_offline_inference_distributed.py, tests/e2e/multicard/test_torchair_graph_mode.py, tests/ut/ops/test_rotary_embedding.py, tests/ut/quantization/test_w8a8.py, tests/ut/test_ascend_config.py, tests/ut/test_platform.py, vllm_ascend/ascend_config.py, vllm_ascend/attention/attention_v1_torchair.py, vllm_ascend/models/pangu_moe.py, vllm_ascend/ops/rotary_embedding.py, vllm_ascend/patch/platform/patch_common/patch_distributed.py, vllm_ascend/platform.py, vllm_ascend/quantization/w8a8.py, vllm_ascend/worker/model_runner_v1.py
This PR supports torchair graph mode with non-mla backend on both 800IA2 and 300I Duo platforms. The main change is to add `attention_v1_torchair.py` to support specific attention related operations that are required by torchair. 
Before this PR, vLLM-Ascend only allows deepseek to use torchair. Now we can also use it with pangu. Besides, we add a support model list to control which type of models that can use torchair.
We have test it with PanguProMoE on both 800IA2 and 300I Duo platforms, and model generates answer normally.
=> [CORE]initial support for torchair with non-mla backend

vllm_ascend/models/deepseek_dbo.py, vllm_ascend/multistream/base.py, vllm_ascend/multistream/metadata.py
1. DBO model support EP parallel
2. optimize dual stream overlap
max tokens:32784 input_len:1024  bs 32 dp2tp8ep16 
before open dbo
TTFT: 4017ms
after open dbo
TTFT: 3017ms
None
=> [0.9.1]DBO support EP parallel and optimize dual stream overlap

vllm_ascend/worker/model_runner_v1.py
Since running on Altlas 300I Duo was initial supported after #1333 , this PR will disable the JIT compiler for the 310P and changed the data format to NZ for the weight in the vocabulary embedding and QKV projection layers, which help improving performance.
See #1563 
See https://github.com/vllm-project/vllm-ascend/pull/1591#issuecomment-3028352339
=> [Performance] Disable JIT and nd2nz to improve performance for Altlas 300I series

docs/source/developer_guide/contribution/testing.md, tests/ut/attention/test_attention_v1.py, tests/ut/base.py, tests/ut/distributed/test_parallel_state.py, tests/ut/ops/expert_map.json, tests/ut/ops/test_expert_load_balancer.py, tests/ut/patch/worker/patch_common/test_patch_distributed.py, tests/ut/patch/worker/patch_common/test_patch_sampler.py, tests/ut/quantization/test_quant_config.py, tests/ut/quantization/test_quantizer.py, tests/ut/quantization/test_w8a8.py, tests/ut/test_ascend_config.py, tests/ut/test_utils.py
Use Base test and cleanup all manaul patch code
- Cleanup EPLB config to avoid tmp test file
- Use BaseTest with global cache
- Add license
- Add a doc to setup unit test in local env 
No
CI passed
=> Add unit test local cpu guide and enable base testcase

tests/ut/worker/test_pooling_model_runner.py
Add ut for test_pooling_model_runner.py
python -m unittest  test_pooling_model_runner.py
- vLLM main: https://github.com/vllm-project/vllm/commit/2e610deb72dfc1e34b904d9b6b02c85eefa451d2
=> Add ut for test_pooling_model_runner.py

vllm_ascend/attention/attention_v1_torchair.py
This PR fixes a bug that is caused by max_num_tokens_across_dp calculation. In earlier version, we compute this by graph_pad_size plus max_num_tokens(actual). This will result in different max_num_tokens_across_dp across dp ranks. If padding related is required, this might cause a wrong padding.
No.
CI passed normally.
=> [BugFix] Fix max_num_tokens_across_dp calculation bugs in attention_v1_torchair

.github/workflows/vllm_ascend_test.yaml
Fix mypy check in CI: https://github.com/vllm-project/vllm-ascend/actions/runs/16115919385/job/45469646509?pr=1654
Mypy failed due to the greater numpy version. We need to pin `numpy=1.26.4` in vllm-ascend
- vLLM main: https://github.com/vllm-project/vllm/commit/923147b5e8551887fd64a0fc242c361d5216e1d7
=> [CI] Fix mypy check in CI

tests/ut/test_utils.py, vllm_ascend/envs.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
1、Sometimes loading torchair cache will fail because of the floating of npu memory, so this pr add a new cache to save the old kv cache bytes to avoid the possible crash while loading the torchair graph cache.
2、When caching is enabled and does not exist, the first compilation introduces the overhead of Dynamo Gurad. So in this case, we will compile them directly twice to skip them (This will bring 3-4 ms of tpot optimization)
Add a new env `VLLM_ASCEND_KV_CACHE_MEGABYTES_FLOATING_TOLERANCE` to control kv cache floating tolerance
- vLLM main: https://github.com/vllm-project/vllm/commit/1fd471e957526a34a0cb4b60d2e830cd6ca79fdc
=> feat: add kv cache memory cache and skip dynamo guard

vllm_ascend/distributed/llmdatadist_c_mgr_connector.py
The Implementation of current `LLMDataDistCMgrConnector` connect and pull kv in synchronous manager which may brought drop of latency to the decode task if the consumer node consistently receiving tasks pushed from the remote producer node. The omni_infer launches llmdatadist's `pull_kv` method  in another thread which brings the better overlap between pull kv cache and model run. This implementation gains better performance against the synchronous path. 
In this PR, we bring this asynchronous philosophy into the vllm-ascend, and launch the `link`, `pull_kv` and `request_finished` tasks also in async managers.
No any user interface change.
=> [0.9.1][Perf] Launch load kv task asynchronously with thread pool.

.github/workflows/vllm_ascend_test.yaml, tests/multicard/test_offline_inference_distributed.py, vllm_ascend/models/deepseek_dbo.py, vllm_ascend/multistream/ms_split.py, vllm_ascend/worker/model_runner_v1.py
1. Quant parameters has been modified but DBO file didn't match it. 
2. remove useless init code, mostly reuse v2 init code.
3. add DBO e2e case and remove case skip.
None
‘tests/multicard/test_offline_inference_distributed.py’
=> [V0.9.1][BugFix] Fix load weight error and add new e2e case

.github/Dockerfile.buildwheel, .github/workflows/release_whl.yml
- Fixes https://github.com/vllm-project/vllm-ascend/issues/1533
1. Run the image
```
docker run \
--name cann_container \
--device /dev/davinci6 \
--device /dev/davinci_manager \
--device /dev/devmm_svm \
--device /dev/hisi_hdc \
-v /usr/local/dcmi:/usr/local/dcmi \
-v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
-v /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/ \
-v /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info \
-v /etc/ascend_install.info:/etc/ascend_install.info \
-it  quay.io/ascend/cann:8.1.rc1-910b-openeuler22.03-py3.11 bash
```
2. Install package
torch=2.5.1
torch-npu=2.5.1.post1.dev20250619 
vllm=0.9.1
vllm-ascend=vllm_ascend-0.1.dev1+g02ac443-cp311-cp311-manylinux2014_aarch64.manylinux_2_17_aarch64.whl
Artifact download URL: …
=> Fix wheel glibc version incompatibility

vllm_ascend/attention/mla_v1.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/quantization/w8a8_dynamic.py, vllm_ascend/worker/model_runner_v1.py
=> add mc2 mask

examples/offline_inference_npu_v0.py, examples/offline_inference_npu_v1.py
Improve
- Keep the same file name format as v1, `offline_inference_npu_v0.py`, `offline_inference_npu_v1.py`
- Use `VLLM_USE_V1` = 0/1 clearly in py scripts
- Fix some run errors in `offline_inference_npu_v1.py`, e.g. `deepseekv3-lite-base-latest` not exists in modescope or hf.
No.
- vLLM main: https://github.com/vllm-project/vllm/commit/baed180aa00314897b37b4b0af65adeba06f3d77
=> feat: Improve the offline_inference npu v0/v1 scripts

vllm_ascend/models/__init__.py, vllm_ascend/models/qwen3.py, vllm_ascend/ops/layernorm.py, vllm_ascend/quantization/w8a8.py
Optimizes the performance of the Qwen3 quantization model by registering a custom model and adding the AddRmsNormQuant operation. Subsequent PRs will focus on performance optimizations based on this custom model.
No.
=> [V0.9.1] Use AddRmsNormQuant ops in the custom model to optimize Qwen3's performance

examples/offline_inference_npu_v1.py, vllm_ascend/distributed/communication_op.py, vllm_ascend/ops/fused_moe.py
In some cases, `dist._functional_collectives.reduce_scatter_tensor` can cause its input tensor not to be released immediately after the current layer ends. Instead, it will only be released when the GPU memory usage of the current process reaches a certain threshold (approximately every 15 layers each time).
**Before Fix**
**After Fix**
No
- vLLM main: https://github.com/vllm-project/vllm/commit/9ff2af6d2ba1757c6e59fe803225a73e61fe526f
=> [Bugfix] Fix memory-leak caused by dist._functional_collectives.reduce_scatter_tensor

.github/format_pr_body.sh, .github/workflows/format_pr_body.yaml, docs/source/conf.py
Use ci_vllm_version when recording vllm commit
Followup on https://github.com/vllm-project/vllm-ascend/pull/1623
No
- Test mannually.
$ python3 docs/source/conf.py | jq .ci_vllm_version | tr -d '"'
v0.9.2
- Test on my local repo: https://github.com/Yikun/vllm-ascend/pull/35
- vLLM main: https://github.com/vllm-project/vllm/commit/49e8c7ea256bd48a36391b5bc72212af39278b67
=> Use ci_vllm_version when recording vLLM commit

tests/ut/attention/test_attention_mask.py, vllm_ascend/attention/attention.py, vllm_ascend/attention/attention_mask.py
If a small batch of short requests is sent first, forming a chunk with a length <128, it will corrupt the `attn_mask_cache`, causing subsequent requests that do not form a chunk to have accuracy issues.
The root cause of this problem is the use of in-place multiplication. Modifying it to use out-of-place multiplication will resolve the accuracy problem.
No
Yes.
- vLLM main: https://github.com/vllm-project/vllm/commit/ad6c2e1a0b56c29065c7d70ff2e736e4f2fb03af
=> [Bugfix] Fix accuracy problem caused by mask pollution

tests/singlecard/test_aclgraph.py, vllm_ascend/platform.py
Currently, Ray is not compatible with ACL Graph, so we need to fall back to eager mode when using the Ray backend.
=> [Fix] Add warning for incompatible Ray backend with ACL Graph mode

tests/e2e/multicard/test_pipeline_parallel.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
This patch supports pipeline parallel in V1 Engine
Yes, users can run PP in V1
Manully test
- vLLM main: https://github.com/vllm-project/vllm/commit/31d5c1797f320b2f407c893673330b3a8766ae47
=> Support pipeline parallel in V1 Engine

tests/singlecard/test_aclgraph.py, vllm_ascend/attention/attention_v1.py, vllm_ascend/compilation/piecewise_backend.py
Rectified the performance regression wherein the FIA kernel underperformed the PA kernel by enabling dynamic updates of PA parameters during graph replay.
=> [0.9.1][2/N][Feat] Restore paged attention kernel in Full Graph for performence

README.md, README.zh.md, docs/source/community/contributors.md, docs/source/community/versioning_policy.md, docs/source/conf.py, docs/source/faqs.md, docs/source/installation.md, docs/source/user_guide/release_notes.md
Add release note for 0.9.2rc1, we'll release soon
- vLLM main: https://github.com/vllm-project/vllm/commit/7bd4c37ae7c6f2223c1a031bbdd2e3435d53da94
=> [Release] Add 0.9.2rc1 release note

docs/source/developer_guide/contribution/testing.md, docs/source/tutorials/index.md, docs/source/tutorials/multi_node.md, docs/source/tutorials/multi_npu_quantization.md, docs/source/tutorials/multi_npu_qwen3_moe.md, docs/source/tutorials/single_node_300i.md, docs/source/tutorials/single_npu.md, docs/source/tutorials/single_npu_audio.md, docs/source/tutorials/single_npu_multimodal.md, docs/source/tutorials/single_npu_qwen3_embedding.md, docs/source/user_guide/feature_guide/graph_mode.md, docs/source/user_guide/feature_guide/sleep_mode.md
1. Add the tutorials for qwen3-embedding-8b
2. Remove VLLM_USE_V1=1  in docs, it's useless any more from 0.9.2
- vLLM main: https://github.com/vllm-project/vllm/commit/5923ab9524e32006ffb9354c5340b6988a45fe3e
=> [Doc] Add qwen3 embedding 8b guide

vllm_ascend/models/deepseek_dbo.py
When enabling both DBO and MoE multistream of deepseek model, there exists problem. This PR fixes this situation and add e2e ut test for this scenario.
=> [BugFix] Fix the bug when enabling both DBO and MoE multistream of deepseek.

vllm_ascend/attention/mla_v1.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/utils.py
This PR port the optimization in PR #1353 to v0.9.1-dev.
=> [0.9.1][Perf] Port MLA multistream optimazition and prefetch to v0.9.1

tests/singlecard/ops/test_rotary_embedding.py, vllm_ascend/models/qwen3.py, vllm_ascend/ops/rotary_embedding.py
use npu_apply_rotary_pos_emb when head_size is 128 and is noex_style
Optimize rope by extracting index_select from layers into model, which can reduce (layer_num -1) * 2 Gather ops in each prefill/decode stage.
NA
NA
=> [V0.9.1] optimize rope in qwen3

.github/workflows/accuracy_test.yaml
Resolve vllm-ascend version
- vLLM main: https://github.com/vllm-project/vllm/commit/66f6fbd393721c98440436ab067304ac4331219c
=> [Test] Resolve vllm-ascend version

vllm_ascend/distributed/llmdatadist_c_mgr_connector.py
Torchair set the `HCCL_DETERMINISTIC` by default, and it will incur error when CacheManagerConnector trying to pullkv in another thread. This PR setting this environment variable ahead of the pullkv process. Makes the pullkv and torchair happy at same time.
No change
ci test
=> [v0.9.1] fix async pullkv determin

tests/multicard/test_offline_inference_distributed.py, vllm_ascend/envs.py, vllm_ascend/models/qwen3.py
Support FlashComm v2 in qwen3, which can reduce latency at prefill stage. set **VLLM_ENABLE_FC=1** and use **eager mode** to enbale this feature. 
**Note**: Enabling FlashComm in decoding stage may cause increased latency,  so it is recommended to use disaggregated prefilling and enbale this feature in the prefill instance only!!!
NA
NA
=> [V0.9.1] add support for flashcomm2 in qwen3

.github/format_pr_body.sh
Remove redundant empty lines in commit msg
No
test locally: https://github.com/Yikun/vllm-ascend/pull/48
- vLLM main: https://github.com/vllm-project/vllm/commit/d0dc4cfca48c2734da18ec42d6bba1346cbfc400
=> Remove redundant empty lines in commit msg

.github/workflows/image_310p_openeuler.yml, .github/workflows/image_310p_ubuntu.yml, .github/workflows/image_a3_openeuler.yml, .github/workflows/image_a3_ubuntu.yml, .github/workflows/image_openeuler.yml, .github/workflows/image_ubuntu.yml, Dockerfile.a3, Dockerfile.a3.openEuler, vllm_ascend/envs.py
Add support for Ascend A3 and remove latest tag
User can run vLLM on Altlas A3 series
CI passed with:
- remove latest tag test: https://github.com/wxsIcey/wxs-vllm-ascend/actions/runs/16267635040/job/45926924765
- E2E image build for A3
- CI test on A3 with e2e test and longterm test
- Unit test missing because need a real A3 hardware to have a test
Closes: https://github.com/vllm-project/vllm-ascend/issues/1696
- vLLM main: https://github.com/vllm-project/vllm/commit/d0dc4cfca48c2734da18ec42d6bba1346cbfc400
=> [Platform] Add support for Altlas A3 series

vllm_ascend/ops/fused_moe.py
Excessive padding for long input sequences can now lead to out‑of‑memory errors. This PR optimizes the padding logic in `fused_moe.py` to eliminate unnecessary padding.
No.
To reproduce the issue, launch the DeepSeek model server using both data‑parallel (DP) and tensor‑parallel (TP) strategies, then submit a request with a long input sequence.
=> [0.9.1][Fix] Fix DeepSeek OOM issue in extreme `--gpu-memory-utilization` scenario

examples/disaggregated_prefill/disaggregated_prefill_offline.py, examples/disaggregated_prefill/dp_proxy.py, examples/disaggregated_prefill/p2p_disaggrefated_prefill_proxy.py, examples/eplb/eplb_strategy.py, examples/offline_data_parallel.py, examples/offline_disaggregated_prefill_npu.py, examples/offline_distributed_inference_npu.py, examples/offline_dualbatch_overlap_npu.py, examples/offline_embed.py, examples/offline_inference_audio_language.py, examples/offline_inference_npu.py, examples/offline_inference_npu_tp2.py, examples/offline_inference_sleep_mode_npu.py, examples/offline_multi_step_custom_ops.py, examples/prompt_embedding_inference.py
Add `__main__` guard to all offline examples.
- vLLM main: https://github.com/vllm-project/vllm/commit/76b494444fd864ffc53a623420668d1865c804b9
=> [Misc][V0 Deprecation] Add `__main__` guard to all offline examples

vllm_ascend/models/qwen2.py
Fix missing attn_state attribute bug in engine_v0 scenario when enabling Flashcomm_v1.
No.
=> [BugFix] Fix flashcomm_v1 when engine v0

vllm_ascend/models/qwen2.py, vllm_ascend/models/qwen3.py, vllm_ascend/ops/rotary_embedding.py
Optimize rope by extracting index_select from layers into model, which can reduce (layer_num -1) * 2 Gather ops in each prefill/decode stage.
No
Pass cos and sin and set skip_index_select=True to enable this optimization. As shown in the following code :
`q, k = self.rotary_emb(positions, q, k, cos=cos, sin=sin, skip_index_select=True)`
**Performance results:**
**origin:**
Successful requests:                     400
Benchmark duration (s):                  243.10
Total input tokens:                      1200000
Total generated tokens:                  60000
Request throughput (req/s):              1.65
Output token throughput (tok/s):         246.81
Total Token throughput (tok/s):          5183.02
**optimized:**
Successful requests:                     400
Benchmark duration (s): …
=> [0.9.1]optmize rope in qwen2

tests/e2e/singlecard/test_aclgraph.py, tests/ut/base.py, tests/ut/conftest.py, tests/ut/ops/test_activation.py, tests/ut/test_utils.py, vllm_ascend/platform.py, vllm_ascend/utils.py
We'll refator `CustomOp` in vllm-ascend from this pr on. 
Use function `CustomOp.register_oot` to achieve the customop registery, taking `AscendQuickGELU` as an example:
```python
from vllm_ascend.ops.activation import AscendQuickGELU
CustomOp.register_oot(_decorated_op_cls=AscendQuickGELU, name="QuickGELU")
```
This is a quick adapt for `CustomOp.register_oot` mechanism from vllm 0.9.2. For further step, we can remove inherit from `QuickGELU` can write our own `QuickGELU` at all.
Part of https://github.com/vllm-project/vllm-ascend/pull/1647
- vLLM main: https://github.com/vllm-project/vllm/commit/8dfb45ca3379b3a789ec529af4bf725daa07f10d
=> [1/N][CustomOp] Register activation customop instead of overwrite forward_oot

tests/ut/test_utils.py, vllm_ascend/utils.py
maybe fixes [#1728](https://github.com/vllm-project/vllm-ascend/issues/1728#issuecomment-3065083433)
No.
Test Qwen3-32B tp=4 with: 
```bash
vllm serve --port 1234 Qwen/Qwen3-32B \
--served-model-name Qwen3-32B \
--tensor-parallel-size 4 \
--swap-space 16 \
--max-model-len 6000 \
--load-format dummy \
--disable-log-stats \
--disable-log-requests \
```
Request batch_size=128 input/output token=1024
**In 0.9.2rc1**
```text
=====================================================
Total TPS with    prefill(tokens/s)         : 785.1395
Total TPS without prefill                   : 846.6809
Mean TPS with    prefill                    : 6.1339
Mean TPS without prefill                    : 6.6147
=====================================================
Mean TTFT(ms)                               : …
```
=> [Bugfix]Fix the performance gap between 0.9.2rc1 and 0.9.1

vllm_ascend/models/__init__.py, vllm_ascend/models/deepseek_v2.py, vllm_ascend/models/deepseek_v3.py
Before patch, we can see `vllm_ascend.models.deepseek_v2:CustomDeepseekV3ForCausalLM`, it seems not friendly format.
```
WARNING 07-14 23:57:34 [registry.py:413] Model architecture DeepseekV2ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV2ForCausalLM.
WARNING 07-14 23:57:34 [registry.py:413] Model architecture DeepseekV3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV3ForCausalLM.
WARNING 07-14 23:57:34 [registry.py:413] Model architecture Qwen3MoeForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3_moe:CustomQwen3MoeForCausalLM.
```
No.
Local Test.
- …
=> Move deepseek_v3 from deepseek_v2.py

.github/Dockerfile.buildwheel, .github/workflows/release_whl.yml
- Fixes https://github.com/vllm-project/vllm-ascend/issues/1533
Backported: https://github.com/vllm-project/vllm-ascend/pull/1582
=> [0.9.1] Fix wheel glibc version incompatibility

examples/offline_data_parallel.py, tests/e2e/multicard/test_data_parallel.py
Fix e2e data parallel test: add resource release code and give more time to engine to pause their processing loops before exiting.
No
- vLLM main: https://github.com/vllm-project/vllm/commit/5895afd78047614a037cac1fc4634825c749fd59
=> Fix e2e data parallel test: add resource release code

vllm_ascend/attention/mla_v1.py
This PR removes NZ transformation of weights of kv_b_proj. This is because we find that this matmul weight is not quantized and will fall back to ND calculation in runtime (because currently float bmm nz is not supported in torchair graph), which causes two redundant transData operations (trans weight from NZ back to ND). Removing these two operations will provide an optimization of about 40us per layer.
=> [0.9.1][Perf]Remove NZ of kv_b_proj in Deepseek MLA.

pyproject.toml, requirements.txt, vllm_ascend/ops/common_fused_moe.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/npu_input_batch.py, vllm_ascend/worker/worker_v1.py
1. vLLM commit https://github.com/vllm-project/vllm/commit/45badd05d04254eb75c48cee7b1d454a80de2165 changed the pooling check logic which  broken vLLM Ascend.
2. vLLM commit https://github.com/vllm-project/vllm/commit/3e04107d97aeb6360fcfb684665b66c94135079b requires higher version of transformers. The transformers version bug has been fixed by https://github.com/vllm-project/vllm/commit/e936e401debe7fba64d6462666d7dc632bc76357. We can safe to remove the version limit now.
3. vLLM commit https://github.com/vllm-project/vllm/commit/217937221b6845913502371aba554a3357fbccfb added a new input `enable_eplb` for FusedMoe Ops
This PR fix the broken CI.
- vLLM main: https://github.com/vllm-project/vllm/commit/6a971ed692974b3d6309d556b15c8cc726b091f9
=> [CI] Fix broken CI

tests/ut/attention/test_attention_v1.py, vllm_ascend/attention/attention_v1.py, vllm_ascend/attention/attention_v1_torchair.py, vllm_ascend/attention/mla_v1.py
vLLM commit https://github.com/vllm-project/vllm/commit/752c6ade2e0f38a26cdaaed6ffae8f72781e2d61 removed `blocksparse_params` for attention backend. This PR does the same change to make CI happy.
- vLLM main: https://github.com/vllm-project/vllm/commit/9499e26e2ae18826bcda99ae7e0883268cde03db
=> [CI] Make AttentionBackend interface compatible to fix broken CI

tests/ut/test_platform.py, vllm_ascend/platform.py, vllm_ascend/torchair/torchair_worker.py, vllm_ascend/worker/worker_v1.py
There is a lot torchair specified logic in common code. It results hard code maintenance. We will create a new torchair module to launch torchair related logic there. I plan to add 4 PR.
1. Refactor worker (this PR)
- create torchair module and move torchair related code in worker to the new module
3. Refactor utils
4. Refactor model_runner
5. Refactor attention
- vLLM main: https://github.com/vllm-project/vllm/commit/8188196a1c8af26134d8e366ebe564c18fb95379
=> [1/4][Refactor] Refactor torchair worker

vllm_ascend/distributed/parallel_state.py, vllm_ascend/worker/worker.py, vllm_ascend/worker/worker_v1.py
This pr fixes the bug, which throw an error `self.cpu_group is None`. This is mainly caused by the wrong group ranks of process groups maintained in vllm-ascend. We need to take external dp size into account to ensure it work fine with `external_launch` mode.
Related fixes: https://github.com/vllm-project/vllm-ascend/issues/1396 https://github.com/vllm-project/vllm-ascend/issues/1154
=> [0.9.1][Dist][Bugfix] Fix mc2 process group to resolve self.cpu_group is None

.github/workflows/vllm_ascend_test.yaml
Pin vllm version to v0.9.1 to make mypy check passed
No
Lint ci passed
=> [0.9.1][CI] Pin vllm version to v0.9.1 to make mypy check passed

tests/ut/core/test_schedule_config.py
What this PR does / why we need it?
According to issue https://github.com/vllm-project/vllm-ascend/issues/1298 , this pull request adds unit test code for schedule_config.py.
Does this PR introduce any user-facing change?
No
How was this patch tested?
- vLLM main: https://github.com/vllm-project/vllm/commit/8d0a01a5f2b53794e4bc6b734d7b63cb8a9b7d7d
=> [Test] Add unit test for schedule_config.py

tests/e2e/multicard/test_offline_inference_distributed.py, vllm_ascend/models/__init__.py, vllm_ascend/models/qwen3.py, vllm_ascend/ops/layernorm.py, vllm_ascend/quantization/w8a8.py
Optimizes the performance of the Qwen3 quantization model by registering a custom model and adding the AddRmsNormQuant operation. Subsequent PRs will focus on performance optimizations based on this custom model.
No.
- vLLM main: https://github.com/vllm-project/vllm/commit/8d0a01a5f2b53794e4bc6b734d7b63cb8a9b7d7d
=> [main] Use AddRmsNormQuant ops in the custom model to optimize Qwen3's performance

tests/singlecard/ops/test_fused_moe.py, vllm_ascend/ops/fused_moe.py
Apply torch_npu.npu_moe_gating_top_k_softmax for moe, when scoring_func is softmax.
NO
ut.
**performance:**
**base**：
Successful requests:                     200       
Benchmark duration (s):                  367.80    
Total input tokens:                      409600    
Total generated tokens:                  409600    
Request throughput (req/s):              0.54      
Output token throughput (tok/s):         1113.64   
Total Token throughput (tok/s):          2227.28 
**apply torch_npu.npu_moe_gating_top_k_softmax**：
Successful requests:                     200       
Benchmark duration (s):                  362.59    
Total input tokens:                      409600    
Total generated tokens:                  409600    
Request throughput (req/s):              0.55      
Output …
=> [0.9.1][Perf] apply npu_moe_gating_top_k_softmax for moe

vllm_ascend/worker/model_runner_v1.py
Avoid performing cpu all_reduce in disaggregated-prefill scenario for better performance.
=> [0.9.1][PD][Perf] Avoid performing cpu all_reduce in disaggregated-prefill scenario.

docs/source/user_guide/support_matrix/supported_features.md, docs/source/user_guide/support_matrix/supported_models.md
The feature support matrix is out of date. This PR refresh the content.
- vLLM main: https://github.com/vllm-project/vllm/commit/107111a85991cbe9c8d16b697e048d91aa4135f6
=> [Doc] Update support feature

tests/ut/patch/worker/patch_common/test_patch_distributed.py, tests/ut/patch/worker/patch_common/test_patch_minicpm.py, tests/ut/patch/worker/patch_common/test_patch_utils.py
Add UT for patches in vLLM Ascend
No
Irrelevant
- vLLM main: https://github.com/vllm-project/vllm/commit/107111a85991cbe9c8d16b697e048d91aa4135f6
=> Add UT for Patches

csrc/torch_binding.cpp, tests/e2e/singlecard/ops/test_vocabparallelembedding.py
Change AI Vector core number getting function to glibc ABI free  function. After this PR merged in, there should been no glibc ABI problems for bump torch version to 2.7.1.
No
- vLLM main: https://github.com/vllm-project/vllm/commit/f59ec35b7f9ff5b1da8aae12e10b83154685c958
=> [Optimize]Change AI Vector core number getting function to glibc ABI free  funcition

tests/ut/attention/test_attention_v1.py, vllm_ascend/attention/attention_v1.py, vllm_ascend/attention/attention_v1_torchair.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/worker/eagle_proposer_v1.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/mtp_proposer_v1.py
Before do attention module refactor, we can do some code cleanup to make the next step easier.
What this PR does:
1. remove uesless `common_prefix_len` for attention builder
2. remove uesless `is_only_prefill` and `num_input_tokens` in attention metadata.
3. remove `CommonAttentionMetadata` and ues `query_start_loc` instead, `CommonAttentionMetadata` is over designed and uesless
4. update the attention backend input parameters to keep the same as vLLM.
5. Rename attention name to the same style with `ASCEND` prefix
- vLLM main: https://github.com/vllm-project/vllm/commit/107111a85991cbe9c8d16b697e048d91aa4135f6
=> [Misc] Clean up uesless code in attention

tests/ut/models/test_deepseek_v2.py, tests/ut/ops/test_fused_ops.py
What this PR does / why we need it?
Add uts for deepseek_v2
Does this PR introduce any user-facing change?
No
How was this patch tested?
- vLLM main: https://github.com/vllm-project/vllm/commit/f3137cdd81cae3a48282c22130fbcadcfc64ea95
=> [Test]add ut for deepseek_v2.

tests/ut/multistream/test_base.py, tests/ut/multistream/test_metadata.py, tests/ut/multistream/test_ms_split.py
Add some uts for files in folder /multistream
No
- vLLM main: https://github.com/vllm-project/vllm/commit/b77c7d327f2a463bb9ef8be36f30e920bc066502
=> [Test] Add ut for files in /multistream

examples/disaggregate_prefill_v1/README.md
In the document examples/disaggregate_prefill_v1/README.md, there are some incorrect or non-standard issues. This PR fixes these problems.
Below are the identified issues:
Non-standard issue: The model weight path is /data01/deepseek_r1_w8a8_zhw, which even includes a person’s initials.
Incorrect issue 1: When running gen_ranktable.sh, the parameter --network-card-name is set to enp189s0f0, but elsewhere in the document, network-card-name is consistently eth0.
Incorrect issue 2: In the VLLM benchmark command, the --port is set to 8000, but according to the earlier documentation, it should be 1025.
No
=> [Doc] Fix errors and non-standard parts in examples/disaggregate_prefill_v1/README.md

vllm_ascend/models/qwen2_5_vl.py, vllm_ascend/models/qwen2_5_vl_without_padding.py, vllm_ascend/models/qwen2_vl.py
Signed-off-by: wuzhongjian <wuzhongjian_yewu@cmss.chinamobile.com>
Fix duplicate 'torch.' prefix in qwen2-vl, qwen2.5-vl
- vLLM main: https://github.com/vllm-project/vllm/commit/dde295a9342fa2b1a3f6c4886706694a53f7b97d
=> [Bug] Fix duplicate 'torch.' prefix in qwen-vl

tests/ut/base.py, tests/ut/models/test_qwen2_5_vl_without_padding.py
this pr is to add ut for qwen2_5_vl_without_padding.py
no
this is only a ut test
- vLLM main: https://github.com/vllm-project/vllm/commit/9c8b2c2a8a0bbfa0c43ed7b220642dc3e802633c
=> ut:add ut for qwen2_5_vl_without_padding.py

.github/workflows/nightly_benchmarks.yaml
Remove transformers installation, The transformers version bug has been fixed by https://github.com/vllm-project/vllm/commit/e936e401debe7fba64d6462666d7dc632bc76357. We can safe to remove the version limit now
- vLLM main: https://github.com/vllm-project/vllm/commit/40d86ee412eeeca93e0c37432db6b96829cb64e2
=> [CI] Remove transformers installation

vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
Added `get_supported_tasks` interface to adapt to vllm [changes](https://github.com/vllm-project/vllm/commit/46d81d69511ac11f27d19af80d19dd7b2cce8613#diff-80ee7e2a62f9dcfbb8a312dc4e3948557e97ef187290daebbcae1e28596bda29)
- vLLM main: https://github.com/vllm-project/vllm/commit/5ac3168ee342f4cae17b0b67375e647bd5dd9151
=> [Bugfix] Add get_supported_tasks interface to fix broken CI

vllm_ascend/models/qwen2_5_vl_without_padding.py
In `AscendQwen2_5_VisionAttention_Without_Padding`,  `torch_npu.npu_rotary_mul(q, cos, sin)`， `cos`/`sin` on cpu, but `q` on npu, so there will be an error.
`qwen2_5_vl_without_padding.py` need this bugfix, because `AscendQwen2_5_VisionTransformer_Without_Padding.rot_pos_emb` in wen2_5_vl_without_padding.py is from vllm and `inv_freq` will create on cpu.
https://github.com/vllm-project/vllm/blob/40d86ee412eeeca93e0c37432db6b96829cb64e2/vllm/model_executor/models/qwen2_5_vl.py#L482
```python
inv_freq = 1.0 / (theta**(torch.arange(0, dim, 2, dtype=torch.float, device='cpu') / dim))
```
`qwen2_5_vl.py` do not need,  because `AscendQwen2_5_VisionRotaryEmbedding` in qwen2_5_vl.py rewrite `AscendQwen2_5_VisionRotaryEmbedding` and `inv_freq` will create on device.
```python
inv_freq = 1.0 / …
```
=> [Bugfix] fix tensor not same device in qwen2_5_vl_without_padding

examples/disaggregate_prefill_v1/README.md
- In the D node, the `max-num-batched-tokens` parameter can be set to a smaller value since the D node processes at most `max-num-seqs` batches concurrently. As the `profile_run` only needs to handle `max-num-seqs` sequences at a time, we can safely set `max-num-batched-tokens` equal to `max-num-seqs`. This optimization will help reduce activation memory consumption.
- Restore the default configuration items for PD separation.
=> [v0.9.1][Doc][PD] Restore the default configuration items in examples/disaggregate_prefill_v1/README.md

.github/workflows/accuracy_test.yaml, .github/workflows/nightly_benchmarks.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_long_term.yaml, .github/workflows/vllm_ascend_test_pd.yaml, Dockerfile, Dockerfile.openEuler, README.md, README.zh.md, docs/source/conf.py, docs/source/installation.md
Upgrade CANN to 8.2.rc1
Backport: https://github.com/vllm-project/vllm-ascend/pull/1653
Yes, docker image will use 8.2.RC1
CI passed
=> [v0.9.1] Upgrade CANN to 8.2.rc1

docs/source/tutorials/single_npu_audio.md, docs/source/tutorials/single_npu_multimodal.md, requirements-dev.txt, tests/e2e/singlecard/test_offline_inference.py, tests/ut/test_utils.py, vllm_ascend/utils.py
Fix num_hidden_layers when Qwen2-Audio 7B and #1760 ：
```
INFO 07-15 04:38:53 [platform.py:174] PIECEWISE compilation enabled on NPU. use_inductor not supported - using only ACL Graph mode
Traceback (most recent call last):
File "/workspace/test1.py", line 58, in <module>
main(audio_count)
File "/workspace/test1.py", line 38, in main
llm = LLM(model="Qwen/Qwen2-Audio-7B-Instruct",
File "/vllm-workspace/vllm/vllm/entrypoints/llm.py", line 271, in __init__
self.llm_engine = LLMEngine.from_engine_args(
File "/vllm-workspace/vllm/vllm/engine/llm_engine.py", line 494, in from_engine_args
vllm_config = engine_args.create_engine_config(usage_context)
File "/vllm-workspace/vllm/vllm/engine/arg_utils.py", line 1286, in create_engine_config
config = VllmConfig(
File …
```
=> [Bugfix] Fix num_hidden_layers when Qwen2-Audio 7B

Dockerfile.a3, Dockerfile.a3.openEuler
Upgrade CANN to 8.2.RC1
Yes, A3 image are using 8.2.rc1
CI passed
- vLLM main: https://github.com/vllm-project/vllm/commit/de509ae8eb4467bd789234d909e5c725b8fba326
=> Upgrade CANN to 8.2.RC1 (A3)

tests/e2e/multicard/test_dynamic_npugraph_batchsize.py, tests/e2e/multicard/test_pyhccl_distributed.py
1.Fixed the issue that pyhccl e2e cannot run continuously with other tests. 
2.Cleaned up the resources occupied by the dynamic_npugraph_batchsize e2e test.
No
This is a e2e test
e2e multi-cards tests local running successfully.
- vLLM main: https://github.com/vllm-project/vllm/commit/0df4d9b06b15fa39eeb2d440e7742da93afd5e6c
=> [e2e]Fixed the issue that pyhccl e2e cannot run continuously with other tests

tests/e2e/multicard/test_pyhccl_distributed.py
Fix test on pyhccl to 2 cards
N/A
- vLLM main: https://github.com/vllm-project/vllm/commit/0d0cc9e15001b18997207fc86af6810500d587d9
=> [CI] Fix test on pyhccl to 2 cards

vllm_ascend/quantization/func_wrapper.py, vllm_ascend/quantization/quantizer.py
1. add wrapper of vocab_parallel_embedding, fixed the bugs when running deepseek-w8a8-mtp
Signed-off-by: curryliu <120010041@link.cuhk.edu.cn>
=> [0.9.1][bugfixed] fix the bug when run the inference of quantized ds-w8a8-mtp

.github/actionlint.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_310p.yaml, tests/e2e/multicard/test_offline_inference_310p.py, tests/e2e/singlecard/test_offline_inference_310p.py
Add e2e test for 310p:
trigger conditions：tag, labels(ready-for-test, e2e-310p-test), schedule
image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-310p-ubuntu22.04-py3.10
runner: linux-aarch64-310p-1, linux-aarch64-310p-4
model: IntervitensInc/pangu-pro-moe-model, Qwen/Qwen3-0.6B-Base,  Qwen/Qwen2.5-7B-Instruct
- vLLM main: https://github.com/vllm-project/vllm/commit/b917da442b820245f537602d752e7146e66dd37a
=> [CI]Add e2e test for 310p

vllm_ascend/envs.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/mtp_proposer_v1.py, vllm_ascend/worker/worker_v1.py
This pull request removes the Dynamo guard for both the DeepSeek and MTP models by resetting the Dynamo graph and invoking the `cache_compile` API twice. This optimization reduces TPOT (Time Per Output Token) by approximately 3ms.
No. Users can enable this feature by setting `"use_cached_graph":true` in `torhcair_graph_config` as before.
It was tested with single-node online serving with DP2TP8EP16 and 8-node disaggregated prefill scenarios with DP2TP8EP16 for P and DP64EP64 for D. We can obtain stable improvements with high user-friedliness.
=> [0.9.1][feat] add kv cache memory cache and skip dynamo guard for deepseek and deepseek_mtp models to increase user-friedliness

vllm_ascend/ops/fused_moe.py, vllm_ascend/quantization/w4a8_dynamic.py, vllm_ascend/quantization/w8a8_dynamic.py
This PR fixes the shape conflicts between shared & routed experts for deepseek model when tp > 1 and multistream_moe enabled. It also fixes the interface conflicts for deepseek (BF16) introduced by https://github.com/vllm-project/vllm-ascend/pull/1391.
No.
It was tested with single-node online serving with DP2TP8EP16 and 8-node disaggregated prefill scenarios with DP2TP8EP16 for P and DP64EP64 for D.
=> [0.9.1][bugfix] fix bf16 multistream

docs/source/installation.md
Fix cann related urls in installation doc.
The users install cann manually could use the correct url after this pr
N/A
- vLLM main: https://github.com/vllm-project/vllm/commit/5bbaf492a6238ff517249e73151ae9989f7bea9e
=> [Doc] Fix cann related urls

Dockerfile, Dockerfile.310p, Dockerfile.310p.openEuler, Dockerfile.a3, Dockerfile.a3.openEuler, Dockerfile.openEuler, requirements-dev.txt
Fix protobuf version in Dockerfile to resolve `AttributeError: 'str' object has no attribute 'DESCRIPTOR' when packaging message to dict` using protobuf. will remove version specification after https://github.com/ray-project/ray/pull/54910 is merged
N/A
- vLLM main: https://github.com/vllm-project/vllm/commit/0e36abf9931baa070609376debb4fb3772f4a3fe
=> [Build][Ray] Fix protobuf version in Dockerfile

tests/ut/models/test_deepseek_mtp.py, tests/ut/multistream/test_decorator.py
add ut for decorator.py/deepseek_mtp.py
No
CI passed with new tests
- vLLM main: https://github.com/vllm-project/vllm/commit/055bd3978ededea015fb8f0cb6aa3cc48d84cde8
=> [Test] add ut for decorator.py/deepseek_mtp.py

vllm_ascend/ops/fused_moe.py
Fix vLLM startup failure when inferring DeepSeek R1 model in DP scenario.
When running vLLM inference for the DeepSeek R1 model in DP32+TP1 configuration, the vLLM service fails to start with the following error.
The root cause is a missing else branch after [this line of code](https://github.com/vllm-project/vllm-ascend/blob/d629f0b2b573c3ba858a09fc93c42f2c2634e043/vllm_ascend/ops/fused_moe.py#L1411). This PR fixes the issue.
No
- vLLM main: https://github.com/vllm-project/vllm/commit/5bbaf492a6238ff517249e73151ae9989f7bea9e
=> [main][bugfix]Fix vLLM startup failure when inferring DeepSeek R1 model in DP scenario

tests/ut/device_allocator/test_camem.py, tests/ut/multistream/test_layers.py
What this PR does / why we need it?
test device allocator/camem and mutistream/layers contains resource allocation and stream ops
Does this PR introduce any user-facing change?
N/A
How was this patch tested?
- vLLM main: https://github.com/vllm-project/vllm/commit/2836dd73f13015ee386c544760ca0d16888203f3
=> add ut for device allocator/camem and mutistream/layers

tests/e2e/multicard/test_torchair_graph_mode.py, vllm_ascend/attention/mla_v1.py
This PR fixes the bug `local variable 'decode_hs_or_q_c' referenced before assignment` when running chunked-prefill with torchair. We should calculate `decode_hs_or_q_c` whether or not torchair graphics mode is enabled.
backport of #1378
fix https://github.com/vllm-project/vllm-ascend/issues/1369
- vLLM main: https://github.com/vllm-project/vllm/commit/0e36abf9931baa070609376debb4fb3772f4a3fe
=> [BugFix] Fix a bug of running chunked-prefill with torchair. (#1378)

tests/e2e/singlecard/ops/test_fused_moe.py, tests/ut/ops/test_fused_ops.py, vllm_ascend/envs.py, vllm_ascend/ops/common_fused_moe.py, vllm_ascend/ops/fused_moe.py
backport of v0.9.1-dev: https://github.com/vllm-project/vllm-ascend/pull/1902
origin main npu_moe_gating_top_k_softmax: https://github.com/vllm-project/vllm-ascend/pull/1355
No.
ut and e2e.
- vLLM main: https://github.com/vllm-project/vllm/commit/055bd3978ededea015fb8f0cb6aa3cc48d84cde8
=> [main] adapt usage of npu_moe_gating_top_k_softmax and remove envs.SELECT_GATING_TOPK_SOTFMAX_EXPERTS

vllm_ascend/sample/sampler.py
Fixed 310p failure when using the sampler feature.
The root cause is: torch_npu.npu_top_k_top_p uses the operator aclnnApplyTopKTopP, but aclnnApplyTopKTopP currently does not support 310P.
First PR that has the issue is #1308.
No
- vLLM main: https://github.com/vllm-project/vllm/commit/207b750e194829c4bcd4df0450f5f93d71755dae
=> Fixed 310p failure when using the sampler feature

vllm_ascend/models/qwen2_5_vl_without_padding.py
Cherry pick #1705 from v0.9.1-dev
Compared qwen2_5_vl.py, qwen2_5_vl_without_padding.py missing some funtions. The purpose of this PR is to supplement these.
add:
- rot_pos_emb(self, grid_thw: torch.Tensor)
- get_window_index(self, grid_thw)
- _process_image_input(self, image_input)
- _process_video_input(self, video_input)
Co-authored-by: zheliuyu [15750543867@163.com](mailto:15750543867@163.com)
Co-authored-by: wangli [wangli858794774@gmail.com](mailto:wangli858794774@gmail.com)
- vLLM main: https://github.com/vllm-project/vllm/commit/207b750e194829c4bcd4df0450f5f93d71755dae
=> [Misc] Add data preprocess functions to qwen2.5_vl_without_padding

examples/offline_disaggregated_prefill_npu.py
The functions KVTransferConfig.from_cli and AscendHcclConnector are missing in the latest vLLM version. To resolve this, I propose modifying the kv_connector to use LLMDataDistCMgrConnector, which depends on [PR #2079](https://github.com/vllm-project/vllm-ascend/pull/2079)
vllm:main
vllm-ascend:mian
results:
```bash
Adding requests: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 374.27it/s]
Processed prompts: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 66.06it/s, est. speed input: 449.08 toks/s, output: 66.51 toks/s]
Prefill node is finished.
INFO 07-31 09:18:30 …
```
=> [BugFix] update the kv transfer config

tests/e2e/singlecard/test_aclgraph.py, vllm_ascend/platform.py
cherry-pick #1501 from 0.9.1-dev to main
Currently, Ray is not compatible with ACL Graph, so we need to fall back to eager mode when using the Ray backend.
co-authored: Yizhou Liu <liu_yizhou@outlook.com>
- vLLM main: https://github.com/vllm-project/vllm/commit/2836dd73f13015ee386c544760ca0d16888203f3
=> [Misc] Add warning for incompatible Ray backend with ACL Graph mode

vllm_ascend/attention/attention_v1.py, vllm_ascend/attention/attention_v1_torchair.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/models/deepseek_dbo.py, vllm_ascend/multistream/ms_split.py, vllm_ascend/worker/model_runner_v1.py
Cherry pick #1291 from v0.9.1-dev, This pr  implement the synchronization of whether `dbo` is enabled across all dp ranks. specifically, it performed allreduce op across multiple DP ranks, only when all the dp rank is `enable_dbo`,  it is enabled
Co-authored-by: shikang-hangzhou <459956190@qq.com>
Co-authored-by: wangli <wangli858794774@gmail.com>
- vLLM main: https://github.com/vllm-project/vllm/commit/2836dd73f13015ee386c544760ca0d16888203f3
=> [MISC] Cherry pick #1291 from v0.9.1-dev

vllm_ascend/ops/common_fused_moe.py, vllm_ascend/ops/fused_moe.py
Updates the FusedMoE method to determine whether to use ACL Graph based on the `torchair_graph_config`
None.
None needed.
=> [0.9.1][Fix] Turn off ACL Graph when enabling TorchAir

vllm_ascend/patch/platform/patch_0_9_1/__init__.py, vllm_ascend/patch/platform/patch_0_9_1/patch_cache_manager.py
When you launch the decoder with `--no_enable_prefix_caching` on ascend devices and benchmark the system with random inputs, at least 129 tokens each, you see the following message after ~2000 tests.
```
File "/code/vllm/vllm/v1/core/block_pool.py", line 145, in cache_full_blocks
assert blk.block_hash is None
^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
Then the decoder exits and the system freezes.
What's happening is that the caching operation is delayed from immediatly after allocation to after the KVCache transportation
in decoder instances, but currently we always cache blocks after they are received from prefillers even if caching is not enabled at all and these cached blocks never get evicted since caching is disabled.
This PR is aiming at fixing the bug. Since the `main` branch of …
=> [v0.9.1][Bugfix][PD] fix D crashing if caching is disabled

examples/offline_inference_audio_language.py
Using vllm's AudioAsset class to retrieve remote audio files(https://vllm-public-assets.s3.us-west-2.amazonaws.com) is not feasible in some cases; it is recommended to switch to local retrieval.
vllm:main
vllm:ascend:main
results:
```bash
Adding requests: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.62s/it]
Processed prompts: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.01s/it, est. speed input: 79.03 toks/s, output: 6.31 toks/s]
generated_text: The sport referenced is soccer, and the nursery rhyme is 'Hey Diddle Diddle'.
```
- vLLM main: …
=> Change retrieving remote files to local retrieval.

vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
We notice that vllm's main branch merged the PR https://github.com/vllm-project/vllm/pull/21072 and https://github.com/vllm-project/vllm/pull/21473 to support ray backend and fix some rebase bug from previous change. Those changes makes the disaggregate pd in vllm ascend breaks in some scenario. 
In this PR, we adopt those changes to make sure the `llmdatddist_c_mgr_connector` works fine on the newest vllm main branch.
No user face change.
relevant ut will be added to make sure the functionality of those changes.
- vLLM main: https://github.com/vllm-project/vllm/commit/ad57f23f6a528ab01066998b41796a44340fd43d
=> [Bugfix] Adopt the new changes on disaggregated pd from vllm main branch

tests/e2e/long_term/accuracy/accuracy_multicard.py, tests/e2e/multicard/test_data_parallel.py, vllm_ascend/distributed/communicator.py
Fix Qwen MoE accuracy bug in DP scenario.
Now the implentment of `FusedMoE` in vLLM use `All2AllManager` to manager different all2all algorithm branch. And the default branch use `Multicast` in `dispatch` phase and `all_reduce` in `combine` phase, which are not implented in vLLM-Ascend. This leading to invoking into a default implentment in `base_communicator`, with empty `dispatch` and `combine` operations, thus causing the accuracy issue on it.
This pr is a temporary workaround, refacting all2all in vLLM-Ascend could be a better way.
- vLLM main: https://github.com/vllm-project/vllm/commit/ad57f23f6a528ab01066998b41796a44340fd43d
=> [MoE][Dist] Fix Qwen MoE accuracy bug in DP scenario

vllm_ascend/quantization/func_wrapper.py, vllm_ascend/quantization/quantizer.py
When run the inference of ds-w8a8-mtp,  it reported 'ParamllelLMhead has no attribute 'params_dtype''.
1. add wrapper of vocab_parallel_embedding, fixed the bugs when running deepseek-w8a8-mtp
Signed-off-by: curryliu <120010041@link.cuhk.edu.cn>
- vLLM main: https://github.com/vllm-project/vllm/commit/ad57f23f6a528ab01066998b41796a44340fd43d
=> [bugfixed] fix the bug when run the inference of quantized ds-w8a8-mtp

tests/ut/kv_connector/test_remote_decode_lifecycle.py, tests/ut/kv_connector/test_remote_prefill_lifecycle.py, tests/ut/kv_connector/utils.py, vllm_ascend/models/qwen2_5_vl.py, vllm_ascend/models/qwen2_5_vl_without_padding.py, vllm_ascend/models/qwen3_moe.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
This pr fix broken CI:
1. Fix the  https://github.com/vllm-project/vllm/commit/ee2eb6ecd86be4b47e334f74feb7874b9a41ca25 changes, in this commit, they fused the gate and up projections in the vision MLP,  This can improve performance by reducing one matrix multiplication. so, this pr do the following things:
- Specify that the two linear layers are fused as `mlp.gate_up_proj` when loading the weights.
- Use a SiluAndMul activation function.
2. Fix https://github.com/vllm-project/vllm/commit/aefeea0fde0fbe5871a0799fad583e6ed6fdf903, Update ModelRunnerOutput parameters to adapt to its changes
3. Fix [vllm-commit](https://github.com/vllm-project/vllm/pull/20815/files#diff-3ffb829a39ab2b3e4706aa28f5e476815f36c3a87b98d6a66514ebedc8f3ffb4R354-R356), fix qwen moe
- vLLM …
=> [Bugfix] Follow vLLM Qwen-Moe/VL and KV Connector change to fix broken CI

tests/e2e/multicard/test_qwen3_moe.py, vllm_ascend/models/qwen3_moe.py, vllm_ascend/ops/fused_moe.py
What's the PR does:
1. Move AscendSparseMoeBlock to qwen3 model, since it's only used by qwen3 model.
2. Disable AscendSparseMoeBlock if aclgraph  is enabled, AscendSparseMoeBlock doesn't work with aclgraph currently.
- vLLM main: https://github.com/vllm-project/vllm/commit/cdfd6871a5c4f125c9b3707ec5c1260db54f4b03
=> [BugFix] Fix the bug that qwen3 moe doesn't work with aclgraph

.github/workflows/vllm_ascend_test.yaml, vllm_ascend/torchair/torchair_model_runner.py, vllm_ascend/torchair/torchair_worker.py, vllm_ascend/worker/worker_v1.py
There is lot of torchair code in model runner leading the code hard for maintenance.  We'll create new torchair_model_runner to split torchair related logic. Following the workflow #2203, this is the first PR.
What this PR does:
create the new torchair model runner, more function will be added later
- vLLM main: https://github.com/vllm-project/vllm/commit/586f286789a09f5616be74ee8bedde0a9f698a72
=> [1/N][Refactor] torchair model runner refactor

tests/e2e/multicard/test_qwen3_moe.py, vllm_ascend/models/qwen3_moe.py
Fixes unable to load `qwen3_moe` quantized weights issue due to #1994
None
Add a `qwen3_moe` W8A8 quantized model in `tests/e2e/multicard/test_qwen3_moe.py`
- vLLM main: https://github.com/vllm-project/vllm/commit/c494f96fbcf5e9f19f59e3dea6c2780aeb6c567f
=> [main][Bugfix] Fix unable to load qwen3_moe quantized weights

tools/check_python_src_init.py
For the vllm src https://github.com/vllm-project/vllm/tree/main/vllm/attention/layers do not have `__init__.py`, which will break the python src init check, so we skip it for now
- vLLM main: https://github.com/vllm-project/vllm/commit/6b47ef24de3d3b4f551aca0bc21b9f16f3d21b6a
=> [Bugfix] Disable check vllm init temporary

tests/e2e/doctests/002-pip-binary-installation-test.sh
Remove transformer pins for v0.9.1-dev, because we already release the v0.9.1rc2 with right transformer version
No
doctest CI passed
- vLLM main: https://github.com/vllm-project/vllm/commit/7e6544c7978364fcb8178f4ab8b1325e45880aa9
=> Remove transformer pins for v0.9.1-dev

tests/ut/ops/test_fused_ops.py, vllm_ascend/ops/fused_moe.py
torch_npu.npu_grouped_matmul:
https://www.hiascend.com/document/detail/zh/Pytorch/710/apiref/torchnpuCustomsapi/context/torch_npu-npu_grouped_matmul.md
According to the document, when `split_item` is 2 or 3, `torch_npu.npu_grouped_matmul` will return a list which has one element. Therefore, the `torch.cat` after `torch_npu.npu_grouped_matmul` is unnecessary. 
not involved
ut and e2e covered: `tests/ut/ops/test_fused_ops.py`, `tests/e2e/singlecard/ops/test_fused_moe.py`
**performance**:
(qwen3 30B, 2k->20k)
base:
Total Token throughput (tok/s):          667.76 
remove cat:
Total Token throughput (tok/s):          680.82 
- vLLM main: https://github.com/vllm-project/vllm/commit/fa00c5d75bc63c87f5822f839db1342f19e4acc8
=> [main] remove torch.cat and replace it by List[0]

.github/workflows/accuracy_test.yaml
Fix create PR of accuracy test 
no
Local testing: https://github.com/nv-action/vllm-benchmarks/pull/87
- vLLM main: https://github.com/vllm-project/vllm/commit/099c0464637f330f8ea38b07fe0694717c16d815
=> Fix accuracy test create PR

tests/ut/distributed/test_communicator.py
Add ut for test_communicator.py 
- vLLM main: https://github.com/vllm-project/vllm/commit/e5ebeeba531755a78f68413e88a23d061404f3e3
=> Add ut for test_communicator.py

vllm_ascend/torchair/torchair_model_runner.py, vllm_ascend/worker/model_runner_v1.py
There is lot of torchair code in model runner leading the code hard for maintenance.  We'll create new torchair_model_runner to split torchair related logic. Following the workflow #2203
What's this PR do:
move `torchair` related logic into `_get_forward_metadata_across_dp` and override it in torchair model runner
- vLLM main: https://github.com/vllm-project/vllm/commit/1b9902806915040ac9b3029f2ab7522ec505afc3
=> [2/N][Refactor] torchair model runner refactor

tests/e2e/singlecard/sample/test_rejection_sampler.py, tests/ut/sample/test_rejection_sampler.py, vllm_ascend/sample/rejection_sampler.py
This PR port optimization in PR #2002 to main and makes it cleaner.
- vLLM main: https://github.com/vllm-project/vllm/commit/afa5b7ca0b417abadfa85e32f28969b72e58a885
=> [Perf][MTP] Optimize reject sampler in greedy situation.

vllm_ascend/torchair/torchair_model_runner.py, vllm_ascend/worker/model_runner_v1.py
There is lot of torchair code in model runner leading the code hard for maintenance.  We'll create new torchair_model_runner to split torchair related logic. Following the workflow #2203
What's this PR do:
create common function `_capture_model` for capture_model
- vLLM main: https://github.com/vllm-project/vllm/commit/1891a265d316217f9c1e552cf7c380ef5bf1eec1
=> [5/N][Refactor] torchair model runner refactor

tests/e2e/multicard/moe/test_moe_comm.py, vllm_ascend/ascend_forward_context.py, vllm_ascend/distributed/moe_comm_method.py, vllm_ascend/ops/common_fused_moe.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/platform.py, vllm_ascend/worker/model_runner_v1.py
This PR refactors the MoE (Mixture of Experts) communication logic by introducing a strategy pattern. It defines an abstract base class, `MoECommMethod`, which encapsulates different communication strategies for MoE layers. By decoupling the MoE implementation from any single communication method, this change makes it simpler to add, replace, or optimize communication strategies in the future.
Plan / Roadmap
1. Introduce `MoECommMethod`, implement `AllGatherImpl`, and adapt ACL Graph handling to cover all scenarios (this PR).
2. Implement `MC2CommImpl` and `AllToAllCommImpl` to optimize performance in specific scenarios.
3. Enable W8A8 / Int8 models to use `unified_fused_experts`.
Other notes
* Data-parallel (DP) communication currently does not work with vLLM's dispatch/combine …
=> [1/N][Feat] Support MoE models with ACL Graph and refactor MoE communication logic

docs/source/faqs.md
Add Docker export/import guide for air-gapped environments
No
NA
- vLLM main: https://github.com/vllm-project/vllm/commit/d16aa3dae446d93f870a2e51b240e18a01cac294
=> [Doc] Add container image save/load FAQ for offline environments

vllm_ascend/ascend_config.py, vllm_ascend/platform.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
Original implementation of torchair caching forces users to make everything prepared, fix all the configuration and enable `use_cached_npu_graph`,  and it might cause some problems confusing to understand and tackle for users. It is better to compile the graph twice instead of reusing the old kvcaches and cached torchair graph. And the extra duration time is acceptable.
If users want to enabling torchair.cache_compile with high compilation speed, it is recommended to enable both `use_cached_kv_cache_bytes` and `use_cached_graph` in `torchair_graph_config`. Without `use_cached_kv_cache_bytes`, we'll compile torchair computation graph twice to avoid runtime error caused by configuration mismtaches (the second compilation will be much faster).
CI and e2e vllm serving passed.
=> [v0.9.1][bugfix] fix torchair runtime errror caused by configuration mismtaches and .kv_cache_bytes file missing

tests/ut/patch/worker/patch_common/test_patch_linear.py, tests/ut/test_envs.py, vllm_ascend/ascend_forward_context.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/compilation/piecewise_backend.py, vllm_ascend/distributed/llmdatadist_c_mgr_connector.py, vllm_ascend/models/__init__.py, vllm_ascend/patch/platform/patch_common/patch_distributed.py, vllm_ascend/patch/worker/patch_common/patch_linear.py, vllm_ascend/platform.py, vllm_ascend/quantization/w8a8_dynamic.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
Remove redundant imported `envs`, using `envs_ascend` instead.
```python
import vllm.envs as envs_vllm
import vllm_ascend.envs as envs_ascend
```
- vLLM main: https://github.com/vllm-project/vllm/commit/71683ca6f6764f35abe23d612a0d7dbd33babe32
=> [Misc] Remove redundant imported `envs`, using `envs_ascend` instead

docs/source/developer_guide/performance/distributed_dp_server_with_large_ep.md, docs/source/developer_guide/performance/index.md
This PR presents a large-EP deployment solution based on vllm-ascend, using DeepSeek as an example. It outlines the end-to-end workflow for model deployment and serves as a reference for developers.
No
=> add document for deepseek large EP

vllm_ascend/attention/attention_v1.py, vllm_ascend/attention/mla_v1.py, vllm_ascend/attention/utils.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/mtp_proposer_v1.py
1. MTP supports V1 scheduler 
2. Refactor attn metadata build
=> [v0.9.1] MTP supports V1 scheduler 

vllm_ascend/platform.py, vllm_ascend/worker/worker_v1.py
Our current code register the custom ops inside the platform intialization phase. however, when a new process started by creating a worker, the former patch will lose it effect on the custom ops and lead to fallback to the native pass wrote in vllm. This PR move the patch code to the worker to make sure the custom op patch worker as our expected.
No
- vLLM main: https://github.com/vllm-project/vllm/commit/8ea0c2753a273e24957ab4587c200a3254ebe970
=> [Bugfix] Fix custom op register issue

tests/ut/test_platform.py, vllm_ascend/attention/attention_v1.py, vllm_ascend/platform.py, vllm_ascend/torchair/torchair_attention.py, vllm_ascend/worker/model_runner_v1.py
1. Move `torchair_attention` to `torchair` dir.
2. Make `AscendAttentionTorchairBackend` extend `AscendAttentionBackend` to reduce duplicate methods.
3. Make `AscendTorchairMetadata` extend `AscendMetadata` to reduce duplicate properties.
- vLLM main: https://github.com/vllm-project/vllm/commit/0933f9d518ecb18e8427bf42731d2a3d00276883
=> [3/N][Refactor] Move `torchair_attention` to `torchair` dir

vllm_ascend/worker/model_runner_v1.py
Fix https://github.com/vllm-project/vllm-ascend/issues/2033
Sync https://github.com/vllm-project/vllm/pull/14702 to solve `grammar_bitmask` IndexError caused by outdated `apply_grammar_bitmask` method
No
=> [Bugfix] Fix `grammar_bitmask` IndexError caused by outdated `apply_grammar_bitmask` method

docs/source/community/contributors.md
I would like to nominate Wengang Chen (@ApsarasX https://github.com/ApsarasX) as a maintainer, starting with my +1.
Review Quality‌: He focuses on the vLLM Ascend Core module review with 100+ high quality review, such as [#2326 (comment)](https://github.com/vllm-project/vllm-ascend/pull/2326#discussion_r2268509365), [#768 (comment)](https://github.com/vllm-project/vllm-ascend/pull/768#discussion_r2075278516), [#2312 (comment)](https://github.com/vllm-project/vllm-ascend/pull/2312#issuecomment-3174677159), [#2268 (comment)](https://github.com/vllm-project/vllm-ascend/pull/2268#discussion_r2260920578), [#2192 (comment)](https://github.com/vllm-project/vllm-ascend/pull/2192#issuecomment-3149414586), [#2156 (comment)](https://github.com/vllm-project/vllm-ascend/pull/2156#discussion_r2249096673 …
=> Nominate ApsarasX as vllm-ascend maintainer

.github/workflows/vllm_ascend_test.yaml
add lint block before running e2e. follow up https://github.com/vllm-project/vllm-ascend/pull/2445
N/A
N/A
=> [CI] add lint block before running e2e

tests/e2e/multicard/test_torchair_graph_mode.py, tests/ut/models/test_qwen3_moe.py, tests/ut/test_ascend_config.py, vllm_ascend/ascend_config.py, vllm_ascend/ops/rotary_embedding.py, vllm_ascend/torchair/models/qwen2.py, vllm_ascend/torchair/models/qwen3_moe.py, vllm_ascend/torchair/torchair_attention.py, vllm_ascend/torchair/utils.py
Added support for the TorchAir graph mode in qwen3_moe and qwen2.5
No
```bash
llm = LLM(
model=model,
tensor_parallel_size=GPUs_per_dp_rank,
enforce_eager=False,
enable_expert_parallel=True,
max_model_len=4096,
max_num_seqs=16,
trust_remote_code=trust_remote_code,
gpu_memory_utilization=0.4,
additional_config={
"torchair_graph_config": {
"enabled": True,
"use_cached_graph": False,
"graph_batch_sizes_init": False,
"graph_batch_sizes": [16]
},
"ascend_scheduler_config": {
"enabled": True,
"chunked_prefill_enabled":True,
},
"refresh": True,
},
)
```
- vLLM main: https://github.com/vllm-project/vllm/commit/b87cb97a53bcff92a90308528b3f313e43aff102
=> qwen3_moe/qwen25 support torchair graph

vllm_ascend/distributed/llmdatadist_c_mgr_connector.py, vllm_ascend/envs.py
1. rename `VLLM_LLMDD_RPC_PORT` to `VLLM_ASCEND_LLMDD_RPC_PORT` to make the prefix the same in vllm-ascend
2. enable `VLLM_ASCEND_LLMDD_RPC_IP` env for PD feature.
=> [PD] Correct the ip and port env

tests/ut/ops/test_token_dispatcher.py, vllm_ascend/ops/moe_dispatcher/token_dispatcher.py
refactor allgather/mc2-related fused_experts
- vLLM main: https://github.com/vllm-project/vllm/commit/de7b67a0232e35ae8e8ecd944aeddfc8cbc02631
=> refactor allgather/mc2-related fused_experts

tests/ut/ops/test_linear.py, tests/ut/test_utils.py, vllm_ascend/distributed/parallel_state.py, vllm_ascend/envs.py, vllm_ascend/ops/linear.py, vllm_ascend/utils.py
For dense models, by not applying tensor parallelism (TP) to the attention module and applying TP to the MLP module, the allreduce operations in the attention module can be eliminated, thereby reducing computational overhead. However, this approach increases memory usage, so the environment variable VLLM_ASCEND_ENABLE_MLP_OPTIMZE is used to control this optimization.
- vLLM main: https://github.com/vllm-project/vllm/commit/b17109beeafbf9577c319ab61530810943a7fc4b
=> add mlp tp optimze

.github/ISSUE_TEMPLATE/750-RFC.yml, README.md, README.zh.md, docs/source/community/versioning_policy.md
This patch add the feature branch policy.
After this patch: maintainers are allowed to create a feature branch. Feature branches are used for collaboration and must include an RFC link, merge plan and mentor info.
No
CI passed
- vLLM main: https://github.com/vllm-project/vllm/commit/7be5d113d8784536b79f27f24cfa91958dc291b0
=> Add feature branch policy

tests/e2e/singlecard/test_embedding.py, tests/ut/test_platform.py
Skip failed ut to recover CI quickly
related ut:
- `test_embed_models_correctness`: revert me when pooler is adapted with the latest vllm main
- `test_check_and_update_config_enforce_eager_mode`: revert me when the occasional failed is fixed
- vLLM main: https://github.com/vllm-project/vllm/commit/8896eb72ebe90be6f1b83f32b3d3d0c379db4f82
=> [QuickFix] Skip failed ut to recover CI quickly

tests/e2e/singlecard/test_guided_decoding.py
Add test for `outlines` backend for structured output in CI.
No.
Tests have all passed with:
```bash
pytest -sv tests/e2e/singlecard/test_guided_decoding.py
```
- vLLM main: https://github.com/vllm-project/vllm/commit/53415653ff24be03e7c90f5b42ef9cb3f72aad71
=> [Structured Output][CI] Add test for `outlines` backend for structured output in CI

docs/source/conf.py
update vllm version in ci
- vLLM main: https://github.com/vllm-project/vllm/commit/170e8ea9ea95294d1bdc4af4bea73741ea759e22
=> [Doc] update vllm version in ci

vllm_ascend/worker/mtp_proposer_v1.py
Fix the inconsistency of cached directories between deepseek and its mtp model with torchair graph. This bug would lead to assertion error while running deepseek_mtp.
No.
CI and e2e vllm serving pass.
=> [0.9.1][bugfix]fix wrong cached torchair graph directory of deepseek_mtp model

tests/e2e/multicard/moe/test_moe_comm.py, tests/ut/distributed/test_communicator.py, tests/ut/test_utils.py, vllm_ascend/ascend_forward_context.py, vllm_ascend/distributed/communicator.py, vllm_ascend/distributed/moe_comm_method.py, vllm_ascend/distributed/parallel_state.py, vllm_ascend/models/pangu_moe.py, vllm_ascend/ops/common_fused_moe.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner_v1.py
This method replaces the previous all-gather approach for small numbers of tokens.
The key changes include:
- A new `AscendFusedMoE` layer that handles token splitting, local computation, and final aggregation via all-gather.
- Logic in the model runner to dynamically select between the new MC2 method and the existing all-gather method based on the number of input tokens.
- Sharding the MoE communication mask across tensor-parallel ranks.
None.
Test case fixed.
- vLLM main: https://github.com/vllm-project/vllm/commit/b00e69f8ca55f4a82847d39466f57ceb748324c1
=> [2/N][Feat] Add MC2 communication method for MoE layers

vllm_ascend/worker/model_runner_v1.py
This PR fixes the bug on some machines where quantmatmul failed to run with the NZ format. The change ensures proper execution under the expected data layout.
No.
- vLLM main: https://github.com/vllm-project/vllm/commit/b5d34af3286ee0334d9f7bd729774ac55c5805e9
=> [main][bugfix] Fix MatmulNZ format bug on some machines

tests/ut/test_platform.py, vllm_ascend/platform.py, vllm_ascend/worker/model_runner_v1.py
This pr updates compilation config in `check_and_update_config`, we use `compilation_config.level` to update `compilation_config.cudagraph_mode` to ensure the config is correct.
Add `compilation_config.cudagraph_num_of_warmups = 1` when V1 is enabled, cause this is also used in torchair graph mode. and this fixes https://github.com/vllm-project/vllm-ascend/issues/2523
fix the bug that the `aclgraphmode` always be `NONE` while running forward in aclgraph mode
- vLLM main: https://github.com/vllm-project/vllm/commit/f58675bfb36b67cdbca4d2356a2f580e7a706ec3
=> [Aclgraph] Update compilation config in `check_and_update_config`

tests/ut/ops/test_fused_ops.py, vllm_ascend/ops/fused_moe.py
convert the format of gmm to nz
not involved
ut: test_fused_ops.py and e2e: test_fused_moe.py
**performance**:
(qwen3 30B, 2k->20k)
base:
Total Token throughput (tok/s):          719.93
gmm nz:
Total Token throughput (tok/s):          728.52
- vLLM main: https://github.com/vllm-project/vllm/commit/bfc1edc9f5bde581e0eec5c830a5a4a7b710fe6a
=> [main] convert the format of gmm to nz

tests/ut/attention/test_attention_mask.py, vllm_ascend/attention/attention_mask.py, vllm_ascend/worker/eagle_proposer_v1.py, vllm_ascend/worker/model_runner_v1.py
This PR fix bugs and refactor cached mask generation logic. Now just pre-construct and use the cached mask on cpu instead of device on npu.
No.
- vLLM main: https://github.com/vllm-project/vllm/commit/9b5f64238fbd0f98928587b3426cbf69eea96ae7
=> [main][bugfix] Fix bugs and refactor cached mask generation logic

tests/ut/ops/test_vocab_parallel_embedding.py, tests/ut/test_utils.py, vllm_ascend/ops/vocab_parallel_embedding.py, vllm_ascend/quantization/quantizer.py, vllm_ascend/utils.py
Register VocabParallelEmbedding instead of overwrite forward
N/A
- vLLM main: https://github.com/vllm-project/vllm/commit/644d57d53191b94d9e50a4765891c498790d924b
=> [CustomOp] Register VocabParallelEmbedding instead of overwrite forward

tests/ut/quantization/test_w4a8_dynamic.py, vllm_ascend/quantization/w4a8_dynamic.py, vllm_ascend/quantization/w8a8_dynamic.py
After moved torchair related quantization section into torchair_quantization, split the torchair from the origin quantization
NO
vLLM version: main
vLLM main: https://github.com/vllm-project/vllm/commit/ab9f2cfd1942f7ddfee658ce86ea96b4789862af
- vLLM main: https://github.com/vllm-project/vllm/commit/69244e67e6822f1c15816f887659e1ccc18c2632
=> [4/N][refactor]delete torchair from quantization

.github/workflows/vllm_ascend_test.yaml, vllm_ascend/patch/worker/patch_common/__init__.py, vllm_ascend/patch/worker/patch_common/patch_logits.py
The mergence of the upstream https://github.com/vllm-project/vllm/pull/22592 caused a vllm-ascend LoRA inference bug. The details are following:
According to [torch_npu/npu/_stream_check.py](https://github.com/Ascend/pytorch/blob/863b9071cbdf47023c12c246e3efa9c6e2285fc6/torch_npu/npu/_stream_check.py#L74), NPU device type tensors have attributes is_cuda=True and is_npu=True. This causes that vLLM's apply_repetition_penalties function will run into the branch of "if logits.is_cuda and logits.is_contiguous()" and call the custom op implemented in CUDA, which is not compatible with NPU.
No.
pytest -sv tests/e2e/singlecard/test_ilama_lora.py
pytest -sv tests/e2e/multicard/test_ilama_lora_tp2.py
- vLLM main: https://github.com/vllm-project/vllm/commit/fe8d7b6f03e7d8a36 …
=> [Bugfix][LoRA][Patch] Fix the LoRA inference bug after upstream vLLM codebase changed

vllm_ascend/worker/model_runner_v1.py
In the pd Disaggregation scenario, the first token of the inference after the d node receives the kv follows the eager mode.
Fixes:
Running with MTP torchair graph mode with Prefilling Decoding Disaggregation , if all requests processed by the D node are requests just transmitted from the P node, it will break the torchair graph.
Reason: During PD Disaggregation , the P node only transmits the KV cache and prompt to the D node, not the actual tokens inferred (neither the main model tokens nor the MTP tokens are transmitted). Therefore, the D node will treat this request as one without MTP tokens for inference (seq_len=1).
The community does not have graph mode issues because the community's attention has a seq_len=1 for each batch during the decode phase.
We have issues because the graph …
=> [0.9.1][BUGFIX] [mtp][pd] FIX mtp torchair bug

.github/actionlint.yaml, .github/workflows/vllm_ascend_dist.yaml
Add e2e ci test for A3
- vLLM main: https://github.com/vllm-project/vllm/commit/11a7fafaa8807bfeea4b60466c576ec6a7031bfd
=> [CI] Add e2e ci test for A3

vllm_ascend/torchair/torchair_model_runner.py, vllm_ascend/worker/model_runner_v1.py
It is confirmed that `num_input_tokens` must be assigned the value of `maybe_padded_num_tokens` under all circumstances.
None.
Waiting for daily test for TorchAir.
- vLLM main: https://github.com/vllm-project/vllm/commit/006477e60b49babfca96352c7c648f10fff4a053
=> [Fix] Resolve data-parallel (DP) assertion errors in TorchAir

examples/disaggregated_prefill_v1/load_balance_proxy_server_example.py
Resolve the issue of waiting queue accumulation when requests are canceled.
No
By ci
- vLLM main: https://github.com/vllm-project/vllm/commit/006477e60b49babfca96352c7c648f10fff4a053
=> [MAIN][BUGFIX] BugFix: Resolve the issue of waiting queue accumulation when requests are canceled. 

tests/e2e/multicard/test_qwen3_moe.py, vllm_ascend/ops/common_fused_moe.py
1. quickfix mc2 operator error in aclgraph + ep<16 scenario to recover CI, will be refactorred in the future
2. disable aclgraph when testing w8a8
- vLLM main: https://github.com/vllm-project/vllm/commit/95089607fa307c5facfb9706ea919292fb56e78c
=> [Bugfix] Fix mc2 operator error in aclgraph + ep<16 scenario

tests/ut/core/test_scheduler.py, tests/ut/kv_connector/utils.py, tests/ut/test_platform.py
https://github.com/vllm-project/vllm/commit/69f46359dd5b36c1a059a0a8b729be1bd86394e8
- vLLM main: https://github.com/vllm-project/vllm/commit/d660c98c1b59580af97d6c7dd162c7c8894d40ed
=> [CI] fix UT error.

tests/ut/torchair/test_utils.py, vllm_ascend/torchair/utils.py
bugfix for torchair graph
No
- vLLM main: https://github.com/vllm-project/vllm/commit/67c14906aaa480d4fee2606f31c784ae21f8a633
=> bugfix for torchair graph

tests/ut/torchair/ops/test_torchair_rotary_embedding.py, vllm_ascend/torchair/ops/torchair_rotary_embedding.py, vllm_ascend/torchair/torchair_model_runner.py, vllm_ascend/torchair/utils.py
Move torchair related rotary ops into torchair dir to make the code clear. Next step we'll remove all torchair related code outside of torchair rotary ops.
No
vLLM version: main
vLLM main: https://github.com/vllm-project/vllm/commit/ab9f2cfd1942f7ddfee658ce86ea96b4789862af
- vLLM main: https://github.com/vllm-project/vllm/commit/81eea3d348c26fb1e6ff0185ad109aedd60a28a2
=> [5/N][refactor]add torchair rotary ops

tests/ut/ops/test_rotary_embedding.py, vllm_ascend/ops/rotary_embedding.py
After moved torchair related rope ops into torchair_ops, split the torchair from the origin rope ops to make the code clean.
No
vLLM version: main
vLLM main: https://github.com/vllm-project/vllm/commit/ab9f2cfd1942f7ddfee658ce86ea96b4789862af
- vLLM main: https://github.com/vllm-project/vllm/commit/81eea3d348c26fb1e6ff0185ad109aedd60a28a2
=> [6/N][refactor]delete torchair in rotary ops

vllm_ascend/patch/platform/patch_0_9_1/patch_core.py
patch run_engine_core in qwen will introduce preformance degradation in qwen, so we only enable it in EXTERNAL_DP_LB_ENABLED case
no
by ci
=> rm ptach run_engine_core in dense case

tests/e2e/singlecard/spec_decode_v1/test_v1_mtp_torchair_correctness.py, tests/ut/torchair/ops/test_torchair_fused_moe.py, vllm_ascend/torchair/ops/torchair_fused_moe.py, vllm_ascend/worker/mtp_proposer_v1.py
Fix MTP torchair bug caused by torchair refactor and moe refactor
Depends on PRs:
fused moe fix: https://github.com/vllm-project/vllm-ascend/pull/2627 
torchair multi DP fix: https://github.com/vllm-project/vllm-ascend/pull/2626
when dp is enabled, to run mtp online server, need to disable server log due to the current metrics does not support multi dp
`--disable-log-stats`
- vLLM main: https://github.com/vllm-project/vllm/commit/7c8271cd1e85670bd60c058441e1a224421dea01
=> [V1][BUGFIX][0.10.1] FIX mtp on main branch

vllm_ascend/torchair/utils.py
Due to the registration mechanism, torchair ops can not take effect， so have to patch the Ascend ops to adapt torchair
No
vLLM version: main
vLLM main: https://github.com/vllm-project/vllm/commit/7ea22e42d5f666a26b3ce4117724dadfdb4d3887
- vLLM main: https://github.com/vllm-project/vllm/commit/7ea22e42d5f666a26b3ce4117724dadfdb4d3887
=> [7/N][refactor]fix torchair rope ops

.github/workflows/vllm_ascend_test.yaml, tests/e2e/singlecard/spec_decode_v1/test_v1_mtp_correctness.py, tests/e2e/singlecard/spec_decode_v1/test_v1_mtp_torchair_correctness.py
enable MTP torchair e2e test
- vLLM main: https://github.com/vllm-project/vllm/commit/ce30dca5c44353f278dc114bd6f03b11700088eb
=> [CI] Enable MTP torchair e2e test

tests/ut/quantization/test_w8a8.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/ops/layers/experts_selector.py
This PR enables `npu_moe_gating_top_k_softmax` when running quantized MoE (such as W8A8). This op in fact makes no distinction between quantized and non-quantized scenarios. Introducing this op reduces 3~4ms for TPOT.
No.
- vLLM main: https://github.com/vllm-project/vllm/commit/ce30dca5c44353f278dc114bd6f03b11700088eb
=> [Perf]Enable npu_moe_gating_top_k_softmax on quantized scenarios

.github/workflows/vllm_ascend_dist.yaml
Disable per-PR triggering for A3 for now, we trigger the dist test in the label `dist-test` rather than
- vLLM main: https://github.com/vllm-project/vllm/commit/136d853e65a91a21b08227217b51daaba2d5cc71
=> [CI] Disable per-PR triggering for A3

tests/ut/models/test_qwen2_5_vl_without_padding.py, vllm_ascend/models/qwen2_5_vl_without_padding.py
Correct `AscendQwen2_5_VLForConditionalGeneration_Without_Padding` override methods
- vLLM main: https://github.com/vllm-project/vllm/commit/42dc59dbaceb2b9aa1477e9b3e0c33b379678468
=> [Bugfix] Fix qwen2.5-vl-without-padding

docs/source/conf.py, docs/source/tutorials/large_scale_ep.md, tests/conftest.py, tests/multicard/test_model_qwen3_w4a8.py, tests/singlecard/core/test_ascend_scheduler.py, tests/singlecard/test_ascend_config.py, vllm_ascend/platform.py
This PR enforces the forcible disabling of the chunked prefill feature in Non-MLA models, as the performance of operators supporting this functionality is currently suboptimal. 
At the same time, in engine v1 mode, the ascend scheduler is forcibly enabled, and the `enable_chunked_prefill` specified by the user in additional_config is disabled.
No.
=> [v0.9.1][bugfix] disable the chunked prefill feature in Non-MLA LLMs

.github/workflows/vllm_ascend_test.yaml
See #2687 we notice that test_platform and test_vocab_parallel_embedding is unstable, let's skip them first.
=> [CI] skip unstable UT

vllm_ascend/core/scheduler.py
bugfix ascend schedule encountered an incorrect req block length in the check_watermark_for_prefill function
- vLLM main: https://github.com/vllm-project/vllm/commit/426cc8629f7e630e1c5a0b96fe2db737a170a06d
=> [bugfix] ascend schedule encountered an incorrect req block length in the check_watermark_for_prefill function

.github/ISSUE_TEMPLATE/900-release-checklist.yml, README.md, README.zh.md, docs/source/_templates/sections/header.html, docs/source/community/versioning_policy.md, docs/source/faqs.md, docs/source/user_guide/release_notes.md
Add release note for 0.9.1
- vLLM main: https://github.com/vllm-project/vllm/commit/8bd5844989373d6914f6dea94a56822e6d7380d4
=> [Doc] add v0.9.1 release note

tests/ut/kv_connector/test_mooncake_connector.py, vllm_ascend/distributed/mooncake_connector.py, vllm_ascend/envs.py
In vllm version 0.10.1, a new KVOutputAggregator was added to the executor, moving aggregation to the executor(https://github.com/vllm-project/vllm/pull/19555). This caused mooncake_connector to break. This change aims to fix this bug and also adds a policy to forcibly release the KV cache when the prefill node times out.
This PR is currently linked to a PR in vllm (https://github.com/vllm-project/vllm/pull/23917). The vllm PR aims to modify the finish and send count confirmation in heterogeneous TP situations.
feature timeout
The reason for deleting many UTs is that a lot of communication codes have been deleted, so the UT as a whole will appear more concise.
- vLLM main: https://github.com/vllm-project/vllm/commit/fa4311d85f3a5f6d445f20429ca6d38122908eeb
=> [P/D]mooncake_connector adapted to 0.10.1

tests/ut/worker/test_model_runner_v1.py, vllm_ascend/ops/common_fused_moe.py, vllm_ascend/quantization/w8a8_dynamic.py, vllm_ascend/worker/model_runner_v1.py
Refactors the Mixture-of-Experts (MoE) communication method selection logic. The choice between all-gather, all-to-all, and mc2 is now determined by expert parallel configuration, SoC version (A2/A3), and token count for better performance.
None.
Added.
- vLLM main: https://github.com/vllm-project/vllm/commit/eafa8dcde63d625350ed618db4dd1cbcbaae77a1
=> [Fix][MoE] Refine MoE communication strategy

.github/workflows/image_310p_openeuler.yml, .github/workflows/image_310p_ubuntu.yml, .github/workflows/image_a3_openeuler.yml, .github/workflows/image_a3_ubuntu.yml, .github/workflows/image_openeuler.yml, .github/workflows/image_ubuntu.yml
Remove git .extraheader and fecth all commtis in /vllm-workspace/vllm-ascend
No
CI passed
Closes: https://github.com/vllm-project/vllm-ascend/issues/2735
- vLLM main: https://github.com/vllm-project/vllm/commit/51d5e9be7dbf4d914374447548dd01f9bfb68f89
=> Remove git .extraheader and fecth all commtis in /vllm-workspace/vllm-ascend

tests/ut/attention/test_attention_v1.py, vllm_ascend/attention/attention_v1.py
fix prefill attention bug，not support sliding window. npu_fused_infer_attention_score head_dim only equal 128, not support other number.
remove prefill phase npu_fused_infer_attention_score
=> [fix] prefill unsupport sliding window attention

docs/source/tutorials/index.md, docs/source/tutorials/multi_node_pd_disaggregation.md, examples/disaggregated_prefill_v1/gen_ranktable.py, examples/disaggregated_prefill_v1/gen_ranktable.sh
The PR is for the document of the prefiller&decoder disaggregation deloyment guide. 
The scenario of the guide is:
- Use 3 nodes totally and 2 NPUs on each node
- Qwen3-30B-A3B
- 1P2D
- Expert Parallel
The deployment can be used to verify PD Disggregation / Expert Parallel features with a slightly less resources.
No.
No.
=> [DOC] Qwen3 PD disaggregation user guide

tests/ut/ops/test_ascend_forwad_context.py, vllm_ascend/ascend_forward_context.py, vllm_ascend/ops/moe_dispatcher/token_dispatcher.py
=> add gatherep select.

vllm_ascend/worker/model_runner_v1.py
Removes the condition that skips metadata synchronization when `enforce_eager` is enabled.
This change is necessary to correctly sync the `with_prefill` and `enable_dbo` flags across all data parallel ranks, which is not required in the base implementation. Forcing the sync operation prevents potential inconsistencies, albeit with a minor performance impact.
None.
Add a E2E online test case?
=> [Fix] Ensure metadata sync across DP ranks in eager mode

.github/actionlint.yaml, .github/workflows/accuracy_test.yaml, .github/workflows/vllm_ascend_doctest.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_long_term.yaml
Switch Infra to linux-aarch64-a2 and python to 3.11
Soft backport: https://github.com/vllm-project/vllm-ascend/pull/2065
Soft backport: https://github.com/vllm-project/vllm-ascend/pull/2072
No
CI passed
search all: `linux-arm64-npu` and `3.10`
=> [v0.9.1] Switch Infra to linux-aarch64-a2 and python to 3.11

vllm_ascend/torchair/torchair_model_runner.py, vllm_ascend/worker/model_runner_v1.py
fix https://github.com/vllm-project/vllm-ascend/issues/2702
- A2: skip graph_size  update that makes it to tp_size because dispatch/combine op support different batch size across EP ranks
- A3: add `max_num_reqs = max(new_graph_batch_sizes)` to fix graph_size and max_num_reqs mismatch
Nope
=> [Bugfix]fix bug when graph_size is not divisible by tp_size

vllm_ascend/ops/fused_moe.py
line 408 already declared mc2_mask ,  remove duplicated unused code
no
- vLLM main: https://github.com/vllm-project/vllm/commit/60f0843ef8fb4b0c4e6788acc042873a0a2ea2a1
=> Remove unused code in fused_moe.py

vllm_ascend/models/deepseek_v2.py, vllm_ascend/ops/common_fused_moe.py, vllm_ascend/patch/platform/patch_common/patch_shared_fused_moe.py
Really strange that `register_oot` doesn't work with `SharedFusedMoE`, so we have to add this patch, for now.
None.
This PR won't have any effect in DeepSeek since we currently still stick with the old `CustomDeepseekV2`.
- vLLM main: https://github.com/vllm-project/vllm/commit/0cdd213641d7adcf7ad0e9cf79867344ea1291d9
=> [Fix] Fix SharedFusedMoE

tests/ut/ops/test_common_fused_moe.py, vllm_ascend/ops/common_fused_moe.py
In reinforcement learning scenarios, weight updates are required, but the current inference applies a transpose operation to the weights, altering their shape. This causes a shape mismatch with the training weights, triggering an error during weight updates.
- vLLM main: https://github.com/vllm-project/vllm/commit/6fb27881634d89c2e70e9e5fbad1b918c0d916cf
=> add weight transpose check.

.github/workflows/accuracy_test.yaml, .github/workflows/nightly_benchmarks.yaml, .github/workflows/vllm_ascend_dist.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_310p.yaml, .github/workflows/vllm_ascend_test_full.yaml, Dockerfile, Dockerfile.310p, Dockerfile.310p.openEuler, Dockerfile.a3, Dockerfile.a3.openEuler, Dockerfile.openEuler, docs/source/conf.py, tests/ut/core/test_scheduler.py, tests/ut/kv_connector/utils.py, vllm_ascend/core/scheduler.py, vllm_ascend/models/qwen3_moe.py, vllm_ascend/ops/common_fused_moe.py, vllm_ascend/sample/sampler.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/npu_input_batch.py, vllm_ascend/worker/worker_v1.py
Remove compatibility maintenance for vllm v0.10.1 and v0.10.1.1
branch main of vllm-ascend will not be compatible with vllm v0.10.1 and v0.10.1.1
- vLLM main: https://github.com/vllm-project/vllm/commit/6fb27881634d89c2e70e9e5fbad1b918c0d916cf
=> [CI] Remove compatibility maintenance for vllm v0.10.1 and v0.10.1.1

csrc/torch_binding.cpp
**Background:**
A dynamic library named vllm_ascend_C.so will be generated when compiling vLLM-Ascend, so when import vllm_ascend.vllm_ascend_C in python, the interperter will search vllm_ascend_C.so and try to find a external symbol named PyInit_vllm_ascend_C which is provided in csrc/camem_allocator.cpp.
**Conclusion:**
The PyInit__C is redundent.
- vLLM main: https://github.com/vllm-project/vllm/commit/717fc00e98c18d183f9141393b4185ddfb6606b3
=> [Code clean] Remove the unnecessary code

.github/workflows/accuracy_test.yaml, .github/workflows/nightly_benchmarks.yaml, .github/workflows/vllm_ascend_dist.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_310p.yaml, .github/workflows/vllm_ascend_test_full.yaml, Dockerfile, Dockerfile.310p, Dockerfile.310p.openEuler, Dockerfile.a3, Dockerfile.a3.openEuler, Dockerfile.openEuler, docs/source/conf.py
Upgrade vLLM version to 0.10.2rc2
Yes, image will use 0.10.2rc2 vLLM
- vLLM main: https://github.com/vllm-project/vllm/commit/f17c075884009a3bfb7c66cb0897719b8e18f196
=> Bump vLLM version to v0.10.2rc2

benchmarks/ops/ben_vocabparallelembedding.py, csrc/torch_binding.cpp, csrc/torch_binding_meta.cpp, tests/e2e/singlecard/ops/test_bgmv_expand.py, tests/e2e/singlecard/ops/test_bgmv_shrink.py, tests/e2e/singlecard/ops/test_rotary_embedding.py, tests/e2e/singlecard/ops/test_vocabparallelembedding.py, tests/ut/ops/test_rotary_embedding.py, tests/ut/torchair/ops/test_torchair_rotary_embedding.py, vllm_ascend/compilation/acl_graph.py, vllm_ascend/lora/lora_ops.py, vllm_ascend/meta_registration.py, vllm_ascend/ops/__init__.py, vllm_ascend/ops/rotary_embedding.py, vllm_ascend/torchair/ops/torchair_rotary_embedding.py, vllm_ascend/utils.py
**Background:**
There are two principles about operator registration in PyTorch
- The same namespace can be only registered once by `TORCH_LIBRARY`
- The operator signatures can be only registered once by `def`
Considering that all custom operators defined in the current repo are only used by Ascend, instead of defining a common operator schema by vLLM, all accelerators then follow this operator schema and complete the implementation based on their respective hardware, which is conducive to functional abstraction.
Therefore, we can rename the operator registration namespace to an Ascend-specific namespace(**_C_ascend**).
Related ISSUE: https://github.com/vllm-project/vllm-ascend/issues/2742
- vLLM main: https://github.com/vllm-project/vllm/commit/f592b3174b39a7aeac5243 …
=> Fix the bugs about operator registration by PyTorch Dispatcher

.github/workflows/accuracy_test.yaml, .github/workflows/nightly_benchmarks.yaml, .github/workflows/vllm_ascend_dist.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_310p.yaml, .github/workflows/vllm_ascend_test_full.yaml, .github/workflows/vllm_ascend_test_pd.yaml, Dockerfile, Dockerfile.310p, Dockerfile.310p.openEuler, Dockerfile.a3, Dockerfile.a3.openEuler, Dockerfile.openEuler, README.md, README.zh.md, docs/source/conf.py, docs/source/installation.md
Upgrade CANN version to 8.3.rc1.alpha001
No
- vLLM version: v0.10.2rc2
- vLLM main: https://github.com/vllm-project/vllm/commit/89e08d6d180c76019daa5aa1bbf7759dfaedde2e
=> Upgrade CANN version to 8.3.rc1.alpha001

tests/ut/kv_connector/test_mooncake_connector.py, vllm_ascend/distributed/mooncake_connector.py
This PR is used to adapt the hostname format for Mooncake when using adxl. When Mooncake uses adxl, it is necessary to set ```USE_ASCEND_DIRECT``` to True in the file ```/Mooncake/mooncake-common/common.cmake``` during compilation. The mooncake_connector obtains this config by calling ```vllm_config.kv_transfer_config.get_from_extra_config```, determines whether Mooncake is using adxl, and selects the corresponding hostname format.
No.
By CI.
- vLLM main: https://github.com/vllm-project/vllm/commit/d21a36f5f9569949dd6c313deed609d77e393850
=> fix mooncake connector adxl hostname usage

.github/workflows/accuracy_test.yaml, .github/workflows/nightly_benchmarks.yaml, .github/workflows/vllm_ascend_dist.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_310p.yaml, .github/workflows/vllm_ascend_test_full.yaml, Dockerfile, Dockerfile.310p, Dockerfile.310p.openEuler, Dockerfile.a3, Dockerfile.a3.openEuler, Dockerfile.openEuler, docs/source/conf.py
Bump vLLM version to v0.10.2
No
CI passed
- vLLM version: v0.10.2rc3
- vLLM main: https://github.com/vllm-project/vllm/commit/15b8fef453b373b84406207a947005a4d9d68acc
=> Bump vLLM version to v0.10.2

tests/ut/core/test_schedule_config.py, tests/ut/core/test_scheduler.py, vllm_ascend/core/schedule_config.py, vllm_ascend/core/scheduler.py
On main, AscendScheduler does not support Multimodels, becuse of lacking of scheduled_encoder_inputs which is need on multimodels inference
No
vLLM version: main@93e28e6862669e3b5cf47cea9f782a65ec47e155
- vLLM version: v0.10.2rc2
- vLLM main: https://github.com/vllm-project/vllm/commit/15b8fef453b373b84406207a947005a4d9d68acc
=>  main add ascend scheduler support multimodal

tests/e2e/singlecard/test_vlm.py, tests/ut/worker/test_model_runner_v1.py, vllm_ascend/worker/model_runner_v1.py
- Fix world size bug in model_runner to make sure ep>16 runs with MC2 
- enable e2e test for vl
Co-Authored-By: whx-sjtu <2952154980@qq.com>
Co-Authored-By: Icey <1790571317@qq.com>
- vLLM main: https://github.com/vllm-project/vllm/commit/3e903b6cb4292ca1425a37cb809c1e3cddfdadcb
=> [BugFix] Fix world size bug in model_runner

examples/disaggregated_prefill_v1/gen_ranktable.py, examples/disaggregated_prefill_v1/load_balance_proxy_server_example.py
fix all cards super_pod_id same on A3 & proxy support min_tokens
2*A3 gen ranktable
before:
"prefill_device_list": [
{
"server_id": "xxx",
"device_id": "0",
"device_ip": "xxx",
"super_pod_id": "0",
"super_device_id": "106758159",
"cluster_id": "1"
},
{
"server_id": "xxx",
"device_id": "1",
"device_ip": "xxx",
"super_pod_id": "0",
"super_device_id": "106758159",
"cluster_id": "2"
}...
after:
"prefill_device_list": [
{
"server_id": "xxx",
"device_id": "0",
"device_ip": "xxx",
"super_pod_id": "0",
"super_device_id": "104857600",
"cluster_id": "1"
},
{
"server_id": "xxx",
"device_id": "1",
"device_ip": "xxx",
"super_pod_id": "0",
"super_device_id": "104923137",
"cluster_id": "2"
}...
=> fix all cards super_pod_id same on A3 & proxy support min_tokens

docs/source/tutorials/multi_npu_qwen3_next.md
Update max_tokens and prompt in qwen3 online doc
Before:
```
"'max_tokens' or 'max_completion_tokens' is too large: 4096. This model's maximum context length is 4096 tokens and your request has 18 input tokens (4096 > 4096 - 18). None"
```
After:
```
curl http://localhost:8000/v1/chat/completions -H "Content-Type: application/json" -d '{
"model": "/root/.cache/modelscope/hub/models/Qwen-SGlang/Qwen3-Next-80B-A3B-Instruct",
"messages": [
{"role": "user", "content": "Who are you?"}
],
"temperature": 0.6,
"top_p": 0.95,
"top_k": 20,
"max_tokens": 32
}'
.{"id":"chatcmpl-8ddbd65c9ddc405397219a6792feb9a0","object":"chat.completion","created":1757985049,"model":"/root/.cache/modelscope/hub/models/Qwen-SGlang/Qwen3-Next-80B-A3B-Instruct","choices":[{"index":0,"message":{"role":"assistant","content …
```
=> Update max_tokens and prompt in qwen3 online doc

vllm_ascend/platform.py, vllm_ascend/worker/block_table.py, vllm_ascend/worker/model_runner_v1.py
This pr fixes a few issues on prefill disaggregation:
1. Fix prefill disaggregation kvcache addr alignment issue, llmdatadist needs the addr of tensors to be aligned with 2M
2. Fix prefill disaggregation kvcache shape error, llmdatadist requires k/v tensors with shape [num_blocks, ...], however the implentment before this pr is  [2, num_blocks, ...], which will break prefill disaggregation
3. Use hybrid kv cache only when running qwen3_next to fix accuracy issue on prefill disaggregation.
N/A
Tested locally by @liziyu179 
- vLLM main: https://github.com/vllm-project/vllm/commit/4f02b77de4e794a0d417ed98a26884208f75e043
=> [HybridKV] Fix prefill disaggregation kvcache addr alignment & use hybrid kv cache only when running qwen3_next

vllm_ascend/ops/moe/token_dispatcher.py
Add missing barrier when no implicit synchonize by `repeat_interleave` is available. Otherwise, the `non_blocking=True` copy of `output_splits` and `input_splits` from NPU may failed to complete before later `async_all_to_all` uses them.
- vLLM main: https://github.com/vllm-project/vllm/commit/ef7eefe17a7dc212ddb8a8aabd7760218a10e25e
=> [Bugfix] Fix async copy bug under single expert scenario

tests/ut/attention/test_attention_v1.py, vllm_ascend/attention/attention_v1.py
Fix shape not match when test LLM-Research/Phi-4-mini-instruct accuarcy 
command:
```bash
VLLM_USE_MODELSCOPE=True lm_eval --model vllm \
--model_args pretrained=LLM-Research/Phi-4-mini-instruct,max_model_len=4096,dtype=auto,tensor_parallel_size=1 \
--tasks gsm8k \
--apply_chat_template \
--fewshot_as_multiturn \
--batch_size auto \
--num_fewshot 5 \
--output ./
```
error log:
https://github.com/vllm-project/vllm-ascend/actions/runs/17545954577/job/49829202227?pr=2330
```
(EngineCore_0 pid=3273) ERROR 09-08 09:55:40 [core.py:702] EngineCore encountered a fatal error.
(EngineCore_0 pid=3273) ERROR 09-08 09:55:40 [core.py:702] Traceback (most recent call last):
(EngineCore_0 pid=3273) ERROR 09-08 09:55:40 [core.py:702]   File "/__w/vllm-ascend/vllm-ascend/vllm-empty/vllm/v1/engine/core.py", …
```
=> [Fixbug] Fix shape not match when sliding_window and dynamic batch_size

vllm_ascend/spec_decode/mtp_proposer.py, vllm_ascend/torchair/torchair_model_runner.py
This PR prepares for deleting this enviroment variable, `VLLM_TEST_DYNAMO_FULLGRAPH_CAPTURE`, as vllm requires `fullgraph=True` to run
- Fixes https://github.com/vllm-project/vllm/issues/21834
No
See CI 
- vLLM main: https://github.com/vllm-project/vllm/commit/99cc41ad50c08e745571abe568226f9fcae61ccd
=> [Bugfix] Remove `VLLM_TEST_DYNAMO_FULLGRAPH_CAPTURE`

.github/workflows/format_pr_body.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_full.yaml, tests/e2e/singlecard/test_guided_decoding.py, tests/ut/ops/test_fused_ops.py, tests/ut/torchair/ops/test_torchair_fused_moe.py, vllm_ascend/ops/fused_moe.py, vllm_ascend/patch/worker/patch_common/__init__.py, vllm_ascend/platform.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/spec_decode/mtp_proposer.py, vllm_ascend/torchair/ops/torchair_fused_moe.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/npu_input_batch.py
1. This pr bump vllm commit to https://github.com/vllm-project/vllm/commit/6d8246aaffff3ebec84767e373212a7b8da328e2
2. fix upstream changes https://github.com/vllm-project/vllm/pull/24548 abort multi-modal kwargs, make vllm main and `v0.10.2` both adaptable
3. fix metadata_builder changes introduced by https://github.com/vllm-project/vllm/pull/23693
4. fix `structured_outputs_config` changes introduced by https://github.com/vllm-project/vllm/pull/22772
5. fix `moe_config` changes introduced by https://github.com/vllm-project/vllm/pull/22537
Co-authored-by:  MengqingCao <cmq0113@163.com>
Co-authored-by:  Yikun Jiang <yikunkero@gmail.com>
- vLLM main: https://github.com/vllm-project/vllm/commit/c60e6137f0bf2034853919b3a9d705d7e06b93cf
=> [CI] Upgrade vLLM to 20250919 (6d8246aa) and fix some broken issue

.github/workflows/format_pr_body.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_full.yaml, tests/e2e/conftest.py, vllm_ascend/sample/sampler.py
Bump main to https://github.com/vllm-project/vllm/commit/c60e6137f0bf2034853919b3a9d705d7e06b93cf
- Updated imports in `vllm.config` to `vllm.config.model`(https://github.com/vllm-project/vllm/commit/aed16879a9191a58adc5b8ac3973454dddefe018) https://github.com/vllm-project/vllm/pull/25252
- Refactored `vllm_ascend/sample/sampler.py` to use string values for `logprobs_mode` instead of the `LogprobsMode` enum, simplifying logprobs mode handling and improving compatibility with recent vLLM changes (https://github.com/vllm-project/vllm/commit/aed16879a9191a58adc5b8ac3973454dddefe018) https://github.com/vllm-project/vllm/pull/25252
No
CI passed
- vLLM main: https://github.com/vllm-project/vllm/commit/6d8246aaffff3ebec84767e373212a7b8da328e2
=> [CI] Upgrade vLLM to 20250920 (c60e613) and address config break

.github/workflows/_e2e_test.yaml, .github/workflows/accuracy_test.yaml, .github/workflows/nightly_benchmarks.yaml, .github/workflows/vllm_ascend_doctest.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_full_vllm_main.yaml
1. Refactor ci to reuse base workflow and enable main 2 hours trigger job:
- Extract e2e test in to _e2e_test.yaml
- Reuse _e2e_test in light / full job
- Enable main 2 hours trigger job
2. Rename e2e test to ascend test to make sure action display label 
3. Re-enable ut coverage which was failed since https://github.com/vllm-project/vllm-ascend/commit/5bcb4c1528311b8f20c91a9239ac38172f002fcb  and disable on https://github.com/vllm-project/vllm-ascend/commit/6d8bc38c7b0faba0b666585a09b7523c7714b9cc
Only developer behavior changes:
- Every job trigger full test with vllm release and hash
- Run full job per 2 hours with vllm main
- e2e light test (30 mins): `lint` (6mins) ---> ut (10mins) ---> `v0.10.2 + main / 4 jobs` (15mins)
- e2e full test (1.5h): `ready label` ---> `v0.10.2 + main / 4 …
=> Refactor ci to reuse base workflow and re-enable ut coverage

.github/workflows/pre-commit.yml, .github/workflows/vllm_ascend_test.yaml
Followup on https://github.com/vllm-project/vllm-ascend/pull/3064
1. should limit vllm version to the same hash with mypy
2. fix the vllm version bug for e2e light test.
no
CI passed
- vLLM main: https://github.com/vllm-project/vllm/commit/c60e6137f0bf2034853919b3a9d705d7e06b93cf
=> [CI] Enable main based lint check and light ci matrix

vllm_ascend/attention/attention_mask.py, vllm_ascend/attention/attention_v1.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner_v1.py
Add new npu_fused_infer_attention_score op to improve perfomance in splitfuse cases and resolve long-seq mask problems .
1. The original op's performance is suboptimal in certain scenarios, necessitating optimization through the _new op_ (npu_fused_infer_attention_score)。
2. For ultra-long sequences (128k), the original operator will allocate a large attn_mask, which consumes excessive CPU memory. In contrast, the _new op_ supports a fixed-size compressed mask, effectively resolving this issue.
NOTE1: The current PR retains the original logic and uses a version check of the CANN package to determine whether the _new op_ can be enabled. This ensures no impact on existing users. In future versions, this version check and the original logic will be deprecated, and the _new op_ scheduling …
=> [Perf] Add new npu_fused_infer_attention_score op to improve perfomance in splitfuse cases and resolve long-seq mask problems

vllm_ascend/ops/register_custom_ops.py
This PR removed the redundant log prints in register_custom_ops.py, in order to make output clear.
No.
- vLLM main: https://github.com/vllm-project/vllm/commit/9607d5eb449711b349d4c2bee0a9c94afcc7ed14
=> [main] remove the redundant log prints in register_custom_ops.py

examples/disaggregated_prefill_v1/mooncake_connector_store_deployment_guide.md, vllm_ascend/distributed/mooncake/mooncake_engine.py, vllm_ascend/worker/model_runner_v1.py
A new kv_role "kv_both" is added to run mixed deployment scenarios. The mixed deployment will involve a decode phase, where with_prefill should be false.
- vLLM main: https://github.com/vllm-project/vllm/commit/c60e6137f0bf2034853919b3a9d705d7e06b93cf
=> Fix of DeepSeek Error in KV Pool Mixed Deployment Scenario

vllm_ascend/worker/model_runner_v1.py
Fix the impact to LoRA that https://github.com/vllm-project/vllm/pull/25249 brought.
No.
pytest -sv tests/e2e/singlecard/test_ilama_lora.py
pytest -sv tests/e2e/multicard/test_ilama_lora_tp2.py
- vLLM main: https://github.com/vllm-project/vllm/commit/9607d5eb449711b349d4c2bee0a9c94afcc7ed14
=> [Bugfix][LoRA] Fix bug introduced by upstream vllm#25249

vllm_ascend/patch/__init__.py, vllm_ascend/patch/platform/patch_common/__init__.py, vllm_ascend/patch/platform/patch_common/patch_multimodal_merge.py
This PR aims to address the incompatibility of the `.masked_scatter_` operation in the current `_merge_multimodal_embeddings` function on Ascend. For now, it reverts to the previous version of the CPU operation, which can be executed asynchronously on the device side to enhance performance. 
None
=> [Model][VLM][Patch]Modify ascend affinity _merge_multimodal_embeddings

tests/e2e/vllm_interface/singlecard/test_sampler.py, tests/e2e/vllm_interface/vllm_test.cfg
Add OOT platform E2E test case to be run in the vllm buildkite pipeline. 
Note: added test case is not run in vllm-ascend CI.
NA
NA
Test result:
1.Test case: has run successfully in local host:
2.Added oot_test.cfg can been successfully get and parsed:
```
TEST_RUN_CONFIG_URL="https://raw.githubusercontent.com/leo-pony/vllm-ascend/refs/heads/main/tests/e2e/oot_interface/oot_test.cfg"
TEST_RUN_CONFIG_FILE="oot_test.cfg"
install_curl() {
if ! command -v curl &> /dev/null; then
sudo yum update
if sudo yum install -y curl; then
echo "'curl' was installed successfully."
else
echo "Error: Failed to install 'curl'. Please check your network connection and package repositories."
return 1
fi
fi
return 0
}
get_config() {
install_curl
if [ $? -ne 0 ]; then
return 1
fi
if curl -s -o …
```
=> Add OOT platform E2E test case to be run in the vllm buildkite pipeline

.github/workflows/format_pr_body.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_full.yaml, tests/ut/attention/test_attention_v1.py, tests/ut/ops/test_fused_ops.py, tests/ut/torchair/ops/test_torchair_fused_moe.py, vllm_ascend/attention/attention_v1.py
Upgrade vLLM to newest commit.
1. Remove the useless func get_state_cls, it has been removed from vLLM already. https://github.com/vllm-project/vllm/commit/e6750d0b18e07631bb2ea7f256f7dd444d4936fa
2. Fix ut broken by https://github.com/vllm-project/vllm/commit/6160ba4151084c78164a0f472ce4da04067f9705
- vLLM main: https://github.com/vllm-project/vllm/commit/b1068903fdca26cf6b4a1a51a32c3365ce3ac636
=> [CI] Upgrade vllm version - 0925

tests/e2e/singlecard/spec_decode_v1/test_v1_spec_decode.py, vllm_ascend/spec_decode/eagle_proposer.py
- Fix the bug https://github.com/vllm-project/vllm-ascend/issues/2978
- Enable e2e test,
- Adapt to scenarios where Speculative tokens are greater than 2,
- Fix the bug that causes Eagle3 inference failures under high concurrency and improve the acceptance rate of draft models,  by https://github.com/vllm-project/vllm-ascend/pull/2794
Co-authored-by: hukongyi [hukongyi@cmbchina.com](mailto:hukongyi@cmbchina.com)
Co-authored-by: guanyuzhu [zhuguanyu@huawei.com](mailto:zhuguanyu@huawei.com)
Co-authored-by: liumail680 [liumail680@163.com](mailto:liumail680@163.com)
=> [Bugfix] eagle and eagle3 spec decode failures and enable e2e test

tests/e2e/vllm_interface/vllm_test.cfg
Correct the vllm interface e2e test Base container image name
NA
Tests in vllm ci pipeline
=> [bugFix] Correct the vllm interface e2e test Base container image name

vllm_ascend/ops/moe/fused_moe_prepare_and_finalize.py
It is a quick bugfix for the memory explosion issue that requires further refactoring.
The dummy_run in eager mode may lead to OOM and the reason is that `hidden_states` were not released in time. 
The PR temporarily resolves the issue by manually clearing the cache, and further refactoring will be conducted subsequently. 
Before the modification, the dummy_run's memory showed an accumulation issue. 
After modification, it can be observed that the memory is released promptly. 
And it was verified that the model responded normally after a single data input. 
- vLLM main: https://github.com/vllm-project/vllm/commit/b1068903fdca26cf6b4a1a51a32c3365ce3ac636
=> [BugFix] Fix dummy_run memory explosion in eager mode

tests/ut/worker/test_model_runner_v1.py, vllm_ascend/worker/model_runner_v1.py
…to avoid unintentional copy ops blocking across different NPU streams, improving disagg TTIT/TTFT (#2788)"
This reverts commit 6995a7bc5be41908da9f64c2b8def298adf3b058. We'll add it back once the issue is fixed.
related issue: https://github.com/vllm-project/vllm-ascend/issues/3195
=> Revert "[Disagg][Perf] Use NPU event sync instead of blocking tolist

.github/workflows/format_pr_body.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_full.yaml, vllm_ascend/patch/worker/patch_common/patch_weight_loader.py, vllm_ascend/platform.py, vllm_ascend/quantization/quant_config.py, vllm_ascend/torchair/torchair_worker.py, vllm_ascend/worker/model_runner_v1.py, vllm_ascend/worker/worker_v1.py
Upgrade vLLM to newest commit
- Fix the aclgraph doesn't work problem, caused by https://github.com/vllm-project/vllm/commit/24fab45d96a91b491db338ee02cd24e55b7fbb5f
- Fix PoolerOutput import error, caused by https://github.com/vllm-project/vllm/commit/755ed7b05be4743237d3339c4ff8c22bcaae04f4
- Fix the aclgraph weight load error to keep the same with torchair fix. https://github.com/vllm-project/vllm/commit/4492e3a55428e161ca8db381edc28263e5da4c8d
No
All test should pass
=> [CI] Upgrade vllm to newest commit

vllm_ascend/platform.py
PR #2894 make ascend_scheduler_config.enabled always be `True` for non-mla models，when `ascend_scheduler_config.enabled=True `, it will always initialize `AscendScheduler` which is a subclass of `Scheduler`, but when we enbale async_scheduling,we need to initialize `AsyncScheduler` in vllm,  this will make async_scheduling can't be enabled.
not-related
when user set `async_scheduling`, it means user don't want to use `AscendScheduler`, so we shouldn't set `ascend_scheduler_config.enabled = True`
=> fix error async_scheduler can't be enabled

vllm_ascend/attention/mla_v1.py, vllm_ascend/spec_decode/mtp_proposer.py
fix bugs when mtp>1, and reorder input batch when mtp is not accepted.
no
by ci
=> bugfix for mtp>1

vllm_ascend/ops/linear_op.py
Addresses a bug in DenseOptimRowParallelOp that occurs when tensor parallelism is not used
No
=> [Bugfix] fix bug when tp=1

.github/workflows/_e2e_test.yaml, vllm_ascend/lora/utils.py
LoRA e2e test uses ilama-3.2-1B model. It uses transformers.py model files. Its self-attention layer names end with "\*.attn", not "\*.self_attn".
There are some other model attention layer names end with "*.attn", such as baichuan.py, bert.py.
No.
pytest -sv tests/e2e/singlecard/test_ilama_lora.py
pytest -sv tests/e2e/multicard/test_ilama_lora_tp2.py
- vLLM main: https://github.com/vllm-project/vllm/commit/17b4c6685ce62d5652654784d6771a3d38e4273e
=> [Bugfix][LoRA] Fix LoRA bug after supporting Qwen3-Next

.github/workflows/format_pr_body.yaml, .github/workflows/vllm_ascend_test.yaml, .github/workflows/vllm_ascend_test_full.yaml, vllm_ascend/models/qwen2_5_vl.py, vllm_ascend/models/qwen2_5_vl_without_padding.py, vllm_ascend/models/qwen2_vl.py
- Pin vLLM commit to releases/v0.11.0 branch.
- Fix the break change by vLLM commit https://github.com/vllm-project/vllm/commit/d4d9899860e75b2ef4aa6dda205c23e641876d24
no
- vLLM main: https://github.com/vllm-project/vllm/commit/17b4c6685ce62d5652654784d6771a3d38e4273e
=> [CI] Pin vLLM to releases/v0.11.0

.github/workflows/vllm_ascend_test_full_vllm_0.11.0.yaml
Add vLLM 0.11.0 release hourly job to monitor release branch changes
No
CI passed
=> Add vLLM 0.11.0 release hourly job

vllm_ascend/models/qwen2_5_vl.py, vllm_ascend/models/qwen2_5_vl_without_padding.py, vllm_ascend/models/qwen2_vl.py
Fix quant_config input parameter bug in qwenvl series. Currently, non-instantiated variables should be passed.
None
=> [Bugfix]Fix quant_config input parameter bug in qwenvl series

docs/source/faqs.md, tests/ut/test_utils.py, vllm_ascend/utils.py, vllm_ascend/worker/model_runner_v1.py
1. Solved the issue where sizes capture failed for the Qwen3-32b-int8 model when aclgraph, dp1, and tp4 were enabled.
2. Added the exception thrown when sizes capture fails and provided a solution
3. Add this common problem to the FAQ doc
no
ut
=> [BugFix] Fix ACLgraph bug in Qwen3_32b_int8 case

vllm_ascend/spec_decode/eagle_proposer.py
- Fixes https://github.com/vllm-project/vllm-ascend/issues/3024
N/A
```
python -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --served-model-name Eagle3 --port 8000  --model Qwen/Qwen3-8B   --seed 42     -tp 1  --speculative_config '{"model": "Tengyunw/qwen3_8b_eagle3", "draft_tensor_parallel_size": 1, "num_speculative_tokens": 5, "method": "eagle3"}'
```
Co-authored-by: liuruijin17 [ricklrj@outlook.com](mailto:ricklrj@outlook.com)
=> [Eagle] Fix attn_mask index out of range in high concurrency situations

vllm_ascend/core/scheduler.py
Running multimodal model with ascend scheduler may cause assert error 【assert (request.num_tokens - request.num_computed_tokens) == 1】
No
- vLLM main: https://github.com/vllm-project/vllm/commit/17b4c6685ce62d5652654784d6771a3d38e4273e
=> [BugFix] Fix ascend scheduler assert error

tests/ut/ops/test_fused_moe_prepare_and_finalize.py, tests/ut/ops/test_fused_ops.py, tests/ut/torchair/ops/test_torchair_fused_moe.py, vllm_ascend/models/qwen3_moe.py, vllm_ascend/ops/moe/fused_moe_prepare_and_finalize.py, vllm_ascend/torchair/models/qwen3_moe.py, vllm_ascend/torchair/ops/torchair_fused_moe.py
Fix `dpmetadata` and `Qwen3MoeSparseMoeBlock` break introduced by https://github.com/vllm-project/vllm/commit/26a7a33b88e38c45680aa6002b9d6e27875a39a3#diff-c1550d0a38469d039370567d8981969530cbfffc7302cd1778e7c2c8a9322dea
NOTE: we maintain a different sp in vllm-ascend with vllm, thus we can just use `cu_tokens_across_sp(1)` as `cu_tokens_across_dp_cpu`
close https://github.com/vllm-project/vllm-ascend/issues/3236, https://github.com/vllm-project/vllm-ascend/issues/3239
=> [CI][Bugfix] Quickfix for DPMetaData

vllm_ascend/ops/common_fused_moe.py, vllm_ascend/ops/register_custom_ops.py
This PR fixes accuracy problem of aclgraph on A2. The problem is introduced by PR #2980, which makes the `all_reduce` of shared_experts exposed to torch dynamo. This PR moves all the codes into forward_impl to shiled from torch dynamo.
- vLLM main: https://github.com/vllm-project/vllm/commit/17b4c6685ce62d5652654784d6771a3d38e4273e
=> [BugFix] Fix aclgraph accu problem in A2.

vllm_ascend/ops/fused_moe.py, vllm_ascend/platform.py
Fix dp+ep+tp inplace copy error when sp chunked the `hidden_states`.
test locally with the following scripts
```bash
python examples/offline_data_parallel.py \
--model="Qwen/Qwen3-30B-A3B" \
--dp-size=2 \
--tp-size=2 \
--enable-expert-parallel
```
=> [Quickfix] Fix dp+ep+tp error when sp chunked the hidden_states

.github/workflows/_e2e_test.yaml, tests/e2e/singlecard/spec_decode_v1/test_v1_mtp_correctness.py, tests/e2e/singlecard/spec_decode_v1/test_v1_mtp_torchair_correctness.py, tests/e2e/singlecard/spec_decode_v1/test_v1_spec_decode.py, tests/e2e/singlecard/test_guided_decoding.py, tests/e2e/singlecard/test_vlm.py
Fix CI by addressing max_split_size_mb config
No, test onyl
Full CI passed, espcially eagle one
=> [CI] Fix CI by addressing max_split_size_mb config

vllm_ascend/worker/model_runner_v1.py
Currently we run an extra profile_run with `num_tokens == self.mc2_tokens_capacity`. However, when setting `max_num_batched_tokens < self.mc2_tokens_capacity`, this will trigger an assertion error that requires num_tokens in `_dummy_run` to be smaller than `max_num_batched_tokens`. This PR skips this extra `profile_run` if `self.max_num_tokens <= self.mc2_tokens_capacity` so as to avoid this bug.
This PR fixes a bug that `kernel_block_sizes` never equals to `[self.cache_config.block_size]`. `kernel_block_sizes` is type of List[List[int]], so the condition should be `kernel_block_sizes != [[self.cache_config.block_size]]`. This also helps to resolve a issue that cpu_offload_gb cannot be enabled.
No.
- vLLM main: …
=> [bugfix] Fix bugs in _dumm_run and re-initialize kv-cache.
